Smithay/smithay

- Cargo.toml
- src/lib.rs
- src/shm/mod.rs
- src/shm/pool.rs
For now, the API is designed.
The actual memory-map logic remains to be implemented in shm/pool.rs
> [WIP] SHM helpers

- .rustfmt.toml
- .travis.yml
- Cargo.toml
- src/lib.rs
- src/shm/mod.rs
- src/shm/pool.rs
> Add rustfmt and clippy to travis build

- Cargo.toml
- src/backend/glutin.rs
- src/keyboard/mod.rs
- src/lib.rs
- src/shm/mod.rs
- src/shm/pool.rs
First draft of the keyboard handling with xkbcommon and forwarding events to the client.
The mechanism for choosing the keymap needs to be determined (`create_keyboard_handler` will change).
@Drakulix I'd like to have your opinion on the API and its implementation.
> keyboard: first draft of xkbcommon handling

- src/backend/graphics/egl.rs
- src/backend/libinput.rs
- src/backend/winit.rs
> Fix/Add winit&egl logging

- .travis.yml
- Cargo.toml
- doc_upload.sh
- examples/winit.rs
- src/backend/winit.rs
- src/seat/keyboard.rs
We were trying to swap_buffers while the xdg_surface had not been configured yet, which is a protocol error.
Also, remove travis-cargo, it's too useless.
> Fix winit backend on wayland

- Cargo.toml
- examples/drm.rs
- src/backend/drm/backend.rs
- src/backend/drm/mod.rs
Test of the current master of drm-rs.
All features are there and merged now and working. Waiting for the crates.io release by @Slabity and once that is done, I will update the Cargo.toml and this is mergable!
> Update to stable drm-rs version

- examples/winit.rs
- src/wayland/mod.rs
- src/wayland/output/mod.rs
- src/wayland/shm/mod.rs
> Add the output global

- src/backend/drm/backend.rs
- src/backend/drm/mod.rs
- src/backend/graphics/egl.rs
- src/backend/winit.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/roles.rs
- src/wayland/compositor/tree.rs
- src/wayland/output/mod.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/shell/mod.rs
- src/wayland/shell/wl_handlers.rs
- src/wayland/shell/xdg_handlers.rs
- src/wayland/shm/mod.rs
Some work towards getting #45 fixed :)
> Apply a bunch of clippy suggestions

- src/wayland/compositor/mod.rs
- src/wayland/output/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/shell/mod.rs
- src/wayland/shm/mod.rs
> Don't required EventLoop for wayland object creation

- .travis.yml
- Cargo.toml
- examples/udev.rs
- src/backend/drm/backend.rs
- src/backend/drm/mod.rs
- src/backend/libinput.rs
- src/backend/session/auto.rs
- src/backend/session/dbus/logind.rs
- src/backend/session/dbus/mod.rs
- src/backend/session/direct.rs
- src/backend/session/mod.rs
- src/backend/udev.rs
- src/lib.rs
- vagga.yaml
Remaining tasks todo:
Ready for review.
> Logind session

- src/backend/winit.rs
> Replace time stub with proper timestamps

- anvil/src/input_handler.rs
- anvil/src/main.rs
- anvil/src/shaders.rs
- anvil/src/shell.rs
- anvil/src/shm_load.rs
- anvil/src/udev.rs
- anvil/src/window_map.rs
- src/backend/drm/backend.rs
- src/backend/drm/mod.rs
- src/backend/graphics/egl/native.rs
- src/backend/input.rs
- src/backend/libinput.rs
- src/backend/session/auto.rs
- src/backend/session/direct.rs
- src/backend/udev.rs
- src/backend/winit.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/tree.rs
- src/wayland/output/mod.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/shell/legacy/mod.rs
- src/wayland/shell/legacy/wl_handlers.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shell/xdg/xdg_handlers.rs
- src/wayland/shell/xdg/zxdgv6_handlers.rs
- src/wayland/shm/mod.rs
- src/wayland/shm/pool.rs
- src/xwayland/x11_sockets.rs
More work towards #45. Should I run cargo fmt on the changed files, all files, or not at all?
> Address some more clippy warnings

- src/wayland/seat/keyboard.rs
Send keymaps to client using a new tempfile for each client, rather than
a single shared tempfile. Doing so prevents a client from tempering with
the contents of the tempfile, which would then cause other clients to
read a corrupted keymap.
See this bug report for details:
https://bugs.freedesktop.org/show_bug.cgi?id=101595
> wayland.seat: send keymaps in individual tempfiles

- CHANGELOG.md
- Cargo.toml
- src/backend/drm/mod.rs
- src/backend/libinput.rs
- src/backend/session/dbus/logind.rs
- src/backend/session/direct.rs
- src/backend/udev.rs
I also needed to add a few Debug `impl`s in calloop. https://github.com/Smithay/calloop/pull/5
> Fix compilation with calloop 0.4

- Cargo.toml
- anvil/Cargo.toml
- anvil/src/shell.rs
Upgrade all the other dependencies.
> Upgrade dependencies

- Cargo.toml
- src/lib.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/mod.rs
This is a first attempt at a handler for the `linux-dmabuf` protocol.
I still need to:
What do you think of the overall API @Drakulix ?
> Wayland dmabuf handler

- README.md
- anvil/build.rs
> anvil: properly document logind support

- Cargo.toml
- anvil/src/udev.rs
- examples/raw_drm.rs
- src/backend/drm/egl/mod.rs
- src/backend/drm/gbm/mod.rs
- src/backend/drm/gbm/session.rs
- src/backend/drm/gbm/surface.rs
- src/backend/drm/legacy/error.rs
- src/backend/drm/legacy/mod.rs
- src/backend/drm/legacy/session.rs
- src/backend/drm/legacy/surface.rs
- src/backend/drm/mod.rs
- src/wayland/dmabuf/mod.rs
Work-in-progress branch for the next iteration of `drm-rs`'s api (now supporting atomic-modesetting and planes much better!).
> drm-rs 0.4

- anvil/src/glium_drawer.rs
- src/backend/egl/display.rs
- src/backend/egl/mod.rs
Was checking egl extensions instead of gl extensions.
> Fix egl_to_texture check

- src/backend/udev.rs
Changes the behavior of `primary_gpu` to not just take the last `device` whose parent is marked as `boot_vga`, but the first, that successfully translates into a `PathBuf`.
> Fix primary_gpu

- anvil/src/glium_drawer.rs
- anvil/src/input_handler.rs
- anvil/src/shell.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
These should finally fix the last remaining clippy warnings.
> Clippy fixes

- Cargo.toml
- anvil/src/winit.rs
- src/xwayland/xserver.rs
I was curious to check out the project, and was surprised to find that it didn't build.  Later I found I was supposed to build and run from anvil/, but it seems like we should keep the top level green, too.
> Fix nix build issues in top level project

- Cargo.toml
- anvil/Cargo.toml
- anvil/src/input_handler.rs
- anvil/src/udev.rs
- src/backend/drm/common/fallback.rs
- src/backend/egl/surface.rs
- src/wayland/seat/pointer.rs
Updating calloop to 0.7 is left for a future PR as this update is nontrivial.
> Dependencies updates

- src/xwayland/xserver.rs
Handling SIGUSR1 requires setting a signal handler, which is a global
resource. This can also cause problems in the presence of threads, since
every thread needs to set up a signal handler. This commit instead
changes the code to use a pipe instead (actually a UnixStream). When the
child closes the pipe, the parent wakes up and knows "to do something".
Fixes: https://github.com/Smithay/smithay/issues/246
Signed-off-by: Uli Schlachter <psychon@znc.in>
> xwayland: Use pipe instead of signal

- src/backend/renderer/gles2/mod.rs
Fixes #267 
- Replace hardcoded type casts with platform alias types
> fix (cross)-compile for aarch64

- src/backend/renderer/gles2/mod.rs
wait for the GL commands to finish before submitting the buffer to the backend
> Workaround for screen flickering on drm/kms

- src/backend/renderer/gles2/mod.rs
Egl buffers from for example wl_drm are external managed and `is_alive()` will always return true.
> disable texture cache for egl imports

- src/backend/egl/display.rs
On my desktop system using MESA the egl query with `EGL_WAYLAND_Y_INVERTED_WL` will always return `EGL_FALSE` indicating that `EGL_WAYLAND_Y_INVERTED_WL` is not supported.
This will leave the orginal value of `0` in the `inverted` field. The spec of [EGL_WL_bind_wayland_display](https://www.khronos.org/registry/EGL/extensions/WL/EGL_WL_bind_wayland_display.txt) defines that a query returning `EGL_FALSE` should be treated like the buffer is inverted. On the i.MX8 the query will return `EGL_TRUE` indicating that `EGL_WAYLAND_Y_INVERTED_WL` is supported. In this case `y_inverted` will be double inverted during rendering.
I have implemented the query like it is defined in the spec and inverted the final value of `y_inverted` to align it with the current behaviour of the renderer.
> handle egl query with EGL_WAYLAND_Y_INVERTED_WL returning EGL_FALSE

- anvil/src/drawing.rs
- anvil/src/input_handler.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- examples/raw_drm.rs
- src/backend/allocator/dmabuf.rs
- src/backend/allocator/gbm.rs
- src/backend/drm/render.rs
- src/backend/drm/surface/mod.rs
- src/backend/egl/native.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- src/backend/winit.rs
- src/utils/mod.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/roles.rs
- src/wayland/compositor/tree.rs
- src/wayland/data_device/data_source.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/explicit_synchronization/mod.rs
- src/xwayland/xserver.rs
Built on top of #289, so to be merged after it.
> Several clippy fixes and fmt

- anvil/src/shell.rs
When Wayland client crashes during a resize, the whole compositor goes down with it. It was quite unexpected behavior when I first witnessed it. 
The fix is not ideal, but it's the best I could come up with, with my current knowledge of Anvil.
> Fix Anvil panic when resizing dead window

- src/wayland/seat/pointer.rs
> do not remove the surface focus during ungrap

- src/backend/session/direct.rs
This PR adds an environment variable to the direct session backend that allows the tty path to be overriden.
closes #302
> allow the direct session tty to be overriden by using a environment variable

- anvil/src/window_map.rs
> [Anvil] XDG activate support

- src/backend/egl/native.rs
- src/wayland/dmabuf/mod.rs
This PR replaces a few hard coded types with their platform specific equivalents.
fixes #312
> (cross-)compilation for armv7

- src/wayland/seat/pointer.rs
> Disable pointer grab with dead starting surface

- anvil/src/drawing.rs
- anvil/src/shell.rs
- anvil/src/window_map.rs
- anvil/src/winit.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shell/xdg/xdg_handlers.rs
This is not a full-featured support of xdg-popups, but it displays them at a not too unreasonable location.
> Rudimentary xdg_popup support

- anvil/src/shell.rs
use the current xdg_toplevel state to check if we are resizing. The configure message
is the result from telling the client that resizing
has stopped and therefore not include the resizing
state. The current state is safe to use because
AckConfigure will move the state to last_acked
and the current state will be set on the next surface commit.
fixes #321
> Fix resize state is never finished

- anvil/src/drawing.rs
- src/wayland/shell/xdg/mod.rs
This PR fixes a bug in the popup default geometry calculation and corrects the relative placement to the parent geometry.
> Fix popup default geometry

- src/backend/allocator/swapchain.rs
- src/backend/drm/device/mod.rs
- src/backend/drm/error.rs
- src/backend/drm/mod.rs
- src/backend/drm/surface/gbm.rs
- src/backend/drm/surface/mod.rs
- src/backend/egl/context.rs
- src/backend/egl/display.rs
- src/backend/egl/error.rs
- src/backend/egl/ffi.rs
- src/backend/egl/mod.rs
- src/backend/egl/native.rs
- src/backend/egl/surface.rs
- src/backend/renderer/gles2/mod.rs
Probably contains a few spelling mistakes, but I think I caught everything that was out-dated at least.
I will give this another go tomorrow. :)
> First pass at backend docs for #228

- src/backend/allocator/swapchain.rs
- src/backend/drm/mod.rs
- src/backend/egl/context.rs
Forgot to save all files, so these did not make it into #336 although I definitely intended them to...
> docs: some backend clarifications

- CHANGELOG.md
- src/backend/egl/display.rs
> backend.egl: Early return on dead buffers 

- anvil/src/drawing.rs
- anvil/src/shell.rs
- anvil/src/udev.rs
- src/backend/drm/device/atomic.rs
- src/backend/drm/surface/atomic.rs
- src/backend/libinput/tablet.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- src/wayland/compositor/handlers.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/explicit_synchronization/mod.rs
- src/wayland/output/mod.rs
- src/wayland/output/xdg.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/tablet_manager/tablet.rs
- src/wayland/tablet_manager/tablet_seat.rs
- src/wayland/tablet_manager/tablet_tool.rs
> Fix Clippy

- src/utils/geometry.rs
This allows Size, Point and Rectangle to be made with any numeric type
> Implement Coordinate for all numerical types

- Cargo.toml
> Make libloading optional

- src/backend/drm/surface/gbm.rs
Hopefully fixes #408 
@vurpo Can you please test this branch on your system?
> gbm: use Xrgb8888, if alpha variant is not available

- src/backend/x11/buffer.rs
- src/backend/x11/extension.rs
This will be needed in the future for #405.
> x11: add option to make extensions optional

- CHANGELOG.md
- anvil/src/x11.rs
- src/backend/x11/error.rs
- src/backend/x11/mod.rs
Builds upon #419 and #420 to bring buffer age support to the x11 backend as well.
> x11: use swapchain and expose age

- src/backend/x11/mod.rs
This should prevent compositors from deadlocking when creating a window while x11 is dispatching events.
One case where a deadlock occurs is when creating a new window when `Super + O` is pressed and creating said window when the `X11Event::Input` is received.
---
Days since i5 forgot to drop a MutexGuard: 0
> x11: Do not hold lock when dispatching events

- src/backend/x11/mod.rs
Dumb mistake I made. Per the docs of X11Source:
> The returned instance will use `SendRequest` to cause a `ClientMessageEvent` to be sent to
> the given window with the given type. The expectation is that this is a window that was
> created by us. Thus, the event reading thread will wake up and check an internal exit flag,
> then exit.
@Drakulix you probably want to test this on cosmic before merging.
> x11: internal window to send close backend event to

- CHANGELOG.md
- src/backend/x11/buffer.rs
- src/backend/x11/error.rs
- src/backend/x11/mod.rs
- src/backend/x11/surface.rs
The first commit does a little bit of internal organization.
Resolves #432
> x11: emit errors when presentation fails

- src/backend/mod.rs
This makes using anyhow with Smithay easier.
> backend: Make SwapBuffersError Send+Sync

- .github/workflows/ci.yml
- Cargo.toml
This removes a number of duplicated dependencies in the process.
> update winit dependency

- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/tree.rs
- src/wayland/shell/mod.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/wlr_layer/types.rs
- src/wayland/shell/xdg/mod.rs
- Implements wlr layer shell
- Adds &mut DisplayHandle to commit_hooks args
- Depends on #450
> 0.30/wlr layer shell

- src/backend/allocator/gbm.rs
`gbm_bo_get_fd` will create a new file descriptor on each call that needs to be closed manually.
without that fix a file descriptor will be leaked on each call to `export`
> fix dma buffer fd leak

- src/backend/drm/node/mod.rs
Let's clean up the internals of DrmNode a bit.
> drm: Replace inner Option on DrmNode and use mem::forget

- anvil/src/input_handler.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- src/backend/drm/surface/mod.rs
- src/backend/egl/mod.rs
This patch was written while implementing the udev backend for my
compositor to make things a little easier to read and understand. I
think the improvements would also help others to grasp grasp the code a
bit faster.
I've tried to keep all the changes minimal and objective, so hopefully
there shouldn't be any major style changes but just improvements. No
functionality has changed.
> Refactor anvil udev code

- Cargo.toml
- src/lib.rs
- includes feature hints in docs
> include feature hints in docs

- examples/compositor.rs
- examples/minimal.rs
- examples/seat.rs
- src/wayland/compositor/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shm/mod.rs
This should make using a delegate type much easier.
> 0.30: introduce delegate_ macros

- src/reexports.rs
- src/wayland/mod.rs
- src/wayland/shell/mod.rs
- src/wayland/shell/xdg/mod.rs
A couple things that wouldn't all make sense in individual pull requests.
> 0.30 small assorted changes

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- Cargo.toml
- src/backend/renderer/mod.rs
Let's try to get 0.30 (partially) green.
> ci: disable anvil for now, fix doc publishing

- src/backend/drm/surface/atomic.rs
> Fix plane rotation on nvidia

- src/backend/renderer/utils.rs
The surface offset is used to move the provided damage (which is relative to the passed location) to the relative position of the surface in the tree in order to calculate the surface local damage intersection.
If we do not agggregate the surface offset the relative damage location will be wrong for subsurface trees with a depth greater than 1.
This results in drawing surfaces outside of the damage with a wrong damage rects.
For example foot uses a subsurfaces for the decorations and sub-subsurfaces for the buttons in the decorations (minimize, maximize, close)
> aggregate the surface offset on render

- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/multigpu/mod.rs
Fixes a bunch of edge-cases / problems with the multigpu renderer in more complex scenarios than what anvil does.
> Multigpu shinanagans

- src/desktop/layer.rs
Adjust the size for top and left anchored layer surfaces as well.
> desktop/layer: Fix exclusive zone calculations

- src/wayland/seat/keyboard.rs
If a surface already has focus, new kbd instances of the same client
should immediately receive an enter event after creation.
> seat: Send enter events to new keyboard instances

- src/backend/renderer/multigpu/mod.rs
Previously it was possible to get an empty set of mappings, which would crash a full upload, which expected `mappings[0]` to be valid. This is fixed by this commit.
Additionally some clients making use of detailed damage constraints and subsurfaces (like firefox) show some erratic rendering with the new multigpu code. ~~Some of these changes are trying to fix this, but will need further investigation (issue persists).~~ These seem now to be fixed as well.
> multigpu: More defensive damage calculations

- Cargo.toml
- src/backend/winit/mod.rs
WlEglSurface changes mean this is here
> 0.30: update to alpha9

- src/wayland/compositor/tree.rs
Cleans up WlBuffers from `SurfaceAttributes` and `SurfaceState` on destruction.
One might think it would be cleaner to not add a dependency on the renderer-module inside wayland/compositor and I agree with that, but.. reliably dropping `SurfaceState` this way is very tricky.
smithay and anvil hold on to `WlSurface`s in many places. I was not able to figure out, what is holding `SurfaceState` back from dropping, but then again downstream should not need to worry about that as well (assuming they don't leak the surface, dropping it later *should* be fine).
But because this might break very pedantic clients (looking at your mako), that expect a buffer to be released immediately once not in use by any surface **and** `SurfaceState` is an implementation detail of smithay, we should be cleaning …
> wayland: cleanup WlBuffers on surface destruction

- anvil/src/input_handler.rs
It seems only toplevels should receive an implicit keyboard focus.
This fixes an issue in firefox-wayland where the menu would just close on selecting an entry.
> anvil: change implicit keyboard focus for toplevels only

- src/utils/geometry.rs
~This PR changes `Rectangle::contains` to include the edges of the rectangle in the check.
Additionally it updates the docs on `Rectangle::contains_rect` to reflect the changes made to  `Rectangle::contains`~
Two rectangles of equal location and size should contain each other.
This PR decouples the `Rectangle::contains_rect` function from `Rectangle::contains` and directly implements the rectangle
check.
> rectangles of equal location and size should contain each other

- CHANGELOG.md
- src/backend/egl/surface.rs
This PR adds a get_size method to EGLSurface
> feat: add get_size method to EGLSurface

- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/egl.rs
- src/backend/renderer/multigpu/mod.rs
Actually felt waaay to easy, but I am not going to complain.
> 0.30: Port multigpu renderer

- src/wayland/compositor/tree.rs
> wayland.compositor: Allow same role reassign

- Cargo.toml
- src/backend/egl/display.rs
> reenable bind_wl_display

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- anvil/src/drawing.rs
- anvil/src/input_handler.rs
- anvil/src/shell.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- anvil/src/xwayland/mod.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/multigpu/egl.rs
- src/desktop/space/mod.rs
- src/wayland/compositor/mod.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/output/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/decoration.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shm/mod.rs
- src/wayland/xdg_activation/mod.rs
Note: This does not touch actual documentation, this just tries to get CI green again
> 0.30: fix a bunch of tests

- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/utils.rs
- src/desktop/utils.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/tree.rs
Ver 5: https://github.com/wayland-project/wayland/commit/fceabb7e9e167e1100c244bb4f460c8a346a5478
Offset in `wl_surface::Attach` got replaced by `wl_surface::Offset`
> Update WlCompositor to version 5

- .github/workflows/ci.yml
- Cargo.toml
- LICENSE.txt
- anvil/Cargo.toml
- wlcs_anvil/Cargo.toml
... and while at it, update some names.
> Update to wayland-rs 0.30.0-beta.5

- src/backend/renderer/utils.rs
So it seems like I misinterpreted the spec on the surface damage in combination with viewporter.
This PR tries to correct that by scaling the surface damage to logical src before converting it to buffer space.
> renderer: respect viewport in surface damage

- src/backend/drm/surface/atomic.rs
`use_plane` does not work because the created test buffer for the plane implicitely drops the test buffer of the primary plane which results in an `InvalidArgument` error during the commit.
This PR moves the test buffer out of the mutex into a `TestBuffer` struct that will clean up the test buffer on `Drop`.
Additionally it fixes a potential memory leak in `create_test_buffer` where the `DumbBuffer` would not be cleaned up
if `add_framebuffer` fails.
> drm: fix test buffer drop for use_plane

- anvil/src/input_handler.rs
Fixes problem caused by #666 :imp:
> anvil: Fix crash on scroll

- anvil/src/udev.rs
Fixes `Double bind_wl_display, smithay does not support this, please report` when running anvil with kms backend
> anvil: do not double bind wl_display

- src/wayland/shell/xdg/handlers/surface/toplevel.rs
Issue encountered by @chrisduerr, thx for providing an example to replicate the issue.
> xdg/decoration: Cleanup reference cycle

- src/backend/renderer/element/mod.rs
> renderer: allow custom trait bounds in render_element!

- src/backend/renderer/element/mod.rs
@Drakulix I forgot the additional bounds
> renderer: allow lifetimes in additonal bounds

- anvil/src/shell.rs
- src/desktop/popup/grab.rs
- src/desktop/popup/manager.rs
- src/desktop/popup/mod.rs
- src/input/keyboard/mod.rs
- src/input/mod.rs
- src/input/pointer/mod.rs
- src/wayland/input_method/input_method_handle.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- 747c49fd62cf89ad9db335ad8243621c7a5a3b9f Provides proper Debug implementations for all new types in the input-module
- 53a211ab48b6927b48b8b7370bed02e679df6fc7 Fixes PopupGrabs. @cmeissl Can you check, that this commit looks sensible?
> Fixes for input abstractions

- src/backend/renderer/element/texture.rs
I broke the tests during refactoring the texture render element
> dev: correct test imports

- src/backend/renderer/damage.rs
@Drakulix I messed up the old damage in the refactoring, should be fixed with this PR
> renderer: only accumulate new damage

- src/backend/egl/ffi.rs
https://registry.khronos.org/EGL/extensions/KHR/EGL_KHR_debug.txt
As defined by the spec, `message` can be `NULL`, so this needs to handle that possibility.
The first argument is not "severity", it is an error code. The severity is instead the third argument, `messageType`.
Since message can be null, converting the error code to a string can be necessary to actually convey useful information.
> Fix `egl_debug_log`

- src/backend/egl/display.rs
> egl: Don't error check eglQueryDmaBufModifiersEXT

- src/backend/renderer/damage.rs
we can skip elements that are completely hidden on our output, not only if they are completely hidden.
without that change the dtr would only skip a element if its complete geometry was hidden, but we
are only interessted in geometry that intersects with the output.
> renderer: dtr skip elements hidden on output

- src/backend/renderer/mod.rs
- src/wayland/shm/mod.rs
- src/wayland/shm/pool.rs
Draft PR, because I still need to test the new functionality in a compositor, but ready for review and anvil still runs fine!
> shm: writeback support

- src/backend/drm/surface/gbm.rs
`Swapchain::submitted` increases the buffer age, which is obviously important for damage correct rendering.
When utilizing the swapchain for triple buffering and it's internal `queued_fb` the damage value of the buffer would not increase correctly, as the prepared frame was not yet displayed.
Instead we should already increase the buffer age, once a buffer is pending to be displayed.
> gbm: Increase age on queue_buffer

- anvil/src/drawing.rs
- src/backend/renderer/damage.rs
- src/backend/renderer/element/memory.rs
- src/backend/renderer/element/texture.rs
> element: Allow alpha to be specified

- anvil/src/udev.rs
> anvil/udev: Don't delay frames for secondary gpus

- CONTRIBUTING.md
> fix-3-typos

- anvil/Cargo.toml
- anvil/src/state.rs
- anvil/src/x11.rs
this enables renderdoc on the x11 backend if the debug feature is enabled
> anvil: integrate renderdoc in debug feature

- Cargo.toml
- anvil/Cargo.toml
- src/xwayland/xwm/mod.rs
The `ConfigWindow` type seems a bit awkward to work with here (https://github.com/psychon/x11rb/issues/791). But that isn't really an issue.
> Bump `x11rb` to 0.11

- src/wayland/seat/touch.rs
Currently the handles for a specific touch slot are always cleared on touch down, meaning that touch events are correctly propagated as long as `down` is called before any other touch events. However when motion is called after `up` without a previous `down`, then the motion is still reported to the previous client.
While this can be easily avoided in the compositor by always calling `down` first and avoiding `motion`/`up`/`cancel` without previous `down` call, it should provide a more intuitive behavior this way.
> Fix touch event focus

- src/xwayland/xwm/mod.rs
- src/xwayland/xwm/surface.rs
Of course there are always bugs, when a big new feature lands.
> xwm: Fixes

- Cargo.toml
- examples/buffer_test.rs
- src/backend/allocator/dmabuf.rs
- src/backend/allocator/dumb.rs
Something I wanted to build for a long time to debug multi-gpu setups.
> example: Buffer Tester

- src/backend/renderer/gles2/mod.rs
gl_debug_log only receives a reference, so move the cleanup of the gl debug span to the drop impl of the renderer
> gles: don't drop the log span in gl_debug_log

- src/desktop/wayland/layer.rs
This seems to improve arrangement of layer surfaces with margins. I tested it in anvil with a bunch of anchored layer surfaces with exclusive zones on each edge.
> fix(layer): arrange layer surfaces accounting for margins

- anvil/src/udev.rs
- src/output.rs
Weston, wlroots and cosmic-comp all use the same logic for this (minus some stylistic differences), so I think it's safe to just provide default behavior.
> Add from DRM mode to smithay output mode conversion

- src/wayland/shell/xdg/mod.rs
Previously this only sent configure if it had changed, but this doesn't work when a client doesn't set a preferred mode and relies on the server to define the mode.
This adds an additional variable for whether the decoration configure event has been sent, since I don't see any indication that `get_toplevel_decoration` couldn't be called some time after the first `configure`.
The protocol spec also states it is a protocol error to create a `xdg_toplevel_decoration` with a buffer attached, or to attach a buffer before the `xdg_toplevel_decoration.configure` is received. It may be good to enforce that, though perhaps first check the behavior of clients and other compositors. The fact `winit` windows ever showed anything before this change suggests it isn't following this restriction...
Fixes …
> wayland.xdg-decor: Send `configure` if it has not been sent yet

- src/xwayland/xwm/surface.rs
As described in ICCCM, "Locally Active Input" windows expect to receive input focus from the WM, but may then want to set the focus to another of its windows. So it is still necessary to call `set_input_focus` for these applications to work correctly.
Additionally "Globally Active Input" windows expect to receive `WM_TAKE_FOCUS` messages. So that needs to be sent to them.
I'm not sure if there are more subtleties in exactly when to set input focus and when to send `WM_TAKE_FOCUS`, but this should be more correct, at least.
Fixes issue with `emacs-lucid` described in https://github.com/pop-os/cosmic-comp/issues/92.
> xwm: Fix handling of `WM_TAKE_FOCUS` windows

- src/wayland/virtual_keyboard/virtual_keyboard_handle.rs
Since the keymap sent for the virtual keyboard protocol is supplied by a client, it should not be trusted. Unwrapping on it causes the compositor to crash when a malicious or buggy client tries to send the `Keymap` request.
To ensure even misbehaving clients don't cause any issues, requests with invalid keymaps are simply ignored.
This has been sparked by an issue encountered with `wvkbd`, which sends a keymap with 54 `\0` bytes at the end. While it would be possible for Smithay to clean this up, I'm not sure if it is appropriate for the compositor to work around what is arguably a client issue.
An issue has been filed with `wvkbd` here:
https://github.com/jjsullivan5196/wvkbd/issues/35
Closes #942.
> Fix virtual keyboard crash with invalid keymap

- src/backend/renderer/gles2/mod.rs
This fix is needed for https://github.com/Smithay/smithay/issues/946
> Handle creation shader function

- src/backend/allocator/vulkan/mod.rs
- src/backend/vulkan/mod.rs
- src/wayland/shm/pool.rs
Adding docs and unsafe wrapping stuff.
Needed for https://github.com/Smithay/smithay/issues/946.
> Fix 756 src/wayland/shm/pool.rs

- anvil/src/shell/mod.rs
- src/wayland/shell/xdg/handlers/surface/toplevel.rs
- src/wayland/shell/xdg/mod.rs
this adds support for configure_bounds which was introduced in v4
fixes #544
> wayland: support xdg_wmbase v4

- anvil/src/input_handler.rs
- anvil/src/shell/xdg.rs
- anvil/src/state.rs
- src/backend/renderer/utils/wayland.rs
- src/wayland/compositor/handlers.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/handlers/surface/popup.rs
- src/wayland/shell/xdg/handlers/surface/toplevel.rs
> Fix role reuse

- src/backend/drm/mod.rs
> doc: restructuring the drm

- anvil/src/shell/mod.rs
> rearrange layer shell on commit

- src/backend/renderer/utils/wayland.rs
- src/wayland/viewporter/mod.rs
viewporter created a ref-cycle which prevented the surface data to be cleaned up properly which resulted in "leaking" textures
> Fix texture leak

- src/backend/drm/compositor/mod.rs
- src/backend/drm/surface/gbm.rs
if a frame resulted in no damage do not try to submit the frame through drm. this would result in an error on legacy and atomic does not guarantee that a vblank will be triggered.
> drm: do not submit empty frames

- src/input/pointer/mod.rs
- src/wayland/seat/pointer.rs
Fixes https://github.com/Smithay/smithay/issues/742
> seat/ptr: Check serial on set_cursor.

- anvil/src/input_handler.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/wayland/input_method/mod.rs
- wlcs_anvil/src/main_loop.rs
This fixes a regression introduced in 881dfbf, which caused input method to panic on the `get_input_method` request.
> Fix input_method panic

- src/wayland/viewporter/mod.rs
we should only add the pre commit hook once and we have to update the actual viewport protocol object
> wayland: fix viewporter surface re-use

- CHANGELOG.md
- anvil/src/input_handler.rs
- anvil/src/shell/grabs.rs
- anvil/src/shell/xdg.rs
- anvil/src/state.rs
- smallvil/src/grabs/resize_grab.rs
- smallvil/src/handlers/xdg_shell.rs
- smallvil/src/input.rs
- src/desktop/wayland/layer.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/handlers/surface/toplevel.rs
- src/wayland/shell/xdg/mod.rs
this adds support for wm capabilities  which were introduced in v5
> wayland: support xdg_wmbase v5

- src/xwayland/xwm/mod.rs
1. Since we're reparenting, we need to reorder the parent windows, not the client window. Reordering occurs relative to siblings and the client windows have no siblings under their respective parent windows. The exception is override_redirect windows, which don't get reparented.
2. When adding windows to client_list and client_list_stacking, ignore MapNotifys for the parent windows. If we don't, we end up with duplicates in the lists, one entry from the client window and one from the parent window.
3. Dedupe the code of update_stacking_order_downwards and update_stacking_order_upwards.
4. Attempt to make the docstrings of update_stacking_order_downwards and update_stacking_order_upwards cleare. In particular, try to be consistent with "abpve" and "below" to match X11's terminology. …
> xwayland: several fixes for window stacking

- src/wayland/seat/touch.rs
The offset passed along with the location to calculate the relative position of the touch event was an idiosyncrasy introduced due to the way I structured the data in my compositor in the past.
At this point even my compositor doesn't use this structure anymore and just stores a relative position, so calculating the offset back from that is a waste of effort and prone to errors.
So to simplify the API, the touch down event now just takes the surface-local position, identical to the way the protocol itself behaves. Documentation has been added to clarify this.
> Remove offset from seat's touch API

- src/wayland/input_method/input_method_handle.rs
And post a protocol error if the surface already has a role. Unfortunately while the protocol says to raise a protocol error in this case, it doesn't actually define an error enum...
> input-method: Call `compositor::give_role` on popup

- src/backend/renderer/gles/mod.rs
- src/backend/renderer/glow.rs
- src/backend/renderer/multigpu/egl.rs
- src/backend/renderer/multigpu/gbm.rs
> Filter gles capabilities

- src/backend/allocator/dmabuf.rs
- src/backend/allocator/dumb.rs
> allocator: Update doc links

- src/wayland/data_device/dnd_grab.rs
Fixes: https://github.com/Smithay/smithay/issues/1072
> data_device: check version for wl_data_source.dnd_drop_performed

- examples/buffer_test.rs
Without this, I see `gbm_create_device` cause a segfault within the Intel driver.
> buffer-test: Open device with write permission

- src/wayland/shell/xdg/mod.rs
- src/wayland/tablet_manager/tablet_seat.rs
Fixes https://github.com/Smithay/smithay/issues/1036.
> Minor fixes

- src/backend/renderer/utils/wayland.rs
It was ignored until now, breaking offset DnD surfaces for example.
I'm not sure if it interacts correctly with viewporter and input region; the protocol is not entirely clear on this. But I'm also not sure after reading the protocol that the existing code handles it correctly. So far nothing seems to have broken.
A good test for this fix is GTK tests/testdndresize; alternatively, dragging images and videos out of [Loupe](https://flathub.org/apps/org.gnome.Loupe) or [Identity](https://flathub.org/apps/org.gnome.gitlab.YaLTeR.Identity).
> Take Wayland buffer offset into account

- src/xwayland/xwm/mod.rs
> xwm: only set SharedSurfaceState.mapped_onto once

- src/wayland/shm/pool.rs
Visual demonstration of Pool drops stalling the main thread:
Real stalled vblank events before this PR:
Real stalled vblank events after this PR:
(yes, there's only one, and it's unrelated)
> shm/pool: Introduce a thread for dropping

- src/wayland/seat/pointer.rs
When accessing the `Seat` state from the `SeatHandler::cursor_image` state the lock was being held on the inner data of the seat, meaning that the seat was useless in such a case.
Refactor the handler leading to calling the said trait function to not hold the lock.
--
tested with niri
> seat/pointer: fix `SeatHandler::cursor_image` deadlock

- src/input/pointer/mod.rs
> Fix pointer gestures copypasted comment

- README.md
- anvil/README.md
[rendered](https://github.com/Smithay/smithay/blob/217d6c87b530a43b8fcf8859eb0cfa2541c8ae93/README.md)
> Update README & Add compositors list

- src/backend/allocator/dmabuf.rs
Although it should be safe as used, `BorrowedFd<'static>` is an ugly solution. This avoids `unsafe`.
Alternately, the plane or fd could be separately ref-counted. But there's not much obvious benefit to that.
> DmabufSource: Define safe helper instead of using `borrow_raw`

- src/wayland/mod.rs
- src/wayland/session_lock/lock.rs
- src/wayland/session_lock/mod.rs
- src/wayland/session_lock/surface.rs
Picking up from #1019 with minimal changes, all in subsequent commits. cc @chrisduerr 
No anvil impl, but I've got a niri impl: https://github.com/YaLTeR/niri/compare/main...session-lock
Preliminary testing with swaylock and https://github.com/Smithay/client-toolkit/pull/419 seems to work, gonna give this more testing over the next few days.
> Implement ext-session-lock

- src/wayland/shell/xdg/mod.rs
little typo thats annoyed me for a bit
> WmCapabilitieSet -> WmCapabilitySet

- src/wayland/shell/xdg/handlers/wm_base.rs
- src/wayland/shell/xdg/mod.rs
this is needed in my use case to properly send failure notifications if the client disconnects while a ping is active
> add XdgShellHandler::client_destroyed

- src/input/keyboard/mod.rs
Fixes soundness issue introduced in #1218.
> keyboard: accept String instead of Keymap when setting keymap

- src/backend/egl/display.rs
I don't know if creating a whole new `wrap_egl_call_*` function would be worth it just to fix this, let me know what you think!
> Fix a logic bug in the egl backend

- src/input/keyboard/mod.rs
change_keymap() needs a lock on self.arc.internal.
> Fix deadlocks when updating xkb state

- src/wayland/seat/pointer.rs
I guess I didn't end up testing this properly. This seems to work now.
> Fix accumulation for `axis_discrete` events

- src/wayland/seat/pointer.rs
Must've been a copy-paste error. Fixes vertical wheel scrolling.
cc @ids1024
> Fix wrong pointer axis

- anvil/src/state.rs
The global wasn't being created.
> anvil: Fix tablet support

- src/backend/drm/compositor/mod.rs
this also fixes the missing rendering reason for the primary plane when no overlay planes are available
> drm: reduce result nesting

- src/backend/drm/compositor/mod.rs
This marks the primary plane test as failed in case submit or page flip fails. The next call(s) to `render_frame`
will then skip the element on the primary plane until some properties change (src, dst, format, ...).
Just to note, this should not be necessary as an atomic commit test should already catch that.
But unfortunately there are broken drivers where the test succeeds, but the actual commit/flip fails :/
> drm: disable element direct scan-out on submit failure

- src/backend/allocator/gbm.rs
in case we miss support fo create_buffer_object_with_modifiers2 we can only fall back to create_buffer_object_with_modifiers if we do not have gbm bo usage flags.
if we got flags we can fall back to create_buffer_object for invalid and linear modifiers, but not for others.
fixes cursor usage flags which is required for the bo on the cursor plane.
fixes number 2 from here https://github.com/Smithay/smithay/issues/1275#issuecomment-1890473451
(I guess this, together with [!1276](https://github.com/Smithay/smithay/pull/1276) should also fix #1262)
> drm: do not silently drop gbm bo usage flags

- .github/workflows/ci.yml
- src/lib.rs
~depends on #1283~ merged
fixes #1282
> logging intro

- src/wayland/shell/kde/decoration.rs
- src/wayland/shell/kde/handlers.rs
- src/wayland/shell/xdg/decoration.rs
I want my CSD on my SDL2 windows, but it's borked on all current releases: https://github.com/libsdl-org/SDL/issues/8173
Thus, I shall hide the globals.
> Filter closures for decorations

- src/desktop/space/wayland/mod.rs
- src/desktop/wayland/layer.rs
- src/output.rs
- src/wayland/output/handlers.rs
- src/wayland/output/mod.rs
> Track entered surfaces in Output

- src/backend/drm/compositor/mod.rs
this adds a fast-path by copying shm buffers directly to the cursor plane bo whenever possible
some quick profile with tracy:
rendering with gl:
copy directly to bo:
> drm: copy element to cursor plane when possible

- src/input/keyboard/mod.rs
- src/wayland/virtual_keyboard/virtual_keyboard_handle.rs
Pass the actually required types we need locks for instead of ensuring that callers release the locks everywhere.
Fixes: 629975f714 (Fix deadlocks when updating xkb state)
Fixes: 5a0b08c804 (Add separate keymap for virtual keyboard)
Links: https://github.com/YaLTeR/niri/issues/103
--
cc @chrisduerr @YaLTeR
> Fix deadlock in send_keymap when called form input

- src/backend/input/mod.rs
- src/backend/libinput/mod.rs
- src/backend/winit/input.rs
- src/backend/x11/input.rs
This just forwards the linput switch toggle events, might be used for automatic output disable/enable.
> input: expose switch toggle events

- anvil/src/udev.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/device/mod.rs
- src/backend/drm/error.rs
- src/backend/drm/surface/atomic.rs
> fix various drm issues

- Cargo.toml
- anvil/Cargo.toml
- anvil/src/drawing.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- src/backend/drm/compositor/mod.rs
- src/backend/renderer/element/memory.rs
- src/backend/renderer/element/mod.rs
Rebased and slightly modified version of #1239 
Main difference from #1239 is that pixman is still optional (enabled by default).
> pixman rendered cursor plane

- src/wayland/input_method/input_method_handle.rs
This can happen when IME releases and takes back the grab on the fly, thus the modifier state may go out of sync with the keyboard modifiers.
> Send modifiers when creating IME grab

- src/wayland/shell/xdg/handlers/surface/toplevel.rs
- src/wayland/shell/xdg/mod.rs
Otherwise there's no good way to track this.
> xdg-shell: Add callbacks for app-id and title changes

- anvil/src/focus.rs
- anvil/src/input_handler.rs
- anvil/src/shell/element.rs
- anvil/src/shell/grabs.rs
- anvil/src/shell/mod.rs
- anvil/src/shell/ssd.rs
- anvil/src/shell/x11.rs
- anvil/src/shell/xdg.rs
- smallvil/src/grabs/resize_grab.rs
- smallvil/src/handlers/compositor.rs
- smallvil/src/handlers/xdg_shell.rs
- smallvil/src/input.rs
- src/desktop/space/wayland/window.rs
- src/desktop/wayland/window.rs
As mentioned in the document, `desktop::Window` will eventually have XWayland support. The related issue is https://github.com/Smithay/smithay/issues/1202.
> Prepare desktop::Window for XWayland

- anvil/src/shell/xdg.rs
- src/desktop/wayland/window.rs
This code got removed at some point for some reason, it's basically handling of adjusting window position during resize.
Even with this applied, both resize and move grabs still act really junky in comparison to smallvil, but this at least makes it work somewhat how people would expect. Will try to debug and fix this in future PRs.
> [anvil] Simple resize handling for anvil

- src/wayland/compositor/handlers.rs
> Add a check for buffer scale validity

- src/xwayland/xwm/mod.rs
Fixes two internal issues:
1. There's a `self.source_data = Vec::new()` that clears the internal selection buffer that probably isn't supposed to be there, and
2. Fixing the above revealed that sometimes the final 0-byte data chunk to complete the transfer wasn't always getting sent. I'm still not sure of the code path that causes this to happen.
This was the simplest way I could fix the problem. If there's a better way let me know!
Fixes #1380
> Fix outgoing xwm incremental selection

- src/backend/renderer/utils/wayland.rs
Lets one implement custom rendering logic.
> Expose scale and transform from RendererSurfaceState

- src/wayland/selection/data_device/dnd_grab.rs
This seems to match the behavior of sway, and fixes https://github.com/pop-os/cosmic-comp/issues/437.
If `!data.dropped`, `cancelled` has already been sent. If `data.finished`, `dnd_finished` has been sent. Otherwise, sending `cancelled` here seems correct.
> Send `wl_data_source::cancelled` on `wl_data_offer::destroy`

- src/wayland/shell/wlr_layer/handlers.rs
`WlrLayerSurfaceUserData` contains a `WlSurface`. `LayerSurfaceAttributes`, which is stored in the surfaces `data_map`, contains a `ZwlrLayerSurfaceV1`. This, somewhat subtly, is a reference cycle that causes a leak. So one of these references needs to be weak.
I noticed this issue with Valgrind, but this can also be reproduced by adding  drop impl to `LayerSurfaceAttributes` that panics. Before this change, running `simple_layer` in anvil and exiting it never drops the `LayerSurfaceAttributes`. With the change, the panic happens when a layer surface is closed.
> wlr_layer: Fix memory leak due to reference cycle

- src/wayland/shm/pool.rs
`sigaction` can contain private fields on some targets, so we can't use the `..mem::zeroed()` syntax.
fixes #1412
> wayland.shm: Zero-Initialize private fields of `libc::sigaction`

- src/input/touch/mod.rs
sending wl_touch.frame for a wl_touch.up is valid and we should not prevent it. wl_touch.cancel explicitly states that no frame should be sent.
cc @chrisduerr
> wayland: allow to send touch frame for touch up

- src/wayland/compositor/tree.rs
if we are not sync we have to commit our complete surface tree.
fixes #883
> wayland: commit sync child surface tree

- src/backend/drm/compositor/mod.rs
Atomic commits fail if this is set on the Nvidia driver, it seems: https://github.com/NVIDIA/open-gpu-kernel-modules/issues/622
Kwin also has a check for this https://invent.kde.org/plasma/kwin/-/merge_requests/4770.
This fixes Anvil and cosmic-comp on the Nvidia 555 beta driver. (I'm not sure why it only started to be a problem; `EGL_ANDROID_native_fence_sync` is present in the 550 driver, etc.)
> compositor: Disable `IN_FENCE_FD` on Nvidia

- src/wayland/alpha_modifier/dispatch.rs
- src/wayland/alpha_modifier/mod.rs
- src/wayland/mod.rs
~~blocked: needs new wayland-rs releasse~~
> Implement wp alpha modifier v1

- src/wayland/shell/xdg/dialog.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/mod.rs
~~blocked: needs new wayland-rs releasse~~
> Implement XDG Dialog protocol

- src/wayland/fractional_scale/mod.rs
Did you know about `map_or()`? It's my new favorite function for reducing line count
> Refactor fractional-scale to store state persistently

- Cargo.toml
- src/backend/egl/display.rs
- src/backend/egl/mod.rs
- src/wayland/compositor/mod.rs
Fixes some new warnings generated by the newest nightly version.
> Fix nightly warnings

- src/backend/drm/compositor/mod.rs
while it should be totally fine to only
update the planes that have actually changed
it seems some drivers might break by doing so.
after some trial and error it seems that it might
be enough to always include the primary plane
in the update to workaround this issues. But
to be safe for now and until this has resolved
we just include all used planes in the update.
might fix/workaround https://github.com/pop-os/cosmic-comp/issues/499
> drm: always submit the complete state

- src/backend/renderer/pixman/mod.rs
The actual mmap can change if the shm pool gets
resized. In this case we have to re-map our image
to prevent accessing a unmapped memory region.
> pixman: re-map resized shm pool images

- src/wayland/selection/data_device/dnd_grab.rs
> wayland: only send dnd_drop_performed for accepted offers

- src/backend/allocator/vulkan/mod.rs
Fixes `fatal runtime error: IO Safety violation: owned file descriptor already closed` error in debug build with Rust 1.80. And presumably other issues.
> allocator/vulkan: Don't create multiple `OwnedFd` from one `RawFd`

- src/backend/drm/gbm.rs
The legacy code path will succeed and then the nvidia driver will accept the framebuffer even though being unable to scan it out and never deliver another vblank event...
We probably shouldn't even try that code path for client-side buffers, so lets skip it.
> drm/gbm: Don't use the legacy code path for import client dmabufs

- src/desktop/wayland/layer.rs
Fixes offset cursor position in layer-shell popup menus.
> layer: Take popup geometry loc into account

- src/wayland/tablet_manager/tablet.rs
- src/wayland/tablet_manager/tablet_seat.rs
- src/wayland/tablet_manager/tablet_tool.rs
Yet another package of reference cycles:
```mermaid
flowchart TD
ZwpTabletSeatV2 --> TabletSeatUserData --> TabletSeatHandle --> TabletSeat --> ZwpTabletSeatV2
ZwpTabletV2 --> TabletUserData --> TabletHandle --> Tablet --> ZwpTabletV2
ZwpTabletToolV2 --> TabletToolUserData --> TabletToolHandle --> TabletTool --> ZwpTabletToolV2
```
> Fixup tablet reference cycles

- src/desktop/space/mod.rs
i don't know what else i could add there that makes sense. maybe FusedIterator.
> specify `ExactSizeIterator` for `Space::elements()`

- src/backend/drm/compositor/mod.rs
In theory I think this should work. But I seem to be seeing issues with this on the 560 beta driver.
The 560 driver adds `IN_FENCE_FD` support, fixing https://github.com/NVIDIA/open-gpu-kernel-modules/issues/622, so the check added in https://github.com/Smithay/smithay/pull/1437 to disable `IN_FENCE_FD` on Nvidia should no longer be needed, if the driver is new enough. Reading `/sys/module/nvidia_drm/version` seems like a reasonable way to check the driver version (although maybe on FreeBSD we'd need a different check.)
Testing on cosmic-comp with https://github.com/pop-os/nvidia-graphics-drivers/pull/210 (using either open or proprietary kernel modules).
* `needs_sync()` is now false, without causing corrupted rendering when an Intel GPU is used for rendering on an Nvidia output
* I'm …
> Enable `IN_FENCE_FD` on Nvidia 560 driver

- Cargo.toml
- src/backend/renderer/gles/version.rs
IMO this seems simple enough to not warrant a dependency
> Drop scan_fmt dependency

- src/input/keyboard/mod.rs
since https://github.com/Smithay/smithay/commit/3293482ca42258fe2b04145dc15e4b7490feaa58 `KeysymHandle::raw_latin_sym_or_raw_current_sym` causes a deadlock unconditionally due to a double mutex lock.
> stop deadlocking in `raw_latin_sym_or_raw_current_sym`

- src/wayland/drm_syncobj/mod.rs
It should be possible to destroy this, and then create a new instance for the same `wl_surface`. And it seems that does happen with Firefox on Nvidia.
I guess I meant to add some handling to `Destroy`, but didn't do so earlier. This removes the hooks, signals any pending release fence, and allows `get_surface` to be called again.
This should be consistent with how the protocol spec says destroy should behave. If a `wl_surface::commit` has already occurred, the sync points should still be used when presenting that commit.
> drm-syncobj: Fix handling of `wp_linux_drm_syncobj_surface_v1::destroy`

- src/wayland/shm/pool.rs
Since we use `OnceLock` for `OLD_SIGBUS_HANDLER`, the `SIGBUS_INIT` is redundant I think.
> shm: simplify sigbus init

- src/wayland/shell/xdg/mod.rs
fixes #1570
The `initial_configure_sent` should be reset only for surfaces that are already mapped, to prevent interference with the initial commit dance.
@YaLTeR Can you check if this fixes the problem in niri as well?
> Fix initial configure reset logic

- src/wayland/commit_timing/mod.rs
> wayland: remove verbose commit timing logging

- src/wayland/viewporter/mod.rs
> Fix viewporter data race

- src/backend/drm/device/atomic.rs
- src/backend/drm/error.rs
- src/backend/drm/surface/atomic.rs
> drm: error instead of panic on missing crtc/connector/plane mapping

- src/backend/drm/error.rs
@kenoss can you verify if that fixes the panic for you and makes the `DrmOutputManager` work as expected on the M2?
fixes #1661
> drm: detect EBUSY and expose it as a transient error

- src/wayland/compositor/handlers.rs
> handlers: add sanity check for neg width / height

- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/utils/mod.rs
- src/backend/renderer/utils/wayland.rs
> renderer: expose damage snapshot of surface

- Cargo.toml
- anvil/src/state.rs
- src/backend/renderer/utils/wayland.rs
- src/utils/geometry.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/output/handlers.rs
- src/wayland/output/mod.rs
- src/wayland/output/xdg.rs
- src/wayland/pointer_gestures.rs
- src/wayland/relative_pointer.rs
- src/wayland/seat/pointer.rs
- src/wayland/seat/touch.rs
- src/wayland/tablet_manager/tablet_tool.rs
- src/wayland/viewporter/mod.rs
- src/xwayland/xwm/mod.rs
- src/xwayland/xwm/surface.rs
I don't know, if we want to merge this, but this seems to match what Kwin does.
> compositor: Allow fractional client scales

- src/wayland/presentation/mod.rs
> wayland/presentation: do not discard non superseded feedback for subsurface tree

- src/backend/renderer/element/memory.rs
- src/backend/renderer/element/surface.rs
- src/backend/renderer/element/texture.rs
- src/backend/renderer/gles/mod.rs
- src/backend/renderer/glow.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/pixman/mod.rs
- src/backend/renderer/test.rs
- src/backend/renderer/utils/wayland.rs
Attempt to fix the issue discussed in #1704.
> renderer: Include texture type information in `ContextId`

- src/wayland/shell/xdg/mod.rs
This PR makes `PositionerState` resize the top and left edges when unconstraining popups in addition to the bottom and right edges that are already getting resized.
A user ran into an issue where a popup would overflow past the top of the screen (pinnacle-comp/pinnacle#305). This issue reproduces in Niri and cosmic-comp.
I believe the current positioner code assumes that a slide will always take place before a resize and thus only cuts off the left and bottom sides of the popup rectangle when resizing. In the issue above, gnome-builder creates the popup with `resize_y` but not `slide_y` constraint adjustments which leaves the top side constrained, so we need to resize the opposing edges as well.
> xdg: Resize opposing edges when unconstraining popups

- src/xwayland/xwm/surface.rs
Add getter for hints on X11Surface
> Expose x11 hints

- src/utils/sealed_file.rs
Fixes a build issue I encountered on OpenBSD.
> Fix rand API after recent update

- CHANGELOG.md
- Cargo.toml
[rendered](https://github.com/Smithay/smithay/blob/b2d28e39aeb7935f1dd8e485b236fb1376e097d1/CHANGELOG.md)
> Bump 0.7.0

- anvil/src/state.rs
- examples/minimal.rs
- smallvil/src/handlers/mod.rs
- src/wayland/selection/data_device/device.rs
- src/wayland/selection/data_device/mod.rs
- src/wayland/selection/data_device/source.rs
- src/wayland/selection/ext_data_control/device.rs
- src/wayland/selection/ext_data_control/mod.rs
- src/wayland/selection/ext_data_control/source.rs
- src/wayland/selection/primary_selection/mod.rs
- src/wayland/selection/primary_selection/source.rs
- src/wayland/selection/seat_data.rs
- src/wayland/selection/source.rs
- src/wayland/selection/wlr_data_control/device.rs
- src/wayland/selection/wlr_data_control/mod.rs
- src/wayland/selection/wlr_data_control/source.rs
> Revert "selection: instantly notify clients when source dies"

- src/backend/drm/exporter/gbm.rs
This changes the behavior of the node filter when not having any node specified on the dmabuf. Previously this would always cause direct scanout to fail, regardless of the specified `NodeFilter`. This patch changes it to always accept scanout with `NodeFilter::All`.
> Fix `NodeFilter::All` without render node attached

- src/backend/renderer/element/mod.rs
I have a case in cosmic-comp, where I want to cache data linked to an Id without keeping resources alive.
> element: Introduce WeakId

- src/backend/renderer/gles/mod.rs
- src/backend/renderer/multigpu/gbm.rs
- src/backend/renderer/multigpu/mod.rs
llvmpipe segfaults currently, when attempting to import a dmabuf it cannot handle: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6438
While it would be nice to fix this upstream, realistically old mesa versions will ship for quite some time. In general it doesn't make sense to do dma-copies with software renderers anyway.
We can figure out from EGL, if we have llvmpipe as a renderer, but we don't know the node it uses. (We could figure it out via `EGLDevice`, but that might not be the node, we set on the dmabuf, especially in the software renderer case where we most likely don't have a render-node and only a primary one, if it was created from a `GbmDevice` and not via enumerating `EGLDevice`s.)
So instead we assume downstream users that do cross-gpu imports on purpose via the …
> multigpu: Don't attempt cross-device imports on software renderers
