- Cargo.toml
This update removes the bindgen/clang dependency when building with `backend_libinput`.
> Update libinput bindings

- Cargo.toml
- build.rs
- examples/simple.rs
- src/backend/graphics/egl.rs
- src/backend/graphics/glium.rs
- src/backend/input.rs
- src/backend/libinput.rs
- src/backend/winit.rs
- src/keyboard/mod.rs
- src/lib.rs
- src/shm/mod.rs
- src/shm/pool.rs
So this is hopefully the last piece refactored in the egl stuff to get drm working.
Most graphical backends will probably yield more then one surface to draw, which all need to be bound to the same egl context, which is why this is necessary.
This actually makes the winit backend more difficult to implement, because the surfaces need to be deconstructed before the context is, which is reflected by lifetimes. However storing an owned var (context) + a reference to that (surface) in a struct is not representable normally in rust. I had to introduce another dependency here to work around this problem, which only changes internal stuff (nothing, that is exposed) and I do think this is actually the best solution to the problem, because:
- This gets the dependency between `EGLSurface` and …
> Decouple EGLSurface from EGLContext

- .gitignore
- .rustfmt.toml
- Cargo.toml
- examples/helpers/glium.rs
- examples/helpers/mod.rs
- examples/helpers/shell.rs
- examples/simple.rs
- src/backend/graphics/glium.rs
- src/backend/winit.rs
- src/compositor/global.rs
- src/compositor/handlers.rs
- src/compositor/mod.rs
- src/compositor/region.rs
- src/compositor/tree.rs
- src/lib.rs
- src/shm/mod.rs
There are still a some things to do before merging.
Two requests of `wl_surface` are missing:
I plan make the user provide a Handler to directly retrieve these, as they cannot be simply accumulated for double-buffering like the others.
Two requests of `wl_subsurface` are missing:
I'm not yet sure how to handle these, the current tree structure could handle ordering of the children of a surface, but we need to _also_ handle ordering the parent relative to each of its children.
EDIT: subsequent needs:
> First draft of the compositor/subcompositor global handler

- examples/helpers/mod.rs
- examples/helpers/shell.rs
- examples/simple.rs
- src/compositor/global.rs
- src/compositor/handlers.rs
- src/compositor/mod.rs
- src/compositor/roles.rs
- src/compositor/tree.rs
- src/lib.rs
This is a large rework of the machinery handling surface roles, making it much more convenient to use.
The general idea is that the user of smithay will use the `define_roles!()` macro to create an enum that represents all the roles of interest. The generated enum has several properties:
- It implements the trait `RoleType`, meaning to smithay that it is a type that manages roles, and a method of this trait can be used to query if a surface currently has a role or not (but now which role).
- For each role of interest, in implements the `Role<RoleTokenType>` trait, where `RoleTokenType` is a unit-like type, implementing the `RoleToken` trait, allowing it to define a `Data` associated type, defining the type holding the data associated with this role. The `Role<_>` trait provides some …
> compositor: rework roles

- examples/simple.rs
These little changes allow us to run weston-terminal in the smithay example, with it correctly updating its buffers.
> Update example to have weston-terminal not crashing

- Cargo.toml
- build.rs
- examples/drm.rs
- examples/helpers/glium.rs
- examples/winit.rs
- src/backend/drm/backend.rs
- src/backend/drm/error.rs
- src/backend/drm/mod.rs
- src/backend/graphics/egl.rs
- src/backend/graphics/glium.rs
- src/backend/graphics/mod.rs
- src/backend/input.rs
- src/backend/libinput.rs
- src/backend/mod.rs
- src/backend/winit.rs
- src/compositor/region.rs
- src/keyboard/mod.rs
- src/lib.rs
- src/shell/xdg_handlers.rs
Rough list of changes:
- new backend rendering via egl via gbm directly on a drm device
- refine EGLContext and EGLSurface dependencies through lifetimes and surface types (super safe now, no unsafe code for initializing is required anymore outside of egl.rs itself).
- add new example using the drm backend instead
- change GliumDrawer to be static for the drm example
- fixup the old winit backend and example to work with these changes
I am sorry this turned out to be one commit (ouch), but I reworked this for so many times and had to rebase this on your re-formatted code, so you might be able to imagine that mess.
This is ready for a first review. ~It is only missing a lot of documentation and more logging.~ It appears to work just fine on my machine and does not seem to have broken …
> Drm Backend

- examples/winit.rs
- src/wayland/seat/pointer.rs
My first PR here (and in Rust anywhere). I'm not sure the correct way to pass around the axis enum (input::Axis, wl_pointer::Axis, or something else). I went with wl_pointer::Axis. I tested with weston-eventdemo and weston-terminal and everything seems to work. Merge, edit or ignore as you wish.
> added scroll events to pointer and winit demo

- examples/udev.rs
- examples/winit.rs
- src/backend/input.rs
- src/backend/libinput.rs
- src/backend/winit.rs
I have added the `EventLoopHandle` to the `InputHandler`s functions to allow creating/modifing/deleting wayland objects in reaction to received input events.
E.g.
- Creating a `Seat`, `Pointer`, `Keyboard` on `on_seat_created`.
- Modifing a window in reaction to keypresses
> Add EventLoopHandle to `InputBackend` and `InputHandler` traits

- src/wayland/shell/wl_handlers.rs
Invalid data was set as user data for wl_shell_surface, causing
access to invalid memory at drop time.
Fixes #60
> wayland.shell: fix memory corruption in wl_shell

- src/backend/winit.rs
This adds an additional `WinitEventsHandler` to our `WinitBackend`. This allows a real compositor to receive additional window events not available in the more restricted `InputHandler`, that it might be interested in.
This also exposes the underlying `winit::Window` object to allow further customization like the window title or to receive properties of the window, like its hidpi factor, if the compositor wants to take that into account.
I figured giving the user more control is way easier then adding a bunch of functions to the backend for that purpose and follows smithay's philosophy.
> Winit handler

- src/backend/input.rs
- src/backend/libinput.rs
- src/backend/winit.rs
Otherwise this information gets lost in the `InputHandler` and cannot be passed onto `smithay::wayland::seat::Seat::new`.
> Add names to backend seats

- src/wayland/seat/mod.rs
I don't know why this even compiles without the reexport, probably because it is only passed into a closure (I still think this should be a hard error, and I should probably think about reporting that to rustc).
Anyways I noticed, that `ModifiersState` is greyed out in [our documentation](https://docs.rs/smithay/0.1.0/smithay/wayland/seat/struct.KeyboardHandle.html#method.input) and there is no way to import the type. This PR fixes this.
Btw I think we should think about how we use types of other crates. Right now we expect the user to depend on the same library version of crates like libxkbcommon as we do to get things like `Keysym`. I am guilty of that as well in the backend code (there is no way to write a real compositor without depending on drm.rs), maybe we should re-export these as …
> Reexport ModifiersState to make it publically accessible

- src/backend/drm/backend.rs
Allows for easier handling of drm related stuff in a compositor. Nothing really special, this is safe, because you could just receive the `RawFd` of the `DrmDevice` and build your own clonable struct that implements `drm::Device` and `drm::control::Device`, this is just for usability reasons.
> Allow `DrmBackend` to act as `drm::control::Device`

- Cargo.toml
- examples/drm.rs
- examples/udev.rs
- src/backend/drm/mod.rs
- src/backend/libinput.rs
- src/backend/session/auto.rs
- src/backend/session/dbus/logind.rs
- src/backend/session/direct.rs
- src/backend/session/mod.rs
- src/backend/udev.rs
`DrmDevice` and `UdevBackend` now do not need to be wrapped into `StateToken`s anymore, but can return a separate `SessionObserver` object using the new `AsSessionObserver` trait.
This change was motivated by allowing the `UdevHandler` to obtain a mutable reference to an `EventLoopHandle` to create a wayland object, e.g. a `wl_output` object.
Previously this was not possible.
Depends on https://github.com/Smithay/wayland-rs/pull/164
~### TODO:~
> Introduce SessionObserver

- examples/drm.rs
- examples/helpers/glium.rs
- examples/udev.rs
- examples/winit.rs
- src/backend/graphics/glium.rs
This is kinda ugly, but I cannot think of a better way to allow mutable access, which is needed for many operations on the drm backend at least. e.g. mode setting.
@vberger if you have a better idea, please tell me.
> Update glium integration to allow mutable borrowing

- src/backend/winit.rs
#79 was not enough as winit actually sends negative mouse coordinates on the X11 backend...
> Fix winit transformed input for negative positions

- src/wayland/seat/keyboard.rs
This is very useful to implement serializable key bindings, e.g. in config files.
> Derive PartialEq,Eq,Hash for ModifiersState

- .travis.yml
- Cargo.toml
- src/lib.rs
- src/xwayland/mod.rs
- src/xwayland/x11_sockets.rs
- src/xwayland/xserver.rs
This is the very core of an XWayland infrastructure. Notably it does not provide an X11 WM implementation.
The full exposed API is:
```rust
/// Trait to be implemented by you WM for Xwayland
///
/// This is a very low-level trait, only notifying you
/// when the connection with XWayland is up, or when
/// it terminates.
///
/// You WM must be able handle the XWayland server connecting
/// then disconnecting several time in a row, but only a single
/// connection will be active at any given time.
pub trait XWindowManager {
/// The XWayland server is ready
///
/// Your previlegied connection to it is this `RawFd`
fn xwayland_ready(&mut self, fd: UnixStream, client: Client);
/// The XWayland server has exited
fn xwayland_exited(&mut self);
}
pub struct XWayland<WM: XWindowManager> { ... } …
```
> xwayland: core infrastructure

- src/wayland/compositor/mod.rs
Thanks to the refactor of wayland-rs, the CompositorToken can
be make Send/Sync again.
Fixes #66.
> wayland.compositor: CompositorToken is threadsafe

- anvil/src/glium_drawer.rs
- anvil/src/main.rs
- anvil/src/raw_drm.rs
- anvil/src/shaders.rs
- anvil/src/shell.rs
- anvil/src/shm_load.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- src/backend/graphics/egl/wayland.rs
- src/wayland/shm/mod.rs
- src/wayland/shm/pool.rs
Refactor the SHM-buffer loading code in anvil to properly load buffers and convert them to RGBA that is internally used by glium.
This removes the hack in the fragment shader that caused the EGL buffers to have wrong colors (as it was translating ARGB to RGBA).
This is not perfect, as loading SHM buffers is now suboptimal, but ideally we would take advantage of OpenGL various loading capabilities if they were exposed by glium...
As a side note, with this we can run alacritty in anvil without any visual glitch! :tada:
> anvil: fix shm buffer loading

- CHANGELOG.md
- Cargo.toml
- src/backend/graphics/egl/native.rs
- src/backend/winit.rs
This PR upgrades the winit backend to 0.17. I couldn't test this in detail since I can't open applications in anvil because of an error about seat manager support but I would assume none of these changes would have much affect.
> Upgrade winit backend to 0.17

- .travis.yml
As discussed on matrix, this is a try to speed up travis builds.
The reasoning is, that we just want to make sure all features do build independently,
but testing is only required once, so as long as tests are run for the "all" target, this should be enough.
> [travis] Only do cargo check for incomplete feature-sets

- anvil/src/udev.rs
- anvil/src/winit.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/mod.rs
With the new XkbConfig struct, it is now easier to just use xkbcommon's
default configuration, by moving the xkbcommon specific options into a
struct with according documentation.
Additionally, anvil now uses xkbcommon's defaults with all backends
(previously, the winit backend had a hardcoded french keyboard layout).
> Refactor Seat::add_keyboard

- anvil/src/input_handler.rs
- anvil/src/window_map.rs
- src/wayland/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
cc #106 
This is the groundwork for support of pointer grabs by clients (by far the most common kind of grabs). In detail, this PR:
- Introduces a global `SerialCounter` in smithay to synchronize the creation of serials, and make anvil use it
- Introduce the `PointerGrab` trait, which represent a capability for a struct to manage a pointer grab.
- You can see it as a middleware that is inserted between the interface for the backend to send events and the interface actually sending the events. The grab can manipulate the events before sending them to the client.
- This functionality is required for things like Drag'n'Drop, or popup grab in the shell protocols
- This required modifying the pointer API to allow the grabs to access the information they need. As such, the motion of a pointer …
> Introduce a global serial counter and pointer grab mechanism

- src/backend/winit.rs
This reworks dpi handling in the winit backend to only expose physical pixel values to the user, while still exposing the winit dpi factor as an information.
This brings the winit backend in par to the framebuffer one: all is done in physical pixels by default and the compositor using smithay is responsible for choosing the dpi factor it wants to use.
This also makes anvil run correctly again on hidpi screens under winit even though not being hidpi aware.
> Rework dpi scaling in the winit backend

- src/wayland/shell/xdg/xdg_handlers.rs
- src/wayland/shell/xdg/zxdgv6_handlers.rs
- vagga.yaml
As the comment in the code states, the role check should be skipped for toplevels linked to dead surfaces.
The current code however not only skipped the check, but also the cleanup of the global toplevel list. Which is obviously wrong. This PR fixes that.
> wayland.shell: Fix a leak of surfaces

- anvil/src/glium_drawer.rs
- anvil/src/shell.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
depends on #115 
fixes #49 
This introduces the necessary code in the wayland protocol handlers to correctly process requests from clients to set custom cursor images, both in general and in a DnD context.
This does *not* implement any of the necessary logic in anvil to actually display them.
> Protocol support for client-provided cursor surfaces

- README.md
Anvil doesn't seem to have the --tty-raw backend anymore, it was still being mentioned in the README though. I just removed it.
> Removed --tty-raw from README

- .travis.yml
The reasoning is as follow: testing smithay on beta and nightly mostly serves to spot potential regressions from rust. The test of individual features on stable is enough to ensure modularity is correctly kept.
This removes 46 jobs from the travis build, which imo were mostly waste of computing power.
> travis: don't test individual features on beta&nightly

- Cargo.toml
- anvil/src/glium_drawer.rs
- anvil/src/window_map.rs
- src/backend/egl/mod.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/tree.rs
Rework the subsurface tree by:
- forbidding subsurface loops
- storing the relative depth of a parent to its children,
finally respecting the wl_subsurface specification.
closes #23
Also contains a small bugfix of anvil, which would attempt to release the same EGL buffer several times, causing segfaults when trying to release an already-destroyed buffer (as it comes from mesa we don't benefit of the liveness-tracking of wayland-server...)
> Subsurface rework

- Cargo.toml
- anvil/src/glium_drawer.rs
- anvil/src/shell.rs
- anvil/src/udev.rs
- anvil/src/window_map.rs
- src/backend/egl/mod.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/tree.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/shell/legacy/mod.rs
- src/wayland/shell/legacy/wl_handlers.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shell/xdg/xdg_handlers.rs
- src/wayland/shell/xdg/zxdgv6_handlers.rs
Currently the compositor global handler has a `U` type parameter to allow the association of arbitrary associated data to a `wl_surface` in a general way.
However other protocols (like `wp_viewporter` or `linux-explicit-synchronization`) also need to associate arbitrary data to a surface.
Do avoid type parameter complication creep, this replaces this type parameter with a `UserDataMap`, a type-map-like abstraction that we are already using for `Client`-wide user data. This allows other modules to associate any data to a surface without the user needing to deal with it.
This also uses `UserDataMap` to store the shell-wide data in the `xdg_shell` abstraction.
I expect the runtime cost of this change to be pretty negligible except in very pathological cases maybe.
> Remove user data type parameters

- Cargo.toml
- src/wayland/explicit_synchronization/mod.rs
- src/wayland/mod.rs
There are relatively simple helpers, which only handle the "wayland protocol" part: the exchange of `dma_fence` file descriptors with the client.
I have absolutely no idea of how these file descriptors are to be used.
> wayland: introduce explicit-synchronization helpers

- src/backend/drm/gbm/mod.rs
- src/backend/drm/legacy/surface.rs
- src/backend/egl/ffi.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/tree.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/explicit_synchronization/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/shell/xdg/zxdgv6_handlers.rs
- src/wayland/shm/pool.rs
Simply ran:
```
rustup run nightly  cargo fix --clippy -Z unstable-options
```
No manual change in this commit.
Partially addresses https://github.com/Smithay/smithay/issues/45
> Fix clippy warnings with cargo fix

- Cargo.toml
- src/backend/session/dbus/logind.rs
This is step one of upgrading: no real code changes, still using the old API.
Will follow this up with an actual upgrade to the recommended new way of doing things.
> Upgrade to dbus 0.7, change imports to match.

- anvil/build.rs
- anvil/src/input_handler.rs
- anvil/src/main.rs
- anvil/src/shell.rs
- anvil/src/udev.rs
- anvil/src/window_map.rs
- anvil/src/winit.rs
- src/backend/drm/legacy/surface.rs
- src/backend/egl/context.rs
- src/backend/egl/ffi.rs
- src/backend/egl/native.rs
- src/backend/graphics/errors.rs
- src/backend/input.rs
- src/backend/libinput.rs
- src/backend/session/direct.rs
- src/backend/udev.rs
- src/backend/winit.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/roles.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/explicit_synchronization/mod.rs
- src/wayland/output/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/shell/legacy/mod.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shm/mod.rs
This commit removes some clippy warnings (to advance #45) by doing the following:
- replace usage of `mem::uninitialized()` with `MaybeUninit`
- replace usage of `nix::libc::{uint64_t, int32_t}` with `{u64, i32}`
- replace functions inside of `Option::ok_or` with `Option::ok_or_else`
- replace functions inside of `Result::unwrap_or` with `Result::unwrap_or_else`
- replace occurrences of pass-by-reference with pass-by-value when
appropriate
- replace unused variables in pattern-matching with wildcards
- replace `match` expressions that only have one case with `if let`
expressions
- replace UpperCamelCase names of consts with SCREAMING_SNAKE_CASE
- replace negated `is_some` with `is_none`
- remove `clone()` on types that implement Copy
- remove redundant imports
- remove `fn main()` from …
> fix some clippy warnings

- anvil/src/shell.rs
- anvil/src/window_map.rs
- src/utils/rectangle.rs
- src/wayland/compositor/mod.rs
This makes things like CSD shadows on weston clients and others clickable-through as they should be.
> anvil: add input region support

- anvil/src/buffer_utils.rs
- anvil/src/main.rs
- anvil/src/shell.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- src/backend/egl/mod.rs
This fixes the issue outlined in the IRC where moving the pointer around the surface would frequently result in the surface behind it getting focus. The problem was that when the buffer is committed, the texture (used for size calculations) gets set to None, and is updated only on the next draw, which can happen after `self_update`. `self_update` would thus think the surface was zero-sized.
An easy way to test this is to open something with sctk decorations and mouse over the buttons. Before the patch the buttons randomly lose color (because they become unfocused due to this bug), after the patch they work correctly.
> anvil: retrieve buffer dimensions on commit

- anvil/src/shell.rs
It doesn't need it, and it also takes the (0, 0) size literally, which makes everything try to be the smallest size possible initially.
Notably fixes sctk clients being one pixel wide initially if wl_shell is used.
> anvil.shell: don't send first configure to WlShell

- anvil/Cargo.toml
- anvil/src/shell.rs
- anvil/src/window_map.rs
- src/wayland/shell/legacy/mod.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shell/xdg/xdg_handlers.rs
- src/wayland/shell/xdg/zxdgv6_handlers.rs
Everything works, the geometry is computed as in Weston.
[Video!](https://streamable.com/52jd8) (the graphical glitches during gnome-calculator resizing are some OBS issue with capturing OpenGL that I've been seeing in other applications too)
Closes #94 
I tested the xdg-shell resizing on weston-terminal, alacritty and evince. I tested the wl-shell resize on the old weston-terminal ([this](https://gitlab.freedesktop.org/wayland/weston/commit/c0f17aba5e007821bf08e58b5033e7e545f6ab10) is the last commit before the xdg-shell switch) and on the sctk clients with xdg-shell disabled in anvil; the sctk clients seem to be computing the initial size incorrectly so the size jumps a little, but otherwise work fine.
The alacritty decorations being off-sync during a left resize seems like a bug in …
> anvil: implement the Resize request

- src/wayland/compositor/tree.rs
If the surface is not alive and is present among its own children, the code would deadlock.
> wayland: fix deadlock in SurfaceData::cleanup

- src/backend/winit.rs
The resize handler with a window resize request causes oscillations between two window sizes (presumably the inner and the outer). While it's not clear what part of the stack causes it, checking `window.get_inner_size()` already presents the correct size.
Either way, changing the same property in its change handler is a recipe for feedback loops as this one and should be avoided whenever possible, and then carefully fortified too.
> winit: Don't resize in resize handler

- anvil/src/udev.rs
I think exactly this feature combination lead to the introduction of `ANVIL_FEATURES` in Travis.
A good thing CI is up and running again, because when updating anvil for drm 0.4, I somehow forgot this again...
(Should fix anvil builds with `udev` but without `egl`.)
> anvil: Fix udev build without egl

- src/backend/session/dbus/logind.rs
If a session is terminated in a different VT, all other sessions are notified of its removal.
Removal events are now filtered to ensure its about this session.
> Ignore removal events for unrelated sessions

- Cargo.toml
- anvil/Cargo.toml
Add `backend_libinput_udev` feature to Smithay
This feature enables backend_libinput, backend_udev and input/udev features.
Use `backend_libinput_udev` feature in Anvil to fix build
> Fix Anvil build

- Cargo.toml
- anvil/Cargo.toml
- anvil/src/udev.rs
- src/backend/session/direct.rs
- src/backend/udev.rs
This upgrades our udev dependency to 0.4, which does not require a context anymore, therefor simplifying our code.
This also updates input-rs in one go, as it also depends on udev and the old version still expects a context, which we are now unable to provide.
The new input-rs version also enables us to use functions introduced in newer libinput versions. But because we are not doing so now, I have for now disabled its features.
But we are re-exporing libinput and users might have use-cases for the later versions, so we should likely make this configurable in the future (through more features....).
> Update to udev 0.4

- Cargo.toml
No longer required as noted in https://github.com/Smithay/smithay/pull/181#discussion_r408170484.
Should I also sort the dependencies alphabetically, to make oversights like the one that happened with wayland-client less likely in the future?
> Remove dependency on wayland-client

- anvil/src/buffer_utils.rs
- anvil/src/glium_drawer.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- src/backend/drm/egl/mod.rs
- src/backend/drm/egl/surface.rs
- src/backend/egl/context.rs
- src/backend/egl/display.rs
- src/backend/egl/mod.rs
- src/backend/egl/surface.rs
- src/backend/graphics/format.rs
- src/backend/graphics/gl.rs
- src/backend/winit.rs
Refactors the `backend:egl` to more closely represent how EGL works under the hood.
I have kept the exposed `EglSurface` api the same, Now it represents a `EGLContext` and `EGLSurface` pair. Allowing the `GLBackend` to still be implemented without the creation of a new type. Similar has happened for `winit`.
The old `EGLDisplay` has now became `WaylandEGLDisplay`, which can be created from either a `EglDevice`, `EGLDisplay, or `WinitGraphicsBackend`.
These changes should then make exposing shared contexts, and improving thread safety in the future a lot easier.
> Refactor EGL backend

- src/backend/libinput/helpers.rs
- src/backend/libinput/mod.rs
* move libinput.rs -> libinput/mod.rs
* add libinput/helpers.rs
* move chunks of code handling libinput::Event variants to their respective helper functions
No logic changed, the changes are purely cosmetic.
> Fix clippy::cognitive-complexity warning 

- Cargo.toml
- anvil/Cargo.toml
- anvil/src/udev.rs
- examples/raw_atomic_drm.rs
- examples/raw_legacy_drm.rs
- src/backend/drm/atomic/mod.rs
- src/backend/drm/atomic/session.rs
- src/backend/drm/atomic/surface.rs
- src/backend/drm/common/fallback.rs
- src/backend/drm/common/mod.rs
- src/backend/drm/egl/surface.rs
- src/backend/drm/gbm/session.rs
- src/backend/drm/gbm/surface.rs
- src/backend/drm/legacy/mod.rs
- src/backend/drm/legacy/session.rs
- src/backend/drm/legacy/surface.rs
- src/backend/drm/mod.rs
- src/backend/graphics/cursor.rs
- src/backend/winit.rs
This is finally ready for a first review...
TODO:
> Atomic modesetting support

- anvil/src/glium_drawer.rs
- anvil/src/main.rs
- anvil/src/shell.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/window_map.rs
- anvil/src/winit.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
A few anvil changes to make things work better overall
- commit 1: introduce a correct handling of frame callbacks
- commit 2: restore the behavior of Wayland dispatching to dispatch the clients in the calloop callback
- commit 3: refactor common portions of anvil into the `AnvilState`
- commit 4: send frame events in bulk to all clients that requested it just after each page flip
- commit 5: implement correct state caching for sync subsurfaces
> Fix anvil event loop

- Cargo.toml
- anvil/Cargo.toml
- anvil/src/shell.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- src/backend/drm/mod.rs
- src/backend/libinput/mod.rs
- src/backend/session/auto.rs
- src/backend/session/dbus/logind.rs
- src/backend/session/direct.rs
- src/backend/udev.rs
- src/xwayland/xserver.rs
depends on #202 
cc #203 
This only reworks the Smithay part, anvil is simply minimally modified to adapt by keeping the `UdevHandler` and just making a plumbing closure. Final goal would be to fuse the `UdevHandler` into the main `AnvilState`, but I'd like feedback on the Smithay API before attacking that.
> Rework the udev backend as a calloop event source

- anvil/src/glium_drawer.rs
- anvil/src/udev.rs
- examples/raw_atomic_drm.rs
- examples/raw_legacy_drm.rs
- src/backend/drm/atomic/mod.rs
- src/backend/drm/atomic/session.rs
- src/backend/drm/atomic/surface.rs
- src/backend/drm/common/fallback.rs
- src/backend/drm/common/mod.rs
- src/backend/drm/egl/mod.rs
- src/backend/drm/egl/session.rs
- src/backend/drm/egl/surface.rs
- src/backend/drm/gbm/egl.rs
- src/backend/drm/gbm/mod.rs
- src/backend/drm/gbm/session.rs
- src/backend/drm/gbm/surface.rs
- src/backend/drm/legacy/mod.rs
- src/backend/drm/legacy/session.rs
- src/backend/drm/legacy/surface.rs
- src/backend/drm/mod.rs
- src/backend/egl/context.rs
- src/backend/egl/display.rs
- src/backend/egl/error.rs
- src/backend/egl/mod.rs
- src/backend/egl/native.rs
- src/backend/egl/surface.rs
- src/backend/graphics/glium.rs
- src/backend/graphics/mod.rs
- src/backend/winit.rs
This is a first of a set of PRs addressing #205 .
This consists out of a number of small commits each doing some refactoring on the drm code (mostly legacy/atomic).
The changes are addressing:
- Some cleanups
> Fix drm mode and connector handling

- .github/workflows/ci.yml
- anvil/src/glium_drawer.rs
- anvil/src/udev.rs
- src/backend/drm/atomic/mod.rs
- src/backend/drm/atomic/session.rs
- src/backend/drm/atomic/surface.rs
- src/backend/drm/common/fallback.rs
- src/backend/drm/common/mod.rs
- src/backend/drm/egl/mod.rs
- src/backend/drm/egl/session.rs
- src/backend/drm/egl/surface.rs
- src/backend/drm/gbm/mod.rs
- src/backend/drm/gbm/session.rs
- src/backend/drm/gbm/surface.rs
- src/backend/drm/legacy/mod.rs
- src/backend/drm/legacy/surface.rs
- src/backend/egl/display.rs
- src/backend/egl/surface.rs
- src/backend/session/dbus/logind.rs
This PR ticks a lot of boxes in #205 (and likely fixes #208, #201, #168 along the way).
It is again best reviewed per commit.
- 75e7e47 fixes #208, which was broken by 31b6d844, which was not supposed to be merged in #206, but somehow landed on its branch. It was supposed to be part of this PR, so I cleaned and fixed it up here instead.
- retrying commits/page_flips needs some fixes to allow recovery:
- b96c63a fixes gbm to unlock buffers again on a failed commit/page_flip
- f30d9a1 makes sure resource cleanup on the last page_flip before pausing the device still happens
- 5af599d in case a commit fails, the atomic backend needs to keep the correct state to construct working atomic requests.
-  6550292 we sometimes get "permission denied", if we have not yet disabled the device, but are …
> Rework rendering loop

- .github/workflows/ci.yml
- Cargo.toml
- anvil/Cargo.toml
- anvil/src/udev.rs
- build.rs
- examples/raw_nvidia.rs
- src/backend/drm/atomic/mod.rs
- src/backend/drm/atomic/surface.rs
- src/backend/drm/common/fallback.rs
- src/backend/drm/egl/mod.rs
- src/backend/drm/egl/session.rs
- src/backend/drm/eglstream/egl.rs
- src/backend/drm/eglstream/mod.rs
- src/backend/drm/eglstream/session.rs
- src/backend/drm/eglstream/surface.rs
- src/backend/drm/gbm/egl.rs
- src/backend/drm/legacy/surface.rs
- src/backend/drm/mod.rs
- src/backend/egl/display.rs
- src/backend/egl/error.rs
- src/backend/egl/ffi.rs
- src/backend/egl/native.rs
- src/backend/egl/surface.rs
- src/backend/graphics/mod.rs
- src/backend/udev.rs
~~Alright, I have not yet had the time or motivation to clean up the  commit history and run some more extensive tests. This PR is mostly serving as a first look and to get myself motivated to finish this up sometime soon.~~
~~Initial work for~~ nvidia support closing #128!
~~Currently only the raw_nvidia example is really usable, but I want to upgrade `FallbackDevice` to support both `GBMDevice` and `EGLStreamDevice` to allow for a seamless integration into anvil soon.~~ **Done**
This is ready for review.
The first commits move a lot of egl-stuff around. eglstream has some different opinions on how surfaces should be constructed, which are no aligned with our egl-implementation and especially our `NativeSurface` trait. As a result most of the code in `EglSurface` had to be made part of …
> Add support for nvidia's EGLStream API

- src/wayland/seat/keyboard.rs
According to this: https://lists.x.org/archives/xorg-devel/2014-July/043110.html
> Sending modifiers before key is _seriously_ broken, and no-one should ever
do it. There are corner cases it completely and horrifically breaks.
So this PR fixes Smithay to not do that.
Thanks @kchibisov for finding this.
> wayland.seat: Send key event before modifier event

- Cargo.toml
- anvil/src/udev.rs
- examples/raw_nvidia.rs
- src/backend/drm/atomic/mod.rs
- src/backend/drm/atomic/session.rs
- src/backend/drm/atomic/surface.rs
- src/backend/drm/egl/mod.rs
- src/backend/drm/egl/session.rs
- src/backend/drm/egl/surface.rs
- src/backend/drm/eglstream/egl.rs
- src/backend/drm/eglstream/mod.rs
- src/backend/drm/eglstream/session.rs
- src/backend/drm/eglstream/surface.rs
- src/backend/drm/gbm/egl.rs
- src/backend/drm/gbm/mod.rs
- src/backend/drm/gbm/session.rs
- src/backend/drm/gbm/surface.rs
- src/backend/drm/legacy/mod.rs
- src/backend/drm/legacy/session.rs
- src/backend/drm/legacy/surface.rs
- src/backend/egl/context.rs
- src/backend/egl/display.rs
- src/backend/egl/surface.rs
This PR tries to make the drm `Surface`-implementations all `Send` to allow the rendering to happen in another thread.
@csnewman I would especially like you to test this branch with your flutter compositor.
You should be able to remove your hacks and move the surfaces without any problems.
Please report all errors, crashes, deadlock you encounter.
This PR is work-in-progress, because I have not given this much testing.
But since it was already working for your use-case and is only safer now, I do not expect this to cause much fuzz.
That said, I do not think it is reasonable to assume, that I did not miss anything.
I actually expect this to contain some rare and hard to debug errors, but I have no idea, how we should verify this approach without testing it in the wild. The documentation of …
> drm: Make surfaces `Send`

- src/wayland/seat/keyboard.rs
wl_keyboard.modifiers must be sent after wl_keyboard.enter event,
otherwise it's a protocol violation.
> wayland.seat: Send modifiers event right after enter event

- Cargo.toml
Older versions of dbus fail to compile due to API differences
> Update dbus to 0.8.3

- Cargo.toml
- src/backend/drm/atomic/mod.rs
- src/backend/drm/common/fallback.rs
- src/backend/drm/egl/mod.rs
- src/backend/drm/eglstream/mod.rs
- src/backend/drm/gbm/mod.rs
- src/backend/drm/legacy/mod.rs
- src/backend/egl/context.rs
- src/backend/egl/display.rs
- src/backend/egl/surface.rs
- src/backend/libinput/mod.rs
- src/backend/session/auto.rs
- src/backend/session/dbus/logind.rs
- src/backend/session/direct.rs
- src/backend/udev.rs
- src/backend/winit.rs
- src/lib.rs
- src/wayland/compositor/mod.rs
- src/wayland/data_device/mod.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/explicit_synchronization/mod.rs
- src/wayland/output/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/shell/legacy/mod.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shm/mod.rs
- src/xwayland/xserver.rs
- make `slog-stdlog` optional, but activated by default. This dependency has a significant dependency tree, but is not used at all if the downstream crate uses slog as well, rather than `log`.
- disable the default features of `image`, which we don't use at all
- make `tempfile` an optional dependency, it is only required by the wayland frontend.
> Lighten some dependencies

- anvil/src/shell.rs
- anvil/src/udev.rs
- anvil/src/window_map.rs
- anvil/src/winit.rs
This is what the protocol requires, and apps rely on it to figure
out how long time elapsed between draws.
> anvil: send millisecond time in frame callback

- src/xwayland/x11_sockets.rs
Here is a lock file not created by smithay:
```
$ xxd /tmp/.X0-lock
00000000: 2020 2020 2020 2035 3537 0a                     557.
```
And this is a lock file created by smithay:
```
$ xxd /tmp/.X23-lock
00000000: 2020 2020 3130 3733 3332                     107332
```
As you see, the difference is a trailing newline (0x0a).
Lock files 1 to 22 where also created by smithay, because I started it a
couple of times. Reading these lock files fails, since the code expects
a file with at least 11 bytes of content: It uses read_exact() with a
buffer of length 11 in the Err()-branch of the match that this commit
modifies.
Signed-off-by: Uli Schlachter <psychon@znc.in>
> Fix writing /tmp/.X{}.lock

- src/xwayland/x11_sockets.rs
When starting xwayland with smithay, the first time I would get the
following output (do not ask what happens with displays 0, 1, 2. That's
not important right now):
Dec 29 14:13:31.031 DEBG Attempting to aquire an X11 display lock, D: 3, smithay_module: XWayland
Dec 29 14:13:31.032 DEBG X11 lock aquired, D: 3, smithay_module: XWayland
Dec 29 14:13:31.032 INFO Initialization completed, starting the main loop.
When killing the process with ctrl-c and starting it again, this
happened:
Dec 29 14:13:29.138 DEBG Attempting to aquire an X11 display lock, D: 3, smithay_module: XWayland
Dec 29 14:13:29.138 DEBG Failed to acquire lock, D: 3, smithay_module: XWayland
Dec 29 14:13:29.138 DEBG Lock was blocked by a defunct X11 server, trying again, D: 3, smithay_module: XWayland
Dec 29 14:13:29.139 …
> xwayland: Unlink X11 socket before binding to it

- src/wayland/dmabuf/mod.rs
- src/wayland/shm/mod.rs
This fixes the following clippy warnings:
```
error: usage of `Rc<T>` when T is a buffer type
--> src/wayland/dmabuf/mod.rs:265:14
|
265 |     formats: Rc<Vec<Format>>,
|              ^^^^^^^^^^^^^^^ help: try: `Rc<[Format]>`
|
= note: `-D clippy::rc-buffer` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#rc_buffer
error: usage of `Rc<T>` when T is a buffer type
--> src/wayland/shm/mod.rs:91:14
|
91 |     formats: Rc<Vec<wl_shm::Format>>,
|              ^^^^^^^^^^^^^^^^^^^^^^^ help: try: `Rc<[wl_shm::Format]>`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#rc_buffer
```
Signed-off-by: Uli Schlachter <psychon@znc.in>
-----
I took another look at this due to all the …
> Make clippy happy

- src/xwayland/launch_helper.rs
- src/xwayland/mod.rs
- src/xwayland/xserver.rs
Calling `fork` in a multi-threaded program is dangerous. According to `man fork`, you are only allowed to call async-signal-safe functions afterwards. `exit` is not async-signal-safe. Hence in #244 I reported seeing crashes from some exit handlers when the forked child process tries to exit.
This PR adds a new `ForkHelper` to the public API. It can be created via `ForkHelper::fork()`, which is `unsafe`, because it calls `fork`. The `ForkHelper` can then later be used to actually launch XWayland.
(This PR also fixes the problem from #244 by simply not calling `exit`, because the fork helper process keeps running after starting `Xwayland`... However, I now get a double panic when closing the winit window because of a failed unwrap. At least no running processes seem to remain.)
This PR was …
> XWayland: Use a fork helper process to launch Xwayland

- src/backend/winit.rs
It is not necessary to set the cursor position on winit since the
windowing system already updates the position on its own. Instead, doing
this makes the cursor (almost) stuck and unmovable. Thus, this commit
just removes that code from the winit backend.
Fixes: https://github.com/Smithay/smithay/issues/241
Signed-off-by: Uli Schlachter <psychon@znc.in>
> winit: Allow moving the cursor

- src/backend/session/auto.rs
I think this was missed on a previous refactoring pass, and never got
tested?
Here's the error I got trying to run anvil:
```
Compiling smithay v0.2.0 (/home/benjamin/projects/rust/smithay)
error[E0425]: cannot find function `slog_or_stdlog` in module `crate`
--> src/backend/session/auto.rs:106:29
|
106 |         let logger = crate::slog_or_stdlog(logger)
|                             ^^^^^^^^^^^^^^ not found in `crate`
```
I also got a whole bunch of warnings, but I can fix those in a different PR.
> Replace usage of slog_or_stdlog with slog_or_fallback

- anvil/src/shell.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
This PR changes the `frame_callback` to a `Vec` of `frame_callbacks`.
A client is allowed to register multiple frame callbacks with a single commit.
This will fix the startup of firefox-wayland which does use more than a single frame callback.
> Fix frame callbacks for firefox

- examples/raw_drm.rs
- src/backend/allocator/dumb.rs
- src/backend/allocator/gbm.rs
- src/backend/allocator/mod.rs
- src/backend/allocator/swapchain.rs
- src/backend/drm/render.rs
This change fixes modifier selection by delegating this to the allocators
and thus to libgbm, which can ask the driver for an appropriate modifier
for scanout, that results in the best possible performance.
We do not have this information, the order in which modifiers are returned
by EGL has no meaning and this is far better then testing modifiers
non-deterministically at random and choosing the first one, that does
not error out...
> allocator: Let the allocator select the best modifier out of a given set

- .github/workflows/ci.yml
Currently we always run tests for specific features with the default set enable, which is really pointless as the default set is current equivalent to "all". Lets fix that.
> ci: Test specific features without default set

- anvil/src/drawing.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- src/backend/allocator/dmabuf.rs
- src/backend/allocator/gbm.rs
- src/backend/egl/context.rs
- src/backend/egl/display.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- src/backend/winit.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/mod.rs
Based on #261.
Finally fixes #96.
Provides support for client buffers submitted through the `linux-dmabuf` protocol extensions. Takes the (in my opinion) cleaner code of the `BufferInfo` struct in the existing protocol implementation and unifies that with the `backend::allocator::dmabuf` module to provide a common dmabuf type across smithay.
Currently just as limited as our wl_drm/egl-buffer implementation. We can only display buffers on the primary gpu on multi-gpu setups.
Tested using `weston-simple-dmabuf-egl` and `XWayland`.
> Dmabuf support

- anvil/src/shell.rs
- anvil/src/window_map.rs
- src/utils/mod.rs
- src/utils/rectangle.rs
- src/wayland/compositor/roles.rs
- src/wayland/shell/legacy/mod.rs
- src/wayland/shell/legacy/wl_handlers.rs
- src/wayland/shell/mod.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shell/xdg/xdg_handlers.rs
- src/wayland/shell/xdg/zxdgv6_handlers.rs
Based on the ideas of #97 
At the moment there is one surface role, `XdgSurfaceRole`, defined for the `xdg_shell` which is
assigned to the surface during processing the request `shell.get_xdg_surface`.
The `xdg_shell` protocol specification defines that the `xdg_surface` itself is not a role for `wl_surface`.
While it could be used as a simplification to represent it as a role in the compositor i believe it comes with
a few downsides. One is that it does not reflect the specification, the second one is that i find it cumberstone to
match on the `XdgSurfaceRole.pending_state` when processing the surface state. If a surface has been for example
assigned a role of `xdg_toplevel`, which is defined as a surface role in the specification, there should be no need to check if the …
> rework xdg_shell

- anvil/src/input_handler.rs
- anvil/src/state.rs
This PR adds tracking for suppressed keys in anvil. 
A key will be suppressed when a key press triggers a action.
On release the key will be forwarded to the client depending on if
the key has been suppressed or not.
fixes #242
> track suppressed keys

- src/wayland/dmabuf/mod.rs
This PR just removes a duplicated `clippy` annotation.
> fix clippy unknown lint

- anvil/src/udev.rs
- src/backend/drm/mod.rs
- src/backend/drm/surface/gbm.rs
- src/backend/drm/surface/mod.rs
- src/backend/renderer/gles2/mod.rs
Removes the renderer from the `DrmRenderSurface` allowing anvil to use just one renderer per backend.
Will allow the `ImportEGL`-trait to hold the `EGLBufferReader` (to be done in a future PR).
Since the old `DrmRenderSurface` was dependant on gbm anyway to import buffers, the new `GbmBufferedSurface` does now only supports gbm as an allocator.
Thus it was renamed. This gets rid of tons of generics, which were not very useful to begin with. There are no useful other allocators that can be imported into gbm (only DumbBuffers might work here, but this still can be implemented, just not with this surface). This also allows us to skip our weird gbm->dmabuf->gbm export-import cycle. The buffer is now only exported once. (cc @cmeissl, if I remember correctly, this helps your compositor.)
The …
> Rework DrmRenderSurface into GbmBufferedSurface

- anvil/src/drawing.rs
- anvil/src/shell.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- src/backend/egl/display.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
This moves the responsibility of managing an `EGLBufferReader` into types implementing `ImportEgl` (right now only our `Gles2Renderer`) to get rid of most of the `feature = egl` cfg-options in anvil.
Especially `anvil/src/drawing.rs` is now a lot cleaner, ~~but since the buffer reader (or the renderer) is required to read out the buffer dimensions, egl still bleeds into `anvil/src/shell.rs`~~ - worked around by using a global inside smithay.
> Move `EGLBufferReader` management into `ImportEgl`

- anvil/src/winit.rs
- src/backend/winit.rs
A shortcut for `bind_wl_display` on the winit backend was left over from the egl-rework in #303.
Using that lead to dropping the `EGLBufferReader` after it was just created and also never assigning the reader to the `Gles2Renderer`. This is now fixed by removing the left over function and using the function of `ImportEgl` correctly in anvils winit-backend.
> Fix wl_drm on winit backend

- src/backend/winit.rs
The simple explanation for this pull request is the input handling for winit should be entirely graphics independent. Currently the input has to have an egl surface to resize. This simply adds a Cell<Option<(u32, u32)>> to tell the graphics backend when a resize occurs and resize before rendering. This shifts the responsibility of resizing the egl surface to the graphics backend.
> Winit: Share the resized size instead of using egl display field

- Cargo.toml
- anvil/src/input_handler.rs
- anvil/src/state.rs
- src/backend/input.rs
- src/backend/input/tablet.rs
- src/backend/libinput.rs
- src/backend/libinput/tablet.rs
- src/backend/winit.rs
- src/wayland/mod.rs
- src/wayland/tablet_manager/mod.rs
- src/wayland/tablet_manager/tablet.rs
- src/wayland/tablet_manager/tablet_seat.rs
- src/wayland/tablet_manager/tablet_tool.rs
It took me a few rewrites, but I think the API is finally in kinda usable state now, and I think it's better to just open a PR and hear your opinion, instead of rewriting it once again :smile: 
- winit support is not there, because winit does not expose any tablet specific events (it you ever decide to go #293 route, I would be happy to add tablet support to that).
- This PR does not include `tablet_pad_v2` (tablet buttons, etc) support, it is only for tablet tools (like pens).
- Tablet tool cursors are independent of mouse pointers, but anvil treats them as one for now, as I don't think it's important for anvil.
- I'm not sure how to handle `NewDevice`, `RemovedDevice` events in anvil, as those are libinput specific events, for now I hard-coded `InputBackend<SpecialEvent = …
> Graphics tablet support

- anvil/Cargo.toml
- anvil/src/main.rs
- anvil/src/udev.rs
- src/backend/egl/context.rs
- src/backend/egl/display.rs
- src/backend/egl/error.rs
- src/backend/egl/ffi.rs
- src/backend/egl/native.rs
- src/backend/egl/surface.rs
- src/backend/winit.rs
Every commit stands for themselves, I have taken care to properly explain every commit in its message..
This is best reviewed one at a time.
I can easily drop any commit from this PR, if any turns out to be controversial, they do not depend on each other.
1. Makes the egl-display handle public, which it should have been in the first place.
2. Moves responsibility from the common egl-surface code into the native surface glue-code.
3. Adds debug logging to libEGL.
4. Fixes a recent regression @PolyMeilex pointed out on matrix.
> Various smaller fixes/additions to our egl stack

- anvil/src/drawing.rs
- anvil/src/input_handler.rs
- anvil/src/output_map.rs
- anvil/src/shell.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- src/backend/input/mod.rs
- src/backend/input/tablet.rs
- src/backend/libinput/mod.rs
- src/backend/libinput/tablet.rs
- src/backend/renderer/mod.rs
- src/backend/winit.rs
This PR adds support for HiDPI to anvil.
The scaling supports fractional scaling and will announce the rounded value to the wayland output.
The initial scale of an output can be set with the envorinment variable `ANVIL_SCALE_{short-name of output}`.
The scale can be changed with the keyboard shortcut `LOGO + SHIFT + P` to increase and  `LOGO + SHIFT + M` to decrease in 0.25f32 steps
Toplevels and the pointer (on udev) will be automatically moved after changing the scale so that they appear stable.
closes #104
> Anvil HiDPI

- anvil/src/shell.rs
Currently, when you move a maximized toplevel in Anvil, it gets stuck in this confusing state where it thinks it is maximized (so for example we can't resize it), but in reality it no longer is maximized.
Possible solutions are:
- ignore move when toplevel is maximized (that's what Weston does)
- unmaximize it and start a MoveSurfaceGrab (that's what most compositors do)
This PR adds a second solution to anvil.
For Anvil's simplicity sake, it omits some positioning calculations, but I left a comment describing those in the code.
> Automatically unmaximize toplevel when it is moved

- src/backend/egl/ffi.rs
Apparently the nvidia-egl-stack can return null pointers for the command string...
> egl: Fix segfault in egl logging for empty command strings

- src/backend/renderer/gles2/mod.rs
This can help with some optimizations and since we already allow direct access to the OpenGL context anyway, lets expose this.
> gles2: expose texture id

- Cargo.toml
- anvil/Cargo.toml
- anvil/src/lib.rs
- anvil/src/main.rs
- anvil/src/shell.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/window_map.rs
- anvil/src/winit.rs
- wlcs_anvil/Cargo.toml
- wlcs_anvil/src/ffi_api.rs
- wlcs_anvil/src/ffi_wrappers.rs
- wlcs_anvil/src/lib.rs
- wlcs_anvil/src/main_loop.rs
- wlcs_anvil/src/renderer.rs
This introduces integration of WLCS testing on anvil, by making anvil into a lib+bin crate and adding a new `wlcs_anvil` crate that builds the `.so` that WLCS expects to load.
The current code is the bare minimum allowing the test suite to actually run (rather than crash after a single test), but most tests fail, mostly due to this todo:
https://github.com/Smithay/smithay/blob/26dc2ff55c02e5ff8f590d96ec840f617fc88e89/wlcs_anvil/src/main_loop.rs#L154-L157
> Main structure of WLCS integration

- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/server_dnd_grab.rs
Addresses problem outlined in #326
I have read thought Weston implementation and Smithay one side by side, and it seems that they mostly work the same way, the only deference I can spot are the checks in data offer SetAction handler:
https://github.com/Smithay/smithay/blob/6b2273235a88032063063ac23b2dedd9fad93fb9/src/wayland/data_device/dnd_grab.rs#L312
Adding `DndAction::None` to the list seems to fix the problem. (it looks like [weston](https://github.com/wayland-project/weston/blob/7a44ee7f37803b8b1c3829672d07c5328b878456/libweston/data-device.c#L189) and [wlroots](https://github.com/swaywm/wlroots/blob/a38baec1f89d423dea4be85a6233fed26d13732f/types/data_device/wlr_data_offer.c#L155) do the same)
After this commit, the compositor no longer crashes when running apps like nautilus or …
> Changes to drag and drop protocol

- README.md
The logind feature is enabled by default.  It doesn't need to be
manually enabled.
> Update Anvil logind documentation

- CHANGELOG.md
- Cargo.toml
- src/wayland/mod.rs
- src/wayland/shell/legacy/mod.rs
- src/wayland/shell/legacy/wl_handlers.rs
- src/wayland/shell/mod.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shell/xdg/xdg_handlers.rs
- src/wayland/shell/xdg/zxdgv6_handlers.rs
- src/wayland/xdg_foreign/mod.rs
Implementation of the xdg-foreign protocol. This allows a client to export a surface and then allow another import the surface using a handle. 
So what's needed otherwise:
> Implement xdg-foreign protocol

- CHANGELOG.md
- anvil/src/drawing.rs
- anvil/src/input_handler.rs
- anvil/src/output_map.rs
- anvil/src/shell.rs
- anvil/src/udev.rs
- anvil/src/window_map.rs
- anvil/src/window_map/layer_map.rs
- anvil/src/winit.rs
- src/wayland/shell/mod.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/wlr_layer/types.rs
- src/wayland/shell/xdg/mod.rs
Design goal of this implementation was to make its API as similar to `xdg-shell` as possible, the idea is that if someone already knows how to use `xdg-shell` they should be able to start using `layer-shell` by using nearly the same API. So `CachedState`, `with_pending_state`, `current_state`, etc. are all there, and should act just like xdg equivalents.
Anvil implementation of layer shell is lacking at the moment, I wanted to implement everything but the more I added, the hackier the code felt, so I decided to stop. The main missing piece for anvil is exclusive_zone support, but I think that I implemented enough to make it a useful test ground for future changes.
https://user-images.githubusercontent.com/20758186/127673456-3296c042-69a6-478f-8a71-dccf66dbef8b.mp4
> WLR Layer Shell Support

- CHANGELOG.md
- anvil/src/shell.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shell/xdg/xdg_handlers.rs
- src/wayland/shell/xdg/zxdgv6_handlers.rs
- wlcs_anvil/src/lib.rs
This PR adds support for `xdg_wm_base` version 3.
The positioner gained support for the new fields and handles the requests for:
- set_reactive
- set_parent_size
- set_parent_configure
**[Breaking]** The positioner state has been moved to the `PopupState` so that it can be updated during handling the `reposition` request. `XdgRequest::NewPopup` has been extended with the position state to make the initial geometry calculation easier.
The `XdgRequest` has been extended with `RePosition` and the function `send_repositioned` has been
added to `PopupSurface`.
A simple implementation was added to anvil.
The protocol adds new toplevel states for tiling. `send_configure` will filter them if the client protocol version
is lower that the required `SINCE`
The `send_configure` now checks for the …
> support for xdg-shell v3

- anvil/src/xwayland/mod.rs
- anvil/src/xwayland/x11rb_event_source.rs
We talked about this a bit on IRC/Matrix: x11rb has an internal queue where it keeps X11 events. When an API call waits for the reply to a request, but an event comes in, the event is added to the queue. Thus, "there are pending X11 events" and "the X11 socket is readable" are not equivalent and the whole calloop integration breaks down and may miss wakeups.
This PR fixes that by spawning a dedicated thread that calls `wait_for_event` in a loop. A calloop channel is used to "feed" these events to the main thread.
Thus, `X11Source` becomes a wrapper around a `Channel` which is a wrapper around a `PingSource´... :-)
Thanks for your tips and the discussion you provided.
> Anvil: Use a dedicated X11 event thread for event reading

- anvil/src/lib.rs
- anvil/src/render.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
At the moment also splitting out Drag n' Drop and cursor rendering requires unraveling some backend specific stuff.
> anvil: Split out logic for drawing layers and windows from backends

- CHANGELOG.md
- src/backend/session/libseat.rs
Queue libseat events and dispatch them after libseat dispatch is done to avoid double borrows
> backend.libseat: Fix dispatch double borrow

- CHANGELOG.md
- anvil/src/input_handler.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/mod.rs
Currently keycodes are always converted using xkbcommons
`State::key_get_one_sym` function. This may be not what the compositor
wants, e.g. if it represents keybindings with explicit modifiers.
Applying Shift in this case changes the sym, making it necessary for
the compositor to *undo* this transformation, which is hard or even
impossible and very unnecessary, when we have all the necessary
information in smithay.
Therefor this commit replaces the `Keysym` argument of the filter
closure with a `KeysymHandle`, which allows for different variants of
keysyms to be received. Modified (as previously), unmodified or even
as a raw keycode.
> wayland/seat: Add `KeysymHandle` to allow for keycode conversions.

- .github/workflows/docs.yml
This should hopefully fix the failing docs build.
> docs: Update calloop in CLI

- src/wayland/compositor/tree.rs
The subsurface logic holds a self-reference to the WlSurface to
track stacking orders of the children relative to the parent. This
self-reference needs be dropped during cleanup to avoid reference
cycles.
This was not the case, and caused every surface user data to be
leaked as it kept a reference to itself (and all of its children).
> wayland.compositor: fix leak of surface data

- anvil/src/input_handler.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
This PR exists to reduce the amount of duplicate code in anvil's input handling.
We merge the logic for winit and x11 backends through the `AnvilState::process_input_event_windowed`. The common key action logic is also taken into another function which winit, x11 and udev call for `None`, `Quit` and `Run`
> anvil: deduplicate some input handler logic

- src/wayland/shell/xdg/mod.rs
Currently the `shell_surface` is not accessible to the outside, meaning
there is no way to query for the XDG shell protocol version supported by
the client.
Adding a `version` method fixes that problem, which allows compositors
to act differently based on the supported protocol version. As an
example this allows setting the state to `State::Maximized` if the
tiling states are not available.
> Add version method to ToplevelSurface

- CHANGELOG.md
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- wlcs_anvil/src/renderer.rs
First set of changes discussed on matrix.
For motivation see https://github.com/Smithay/smithay/discussions/363#discussioncomment-1505061 .
TL;DR: A software renderer (and potentially others) cannot support the matrix style `render_texture` api, so lets move that into the `Gles2Renderer`.
Feedback welcome.
> Refactor Renderer API

- CHANGELOG.md
- src/wayland/shell/mod.rs
- src/wayland/shell/xdg/mod.rs
This PR fixes an Issue where consecutively calling the following code
could loose some configured state if the state is not acked by the client
between the calls.
```
ToplevelSurface::with_pending_state(|state| {
...
});
ToplevelSurface::send_configure();
```
The fix uses the latest non acked configure when available to accumulate
the pending state changes.
> use the latest pending server state if available instead of the current state

- CHANGELOG.md
- Cargo.toml
- anvil/src/udev.rs
- examples/raw_drm.rs
- src/backend/allocator/swapchain.rs
- src/backend/drm/surface/gbm.rs
- src/utils/mod.rs
- src/utils/user_data.rs
Necessary changes (and some clean up) to support buffer age in the backend.
This is necessary to properly implement damage tracking.
Best reviewed on a commit-by-commit basis.
Explanation taken from [EGL_EXT_buffer_age](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_buffer_age.txt).
>     Buffers' ages are initialized to 0 at buffer creation time.
>     When a frame boundary is reached, the following occurs before
>     any exchanging or copying of color buffers:
>
>          * The current back buffer's age is set to 1.
>          * Any other color buffers' ages are incremented by 1 if
>            their age was previously greater than 0.
>
>      For the purposes of buffer age tracking, a buffer's content
>      is considered defined when its age is a value greater than 0.
> …
> backend: Support buffer age

- anvil/src/input_handler.rs
ScaleDown was doing the same thing as ScaleUp (probably someone copypasted and forgot to change the sign).
Now it should properly decrease scale.
> [Anvil] Fix ScaleDown scaling up

- anvil/src/x11.rs
- src/backend/allocator/swapchain.rs
- src/backend/x11/mod.rs
#419 and #421 brought buffer age support to the x11 backend.
However it is not utilized (yet) by anvil, causing two issues with the implementation to slip through.
#423 uncovered them and these two commits are cherry-picked from that PR to unblock further development of the X11 backend, while #423 is still in flux and will likely need a lot more time.
> Fixup for #419 and #421

- anvil/src/winit.rs
- src/backend/drm/device/mod.rs
- src/backend/drm/surface/mod.rs
- src/backend/egl/native.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/transaction.rs
- src/wayland/explicit_synchronization/mod.rs
- src/wayland/output/mod.rs
- src/wayland/seat/keyboard.rs
- src/wayland/shell/xdg/mod.rs
Rust 1.57.0 means new clippy lints.
Many of the new warnings are manual `default::Default` impls.
> resolve new clippy lints

- CHANGELOG.md
- anvil/src/x11.rs
- src/backend/allocator/mod.rs
- src/backend/x11/error.rs
- src/backend/x11/mod.rs
- src/backend/x11/window_inner.rs
This should allow the X11 backend to create multiple windows.
I have not implemented the handling of secondary windows in anvil yet but the single primary window is tested as working.
> x11: rework api to be multi-window capable

- CHANGELOG.md
- src/wayland/seat/keyboard.rs
This fixes clients reading the keymap from the `fd` directly to a string instead of using a memory map.
> rewind the keymap file before passing it to clients

- CHANGELOG.md
- src/utils/geometry.rs
- src/utils/mod.rs
So this is the result of a bunch of changes, that have piled up in #423 related to our geometry helpers.
I have extracted them to make review easier and quicker.
This also should address previous commits from @vberger on #423 related to `Rectangle::to_i32_{ceil, floor, round}` (4284ae471df6a5ddc966fe48c27daa2d933035e6).
Best reviewed commit-by-commit, if anything is controversial (like maybe 100f7ad70e0d8fd333048287e25f987cb2b42b76) I can always drop them from this particular PR.
> Geometry additions

- src/utils/geometry.rs
Right now `Rectangle::intersection` panics, if two rectangles don't overlap, but you try to compute the intersection, because `Rectangle::from_extemities` would create a rectangle with a negative size in that case.
I don't think even if it would not panic, that this call makes a lot of sense, so lets just return an `Option`.
> geometry: Don't compute intersection for non-overlapping rects

- src/backend/x11/mod.rs
Older dri3 versions (< 1.2) do only support dmabufs with one plane.
Lets limit the modifiers early, if we detect that, so we do not end
up allocating buffers the interface does not accept.
> x11: Don't use modifiers on old dri3 versions

- src/backend/drm/surface/atomic.rs
- src/backend/drm/surface/gbm.rs
Current use_mode implementation fails when the user tries to set a mode with higher resolution the the initial output mode.
The issue is cased by two places:
- the test_buffer uses the previous mode size, so when a new mode tries to commit on it and has higher resolution it fails with ENOSPC. This is fixed by the "make use_mode use the new mode size on test_buffer 9a7cd23" commit
-  after the test is successful the real buffer will reject the new pending mode on next commit unless resize on swapchain is called. This is fixed by the "call resize after applying new pending model 5ce5a8a" commit.
> Fix use_mode when trying to apply higher resolution then the current one 

- src/wayland/seat/mod.rs
An oversight, interesting Rust allows this, given it is part of the public api through the closure in `KeyboardHandle::input`.
> seat: Export KeysymHandle

- .github/workflows/docs.yml
Always build the doc on PRs, but only publish it on push.
> ci: always build doc

- src/wayland/seat/keyboard.rs
This PR add a simple function to KeyboardHandle with allows checking if they is currently a focused surface with grabs the keyboard.
Motivation behind it is when writing a WM with internal build in shell for example by using imgui keyboard events routed to it needs to be omitted if the Keyboard is focused on a surface.
> Allow checking if KeyboardHandle is focused on a surface

- anvil/src/winit.rs
- src/backend/egl/context.rs
- src/backend/egl/device.rs
- src/backend/egl/surface.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- wlcs_anvil/src/renderer.rs
Best reviewed on a commit-by-commit basis.
Addresses some short-comings I found implementing smithay-egui.
6e1f6ab1f3e4d3e705c55c51d6c17d09b6f39068 makes it possible to attach user_data to an `EGLContext`. Given that GL-resources like textures or buffers are local to a context, this is the obvious place to store them.
e0ad187411cbcb4e7d7586b9676c47a07069686f makes it possible to retrieve the `EGLContext` of a `Gles2Renderer` to actually access the user_data from downstream.
7ac8872a5ebac9cf8a6570da3ccaa4199dbe1751 and 07bf1e563955c00b2ec50bb51e48ce1c1562f577 expose rendering specifics of the `Gles2Frame`, that make it easier to correctly orientate and size externally drawn content.
04f6434b76c9ac0d2d1d7ed10873c9673005cbf3 allows downstream to retrieve the raw-egl handles, if they want to. …
> EGL and Gles2 cleanups and additions

- .github/workflows/ci.yml
This PR disables the new [non_send_fields_in_send_ty](https://rust-lang.github.io/rust-clippy/master/index.html#non_send_fields_in_send_ty) clippy warning for now.
As written in [rust-clippy/issues/8045#issuecomment-1013301645](https://github.com/rust-lang/rust-clippy/issues/8045#issuecomment-1013301645) this lint will be moved back to nursery in 1.58.1. 
Apparently this was done for `Nightly` and `Beta`, but not for `Stable`. see:  [rust-clippy/issues/8045#issuecomment-1010392770](https://github.com/rust-lang/rust-clippy/issues/8045#issuecomment-1010392770)
> disable clippy non-send-fields-in-send-ty

- src/desktop/space/mod.rs
- src/desktop/space/popup.rs
- src/desktop/window.rs
Fixes missing damage for removed popups inside the window bounds by tracking them like other toplevels. Drawing operations are still grouped, because popups without a parent are not useful. The only api that changes for downstream is `Window::accumulated_damage`, which now only returns the windows damage (as the docs suggested anyway) instead of including popup damage.
> desktop: Fix damage for removed popups

- src/utils/ids.rs
`fetch_update` returns the previous value, resulting in the current code assigning the id `0` twice.
> utils: correctly increment ids on first call

- src/desktop/space/mod.rs
Thanks for @cmeissl for reporting and providing reproduction instructions.
This avoids double damage for the same region, when a rectangle is added to the damage that overlaps with two existing (previously) non-overlapping rectangles. The original code would merge the new rectangle into whichever other rectangle was returned first without visiting the rest of the damage-array. This leaves two overlapping rectangles behind, which can cause broken renderings, because rendering two instances of the same toplevel is problematic, when transparent regions are involved. E.g. stacked drop shadows.
> space: Handle multiple overlapping rects when merging damage

- anvil/src/drawing.rs
- anvil/src/shell.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/backend/egl/display.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/utils.rs
- src/desktop/space/mod.rs
- src/desktop/utils.rs
- src/utils/geometry.rs
- src/utils/mod.rs
- wlcs_anvil/src/main_loop.rs
- wlcs_anvil/src/renderer.rs
Damage values for rendered textures on transformed outputs are currently off, because we calculate the positions in the cpu before uploading them to the gpu in opengl coordinate space.
The first commit simply applies the transformation beforehand.
The second fixes a slight mistake in the Transform::matrices and then finally applies buffer-transformations correctly instead.
To do that it:
- Moves `Transform` into utils::geometry
- Changes conversion from and into buffer-coordinates to take
`Transform` arguments.
- `Renderer` take `Buffer`-space instead of `Physical` (so render-space) damage now
- buffer_transform is taken into account everywhere
> Apply transformations correctly

- src/backend/renderer/gles2/mod.rs
Ok, this PR is awkward right after #466.
The first commit added a transformation, that I am removing now, because the second fixed the underlying issue, causing the previous commit to cause the bug it fixed previously...
To sum it up, because damage is now buffer based instead of surface based, we don't need to translate the damage in the renderer anymore, the shader does this for us. As a result the winit-backend (which needs a Transform of Flipped180) is broken again, while I didn't notice this, when testing the buffer-transfomations on the x11-backend...
Now both are applied fine (output and buffer transforms).
> gles: Don't apply output transformations to buffer damage

- src/desktop/layer.rs
- src/desktop/space/mod.rs
- src/desktop/utils.rs
- src/wayland/output/mod.rs
Currently we send neither popups or layers output enter or output leave events.
This series of commits tries to fix that and also refactors the logic of `Space::refresh` a bit to avoid adding too much duplicated code in the process.
> Send popups and layers output enter/leave events as well

- src/desktop/space/element.rs
Poly noticed, that rendering `RenderElement`s is of, when the output is not mapped to (0, 0), which is correct, because it is difficult to figure out for a custom element right now where it actually should draw. This PR adds a `location` parameter to the `draw` function, because we already do this calculation in smithay anyway.
@PolyMeilex please test. :)
> space: Pass a location to `RenderElement::draw`

- src/backend/allocator/swapchain.rs
- src/backend/drm/surface/gbm.rs
- src/backend/x11/surface.rs
Previously a buffer could only be marked of submitted, when it should also be released.
This breaks damage tracking in the `GbmBufferedSurface`, because for drm-operations we need to keep the buffer alive until it was actually scanned-out, but also need to increase the age after rendering is done for the next buffer to have the correct value.
> swapchain: Don't force release of submitted buffers

- CHANGELOG.md
- anvil/src/shell.rs
- src/desktop/layer.rs
- src/desktop/popup/grab.rs
- src/desktop/popup/manager.rs
- src/desktop/popup/mod.rs
- src/desktop/utils.rs
- src/desktop/window.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/shell/xdg/mod.rs
The PR adds support for popup grabs to the desktop abstraction.
A popup grab is only allowed before the initial commit, to check for that protocol error the field `committed` 
has been added to the `XdgPopupSurfaceRoleAttributes`.
To support exclusive keyboard focus a `KeyboardGrab` similiar to the existing `PointerGrab` has been added.
During testing i found an issue with the current popup handling that prevents menu popups from working correctly.
If a popup has no grab it should not receive the keyboard focus, for that a `WindowSurfaceType` has been added
that can be used to filter the surfaces in `surfaces_under`.
> Add support for popup grabs to desktop abstraction

- src/wayland/shell/xdg/mod.rs
- src/wayland/xdg_foreign/mod.rs
`set_parent` of `ToplevelSurface` always removed the current parent, this PR fixes that.
> fix setting the parent of a ToplevelSurface

- src/desktop/layer.rs
- src/desktop/space/element.rs
- src/desktop/space/layer.rs
- src/desktop/space/mod.rs
- src/desktop/space/popup.rs
- src/desktop/space/window.rs
This PR add support for definition of layer a RenderElement passed to render_output should be draw on.
This is done via layer function in RenderElement trait, it should return a layer an element should be draw on.
A default implementation is provided which makes the element render on top of all other elements to preserve the current behavior and not introduce any braking changes.
Marking PR as draft because I hope some comments/suggestion for improvements, mostly probably for for the whole render loop chain got pretty scary.
Maybe add some simple functions is_top, is_above_background etc. to at least skip the `c.layer() == RenderLayer::AboveBackground`? 
Another option would be to wrap the `&[DynamicRenderElements<R>]` in a struct and add something similar to `layers_on`.
Thanks for any …
> Add layer definition to RenderElement

- src/backend/egl/surface.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/winit/mod.rs
Previously if the buffer age of a `WinitGraphicsBackend`s back buffer was queried, it would never return a defined value, because it's surface will never have been bound, because the `Renderer::bind`-call would deferr its `make_current` call until the actual rendering.
Additionally this PR adjusts the `WinitGraphicsBackend::buffer_age` docs to warn the user of this behavior.
> winit: Fix returned buffer age

- anvil/src/udev.rs
- src/backend/drm/surface/gbm.rs
Right now the `GbmBufferedSurface` abstraction forces the use of a `GbmDevice` as an allocator.
This means users have to clone the underlying file descriptor to initialize multiple surfaces of the the same `GbmDevice`.
smithays internal code explicitly avoids this, because it may contribute to wrong or more difficult cleanup procedures, might prove to be a security hole, if the clone is not CLOEXEC, and even can mess up reference counting of buffer handles inside libgbm.
We already have a much better solution in smithay through implementations of the `Allocator`-trait for `Rc<RefCell<impl Allocator>>` and `Arc<Mutex<impl Allocator>>`. This PR adds a generic type to the `GbmBufferedSurface` to allow these variants to be used as well, as long as they produce a `gbm::BufferObject`.
This also …
> gbm: Allow usage of other allocators for GbmBufferedSurface

- Cargo.toml
- src/backend/drm/device/atomic.rs
- src/backend/drm/surface/atomic.rs
- src/backend/drm/surface/legacy.rs
Basically the only thing different for the current version of drm-rs is, that it uses the bitflags-crate now.
But it also brings some new function, which might be interesting for downstream (much less to smithay itself), so we should care to update.
> deps: Update drm-rs and gbm-rs

- examples/raw_drm.rs
- src/backend/drm/device/mod.rs
- src/backend/drm/mod.rs
For precise low-latency rendering it is important to now, when a frame event happened. We currently pass non of the timing related event fields from drm-rs to downstream. Lets make use of the calloop-Metadata to parse and change that.
> drm: Use EventMetadata to pass on frame timings

- anvil/src/udev.rs
Since `AnvilState::init` already initializes the socket, it shouldn't be
necessary to duplicate this in the `udev.rs` backend.
> Remove socket initialization from udev.rs

- anvil/src/state.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
Currently there is no way to know with which pointer a dnd-icon should be associated with.
(Anvil just uses it for all pointers, I think, but anvil also does not support multiple seats... so.)
> data_device: Pass seat to DnD events

- anvil/src/shell.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
- src/wayland/seat/pointer.rs
The pointer grab mecanism had a few inconsistencies in its behavior when
a grab is set or unset. THis commit uniformizes the behavior, and also
introduces a synthetic motion event when the grab is set, allowing the
newly set grab to change the focus or the pointer location if needed.
Also adjust the DnDGrab, as well as the resize and move grabs from anvil
to unset the focus while they are active, matching weston's behavior.
> wayland.seat: Fix pointer grab API

- Cargo.toml
- src/backend/renderer/utils.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/tree.rs
- src/wayland/seat/pointer.rs
- src/wayland/shell/mod.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/mod.rs
Remove unneeded liveness checks and introduce pro/post commit hooks as well as destruction hooks for surfaces.
> Refine compositor API

- anvil/src/input_handler.rs
- anvil/src/shell.rs
- src/desktop/space/mod.rs
- src/desktop/space/window.rs
Followup to  #491
As discussed on matrix, window_geo is being removed in favor of calling window.geometry() and doing any coordinate space calculations manually.
> desktop: Replace window_geo with window_location

- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/gles2/shaders.rs
- src/desktop/space/mod.rs
The patch 31b3088 introduced instanced rendering for efficiently
updating only the damaged area of the output. However due to this new
feature, support for older GPUs without instanced rendering was dropped.
This patch adds an alternative implementation which is chosen at runtime
when the target GPU does not support instanced rendering. It uses a
combination of uploading duplicate information and multiple draw calls
to somewhat efficiently mimic the effects of instanced rendering.
I've verified that with this patch it is now possible to run Anvil on my
PinePhone.
> Add support for GPUs without instanced rendering

- src/backend/session/dbus/logind.rs
- src/backend/session/direct.rs
- src/backend/udev.rs
- src/utils/x11rb.rs
- src/wayland/seat/keyboard.rs
- src/xwayland/x11_sockets.rs
- src/xwayland/xserver.rs
Specifically, aliases to io::Error, io::Result and nix::Result
> Replace redundant Result/Error typealiases

- examples/minimal.rs
- examples/seat.rs
- src/wayland/seat/keyboard/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/seat/pointer/events.rs
- src/wayland/seat/pointer/grab.rs
- Allows users to pass arbitrary data into grabs
- Implements `is_focused` method
- Implements `from_resource`  (Useful for potential multiseat support)
- Implements `user_data` method (I believe some yet unported modules will make use of it)
> 0.30: Update Seat to allow data passing

- src/utils/geometry.rs
I'd assume most Wayland consumers probably mostly want to deal with
Smithay's `Transform`, so it's nice to keep that type consistent in
consumer crates and then have it converted to the protocol's types on
demand.
I've refrained from making changes to the `change_current_state` method
in this patch to keep the patch as uncontroversial as possible, but
changing the parameters to `impl Into<Option<T>>` for at least the
transform of that method similar to how the Size/Point types are
implemented would probably help downstream.
> Implement `From<Transform>` for `wl_output::Transform`

- CHANGELOG.md
- src/backend/input/mod.rs
- src/backend/libinput/mod.rs
- src/backend/winit/input.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/touch.rs
While Smithay already supports libinput's touch events, it did not
support forwarding touch events to clients yet.
This patch implements a new `TouchHandle`, which can be acquired from
`Seat::get_touch`.
> Add client touch capability support

- examples/minimal.rs
The deadlocks appears to be caused by a single stray `handle()` call and egl blocking forever while swapping buffers because we did not dispatch and flush before.
> 0.30: fix deadlock in minimal compositor example

- anvil/src/shell.rs
- examples/minimal.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/transaction.rs
- src/wayland/seat/pointer.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/handlers/surface/toplevel.rs
- src/wayland/shell/xdg/mod.rs
Those checks existed because old version of compositor module required alive checks, but that's no longer the case.
> 0.30: Remove no longer needed alive checks

- src/desktop/space/mod.rs
Currently it is not possible to focus a window underneath another window by clicking through the dropshadow.
Instead of using the bounding box of the window, which includes the drop shadow, use the geometry to
find the window under the current pointer location.
> Use the window geometry to find the window under the pointer location

- Cargo.toml
- src/backend/egl/context.rs
- src/backend/egl/native.rs
- src/wayland/compositor/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shm/mod.rs
WlEglSurface is no longer Sync, so EGLNativeDisplay is only implemented for `Mutex<WlEglSurface>`.
> 0.30: update to alpha6

- src/wayland/seat/mod.rs
In the long term let's just get rid of this `pub use` stuff, it often causes issues where types are exposed in public api but not usable.
> 0.30: ensure all pointer and keyboard types are publicly available

- src/utils/geometry.rs
During working on crop & scale I found that `Transform::Flipped90` and `Transform::Flipped270` were swapped.
> fix rectangle transform Flipped90/270

- anvil/src/drawing.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/gles2/shaders.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/utils.rs
- src/desktop/space/mod.rs
- wlcs_anvil/src/renderer.rs
As discussed I changed the renderer to take `Physical` damage instead of `Buffer` damage. This greatly simplifies the calling code as the damage, which is provided in `Logical` coordinates from `Space`, can now be easily converted to `Physical` without using the buffer `Transform` and `Scale`.
In `render_texture` the `tex_coords` have been replaced by a matrix that describes how the vertices are translated to texture coordinates, including `y_inverted`.
~~For supporting fractional scale and crop the render functions are now generic over the `Coordinate`.~~
---
TODO:
> Use physical damage in the renderer

- anvil/src/input_handler.rs
When using anvil with the winit/x11 backend `ScaleDown` needs to be clamped to 1.0 just like in the udev backend
or otherwise it will crash.
> Fix anvil (winit/x11) crashing on ScaleDown

- anvil/src/drawing.rs
- anvil/src/render.rs
- anvil/src/udev.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/utils.rs
- src/desktop/space/mod.rs
- wlcs_anvil/src/renderer.rs
Based on https://github.com/Smithay/smithay/pull/527
This PR changes the renderer damage including `clear` to use `f64` just like the `dst` already did.
The problem with damage tracking and fractional output scale is that rounding the `dst` and or `damage` will
result in mismatches with the damage provided to `clear`.
> Fix damage tracking with fractional output scale

- src/wayland/compositor/handlers.rs
If the same buffer is attached multiple times to a sync subsurface without a commit on the parent in between releasing the old buffer will also release the new buffer.
After that the buffer will be dead and all access, including importing the buffer content will fail.
This can be observed by running foot:
```
...
[3145960.831]  -> wl_subcompositor@6.get_subsurface(new id wl_subsurface@37, wl_surface@36, wl_surface@19)
[3145960.838]  -> wl_subsurface@37.set_sync()
...
[3145962.725]  -> wl_surface@19.attach(wl_buffer@39, 0, 0)
[3145962.734]  -> wl_surface@19.damage_buffer(0, 0, 700, 26)
[3145962.741]  -> wl_surface@19.set_buffer_scale(1)
[3145962.744]  -> wl_compositor@5.create_region(new id wl_region@47)
[3145962.751]  -> wl_region@47.add(0, 0, 700, 26)
[3145962.758]  -> …
```
> do not release the buffer if old == new

- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/desktop/space/mod.rs
- wlcs_anvil/src/main_loop.rs
We need to always send frame callbacks, irregardless if the surface has been drawn or not. Some clients will just wait for the next frame callback to complete before updating their content.
For example firefox on a pointer axis event or when showing popup menus.
> Always send frame callbacks

- src/backend/drm/surface/atomic.rs
This resolves a regression introduced in 6260e46, which could lead to
compositors not finding any viable GPU due to their lack of the
`rotation` property.
Since this property is only set to ensure it has a sane default value,
it should not be necessary on devices where it is not present at all.
Fixes #536.
> Fix error due to unknown DRM rotation property

- src/backend/renderer/utils.rs
- src/desktop/utils.rs
- src/wayland/compositor/mod.rs
wayland/compositor is designed to expect downstream to drain/clear
the accumulated damage from `SurfaceData` on commit. To handle
multiple renderers the renderer/utils module did not do that, causing
damage to pile up indefinitely. This is obviously wrong, so this commit
attempts to fix this, by accumulating damage into `SurfaceState`
(clearing `SurfaceData` in the process) and keeping at most four commits
of damage for different renderers to consume.
> Fix surface-damage indefinitely accumulating

- src/wayland/compositor/handlers.rs
~If the client attaches a new buffer (either NIL or some new buffer) we should reset the current damage or we will end up
with wrong damage in case of sync subsurfaces where multiple attach/commits are called on the surface without a parent commit in between.~
If a surface gets unmapped by attaching a `NULL`  buffer we should also clear the pending damage.
fixes #494
> reset surface damage if it gets unmapped

- examples/minimal.rs
- src/backend/egl/display.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/utils.rs
- src/wayland/buffer/mod.rs
- src/wayland/mod.rs
- src/wayland/shm/handlers.rs
- src/wayland/shm/mod.rs
This adds a way for multiple types of WlBuffer to coexist. The interesting part of this is the `ManagedBuffer` type which statically asserts a buffer is managed by Smithay.
This is done in two commits:
- introducing the `buffer` module
- porting shm to use `buffer` module along with renderer changes.
> 0.30 buffer management

- anvil/src/input_handler.rs
- src/backend/egl/display.rs
- src/desktop/space/mod.rs
- src/desktop/utils.rs
- src/desktop/window.rs
- src/utils/signaling.rs
- src/wayland/compositor/handlers.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/shell/legacy/wl_handlers.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/xdg/decoration.rs
- src/wayland/shell/xdg/xdg_handlers.rs
This PR changes the input handling to always use the input region(s) to find the surface under a point.
Using the window bounding box blocks clicking through drop shadows and using the window geometry
is wrong as it will block input on decorations (breaking move and resize).
> desktop: allow to retrieve the surface under a point

- src/desktop/space/mod.rs
fixes elements moving from one output to another within a space without damaging there whole surface.
This is necessary as the damage seen is tracked per space, but the element geometry is tracked per output.
Issue reported by @PolyMeilex on matrix
> desktop: damage whole element on first appearance

- src/desktop/utils.rs
when querying a surface tree for damage the subsurface offset should always be added to the location.
fixes wrong damage location for surface trees with a depth greater than 1 when only the sub-subsurface
has been damaged by the client. otherwise the location would not account for the parent subsurface offset.
> desktop: always aggregate the subsurface offset

- anvil/src/input_handler.rs
- src/desktop/space/mod.rs
- src/desktop/space/popup.rs
- src/desktop/space/window.rs
the xdg-shell protocol defines that a window should be placed relative to its geometry. the geometry should only include user visible parts, so non funtional parts like drop shadows should be ignored for placement.
from the [spec](https://wayland.app/protocols/xdg-shell#xdg_surface:request:set_window_geometry):
> When maintaining a position, the compositor should treat the (x, y) coordinate of the window geometry as the top left corner of the window.
this also fixes maximize for a lot of clients where before some parts of the decorations (menu bar) where not visible and the size did not align with the output size.
placing a window at (0,0) works now fine for most clients, but it seems that winit (or at least glutin) based clients do not put their decorations inside the geometry when run …
> desktop: place a window relative to its geometry

- CHANGELOG.md
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/wayland/output/mod.rs
- src/wayland/output/xdg.rs
- wlcs_anvil/src/main_loop.rs
As discussed on matrix, certain protocol implementations (e.g. wlr_output_management) are not desirable directly in smithay.
Still they might want to piggy-back on internal smitay types. This PR makes an attempt to make most of the state of `Output` accessible in some way and also decouples the `Output`-type from the existance of a matching `Global`.
See #558 for a example implementation, that makes use of these changes.
Any feedback on this approach is welcome.
> output: Expose all of its internal state

- src/backend/renderer/gles2/mod.rs
We don't want `Renderer::clear` to merge with existing buffer contents, but the `Gles2Renderer` does just that.
We fail to notice it in most cases, because most compositors clear with an alpha value of 1. However clearing with any other alpha value will not yield the expected result, when blending is enabled. So instead we should disable blending, so that the framebuffer's color is replaced with the new clear_color.
> gles2: Don't blend on clear

- CHANGELOG.md
- anvil/src/input_handler.rs
- anvil/src/render.rs
- anvil/src/shell.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/desktop/layer.rs
- src/desktop/space/mod.rs
- src/desktop/space/output.rs
- src/wayland/output/mod.rs
- src/wayland/output/xdg.rs
- wlcs_anvil/src/main_loop.rs
based on #557
- The first commit introduces a new `Scale` type to represent different integer/fractional scaling combinations + xdg_output using it to calculate it's `logical_size`
- The second commit removes the `OutputState::render_scale` and replaces it with the new fractional_scale values from the Output's `Scale`.
> output: Track fractional scale

- src/wayland/output/mod.rs
`PartialEq` already uses `Arc::ptr_eq` anyway.
> output: impl Hash

- CHANGELOG.md
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/server_dnd_grab.rs
This PR fixes DnD behavior. It always sends a data_device leave event before releasing the dnd grab when the button is released.
> fix: send device leave event after button released

- src/backend/renderer/gles2/mod.rs
- src/desktop/space/mod.rs
This PR fixes some fractional scaling issues I have encountered during implementing crop & scale.
Additional it changes the default texture filtering to linear which shows better results in most cases.
> Fractional (output) scaling fixes

- anvil/src/shell.rs
This was almost nothing, but we don’t want to publicise that any longer.
> anvil: remove remnants of wl_shell

- src/utils/alive_tracker.rs
- src/utils/mod.rs
- src/wayland/compositor/handlers.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/handlers/surface/toplevel.rs
- src/wayland/shell/xdg/mod.rs
This introduces new IsAlive trait that we can use to implement `is_alive` check on any wayland object we want.  For now I implemented it for most common objects that users may want to alive check.
> 0.30: Introduce IsAlive trait

- anvil/src/shell.rs
- anvil/src/state.rs
- src/desktop/layer.rs
- src/desktop/space/mod.rs
- wlcs_anvil/src/main_loop.rs
Currently the `_from_surface` methods of the various desktop-helpers only match for toplevel-surfaces.
However it can be useful (although not used by anvil in any way) to retrieve a matching window/layer/etc from a subsurface as well. E.g. to figure out on which outputs a surface resides.
Currently there is no way to do that. This PR aims to solve that, by allowing `_from_surface` to work with sub-surfaces. Because this requires walking surface-trees and thus might be unnecessary overhead for a lot of simple operations, this utilizes the `WindowSurfaceType` as a new attribute to filter, which surfaces should be matched.
> space: Allow to retrieve window/layer from subsurface

- src/backend/renderer/mod.rs
Trivial change, waiting for CI to finish to see how many more cfg configurations need fixing.
> 0.30 gl: fix compile error without wayland_frontend

- examples/minimal.rs
- src/wayland/data_device/device.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
- src/wayland/data_device/seat_data.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/dmabuf/dispatch.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/xdg_activation/dispatch.rs
- src/wayland/xdg_activation/mod.rs
These are available when dispatching requests, may as well provide the display handle for convince.
> add missing display handle params in trait functions

- src/desktop/layer.rs
- src/desktop/mod.rs
- src/desktop/popup/mod.rs
- src/desktop/space/popup.rs
- src/desktop/window.rs
So while we have defined `RenderZIndex::Popups` and `RenderZIndex::PopupsOverlay`, we effectively don't use them, because the popups's RenderElements are not *rendered*. Instead they are only used for damage tracking, but popups are rendered with their parent.
Turns out this is not really helpful (e.g. [xdg-shell-wrapper](https://github.com/pop-os/xdg-shell-wrapper) cannot use `Window`, because `draw_window` draws the popups, which xdg-shell-wrapper instead handles by creating popups themselves).
So this PR introduces new popup-rendering helpers (which can be used to replace the old usecase)
and finally splits rendering of popups between it's parents and the actual popup RenderElement. This fixes the z-index we draw popups at!
> desktop: Split of popup rendering

- examples/compositor.rs
- examples/minimal.rs
- examples/seat.rs
- smallvil/src/state.rs
- smallvil/src/winit.rs
- src/wayland/compositor/mod.rs
- src/wayland/data_device/mod.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/output/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/decoration.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/shm/mod.rs
- src/wayland/xdg_activation/mod.rs
This does now require turbofish syntax for global creation. This makes global registration much more flexible.
> manage globals using DisplayHandle

- examples/minimal.rs
- smallvil/src/handlers/compositor.rs
- src/backend/egl/display.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/egl.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/utils.rs
- src/wayland/buffer/mod.rs
- src/wayland/dmabuf/dispatch.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/shm/handlers.rs
- src/wayland/shm/mod.rs
This simplifies the codebase and removes the need for a Buffer wrapper type that would need conversion all around compositor implementations.
> use multiple dispatch implementations for buffers

- src/backend/allocator/format.rs
- src/backend/allocator/mod.rs
Adds a bunch of data that is not implicitly available with DRM formats.
This data is generated with a macro that exposes some functions.
This provides the following data related to formats:
- bits per pixel
- opaque alternatives
- whether a format has an alpha channel, useful for graphics apis like Vulkan where there are no opaque formats (instead swizzling the alpha component).
Also some formats need an update drm-fourcc crate, I tried to update it but last time I tried it seemed to fail to find the headers (even on a system with the headers installed)?
This intentionally does not include other graphics api format conversions. Some formats defined in graphics apis may only work with specific endian values or may require extra data (like Vulkan with component swizzling).
Some tests are …
> Add DRM format tables

- src/wayland/xdg_activation/handlers.rs
Fixes protocol error starting `gtk4-demo`. I'm not sure if this could be handled better or if `destroy` should actually be doing anything.
> Allow `xdg_activation_token_v1::destroy` after token is constructed

- src/wayland/seat/keyboard/keymap_file.rs
- src/wayland/seat/keyboard/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer/mod.rs
Ver 6 was about touch events that we already have: https://github.com/wayland-project/wayland/commit/6a18a87727c64719c68168568b9ab1e4d7c2d9c1
Ver 7 is about sealing the keymap files:  https://github.com/wayland-project/wayland/commit/905c0a341ddf0a885811d19e2b79c65a3f1d210c
The Sealing could allow for some optimizations, but I'm not sure which OSes support that, so I just left the inefficient version where we create a file per client.
> Update WlSeat to version 7

- Cargo.toml
- Updates wayland-rs to beta.3 to fix egl-acceleration
- Updates winit to a git-dependency temporarily until the next version fixes redrawing on wayland
> 0.30 Fix dependencies

- anvil/src/render.rs
popups are no longer drawn as part of the window.
we have to explicitely draw them for full screen windows.
fixes: #615
> anvil: fix fullscreen window popups

- anvil/src/drawing.rs
- anvil/src/render.rs
- anvil/src/shell.rs
- anvil/src/winit.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/gles2/shaders.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/utils.rs
- src/backend/winit/mod.rs
- src/desktop/layer.rs
- src/desktop/popup/mod.rs
- src/desktop/space/element.rs
- src/desktop/space/layer.rs
- src/desktop/space/mod.rs
- src/desktop/space/output.rs
- src/desktop/space/popup.rs
- src/desktop/space/window.rs
- src/desktop/utils.rs
- src/desktop/window.rs
- src/utils/geometry.rs
- src/utils/mod.rs
- src/wayland/mod.rs
- src/wayland/viewporter/mod.rs
- wlcs_anvil/src/renderer.rs
- Add a two-dimensions `Scale`
Allows for different scales on x and y axis, which could be used for some special use-cases for outputs.
Preparation for compositor driven crop & scale
- Support for `wp_viewporter`
- Rounding physical coordinates to align with the physical pixel grid
~~(also implements the rounding described in [wp-fractional-scale-v1](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/143)~~
Rounding is done as the final step, `wp-fractional-scale-v1` will be integrated in a seperate PR
- Fixes for damage artifacts on some fractional scales
This could reduce the places where we round the physical coordinates~~
No, using physical reduces the places where we need to round and allows the `RenderElements` to
multipliy the scale with some factor without …
> Add support for viewporter

- src/backend/allocator/swapchain.rs
- src/backend/x11/surface.rs
Fixes a potential overflow inside the `Swapchain`, if the numbers of cycled slots is not consistent.
Currently if an allocated slot does not get used for a long time, it will overflow causing a panic.
Instead we should reset unused slots.
Fixes https://github.com/pop-os/cosmic-comp/issues/10
As far as I know this is not reproducable in anvil, but given cosmic-comp does a little more complex buffer management and I cannot see any obvious misuse of the api, this seems to be the correct fix. And securing the swapchain against an overflow is good practice anyway.
@PolyMeilex and @h1771t please test and confirm this fixes the problem on your systems.
> allocator: Fix overflow

- anvil/src/state.rs
- examples/minimal.rs
- smallvil/src/handlers/compositor.rs
- src/wayland/shell/xdg/decoration.rs
- src/wayland/shm/handlers.rs
- src/wayland/shm/mod.rs
Some fixes to the consistency of using the 0.30 branch.
Each commit stands for itself and can be dropped if controversial:
- ShmState is the only one using `AsRef` for referring to its state -> replaced by `ShmHandler`
- The `XdgDecorationManager` is the only state object not named `State` but after its protocol object -> replaced with `XdgDecorationState`
> 0.30: various consitency fixes

- Cargo.toml
- src/backend/session/libseat.rs
Depends on https://github.com/Smithay/calloop/pull/102
This makes the libseat session match the behaviour of the other sessions more closely by directly reflecting the active-state after creation instead of after it's first dispatch.
> session/libseat: process immediate events after creation

- anvil/src/udev.rs
- src/backend/libinput/mod.rs
- src/backend/x11/extension.rs
- src/xwayland/xserver.rs
- wlcs_anvil/src/main_loop.rs
- wlcs_anvil/src/renderer.rs
Another new Rust release. Another pull request to fix the clippy lints.
Apparently wlcs_anvil wasn't being run with clippy for some reason, so I fixed the clippy issues there.
> Fix new clippy 1.62 lints

- anvil/src/drawing.rs
- anvil/src/render.rs
- anvil/src/shell.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- examples/minimal.rs
- smallvil/src/handlers/compositor.rs
- smallvil/src/winit.rs
- src/backend/egl/display.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/egl.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/utils.rs
- src/desktop/layer.rs
- src/desktop/popup/mod.rs
- src/desktop/space/element.rs
- src/desktop/space/layer.rs
- src/desktop/space/mod.rs
- src/desktop/space/popup.rs
- src/desktop/space/window.rs
- src/desktop/window.rs
- wlcs_anvil/src/main_loop.rs
- Checks for 0x0-buffers, so we don't crash on invalid buffers
- Remove a broken egl-buffer check (confirmed doesn't crash when trying with an invalid buffer)
- As a consequence DisplayHandle is not needed for most of renderer-apis anymore (just like before 0.30), so lets remove it again.
> egl: Fix buffers

- anvil/src/shell.rs
- anvil/src/xwayland/mod.rs
- smallvil/src/grabs/move_grab.rs
- smallvil/src/grabs/resize_grab.rs
- smallvil/src/handlers/xdg_shell.rs
- src/desktop/space/element.rs
- src/desktop/space/mod.rs
- src/desktop/space/window.rs
- src/desktop/window.rs
- wlcs_anvil/src/main_loop.rs
Previously a window's z_index could be overridden by [`Window::override_z_index`], which worked fine for rendering, but broke input helpers such as [`Space::surface_under`], because windows could essentially re-order their relative position to other windows without updating the stack-order inside the spaces they were mapped to.
Instead this PR now makes a window's z_index a space-local variable (attached to the `WindowState`), that can be set when inserting a window.
After adding a window, the index-set will be sorted by the z-index to correctly reflect the positions. [`IndexSet::sort`] is guaranteed to be stable, so the implicit insertion order should not be influenced by this.
> space: Replace window-local z_index with space-local

- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/handlers.rs
- src/wayland/shell/xdg/handlers/surface.rs
Currently there is no event generated by the [zwlr_layer_surface_v1::get_popup](https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:request:get_popup) request.
This is an issue when trying to implement positioning logic for popup with layershell surfaces as parent.
On the [xdg_surface::get_popup](https://wayland.app/protocols/xdg-shell#xdg_surface:request:get_popup) call they don't have yet a parent, making it impossible to know, which location they should be positioned relative to.
On the first commit, it is already too late, given the xdg-shell protocol mandates that configure-events are only send at very specific times:
> For version 2 or older, the configure event for an xdg_popup is only ever sent once for the initial configuration. Starting with version …
> layer_shell: Add new_popup callback

- smallvil/src/handlers/compositor.rs
- smallvil/src/handlers/xdg_shell.rs
the initial xdg toplevel configure should be sent on the initial commit
Maybe we want to add a helper for that or at least expose `initial_configure_sent` on the `XdgToplevel`
to get rid of the `Mutex<XdgToplevelSurfaceRoleAttributes>`?
fixes #644
> smallvil: send initial configure on commit

- .github/workflows/ci.yml
- Cargo.toml
- examples/vulkan.rs
- src/backend/allocator/mod.rs
- src/backend/allocator/vulkan/format.rs
- src/backend/allocator/vulkan/mod.rs
- src/backend/mod.rs
- src/backend/vulkan/inner.rs
- src/backend/vulkan/mod.rs
- src/backend/vulkan/phd.rs
- src/backend/vulkan/version.rs
- src/reexports.rs
First is a thin lightweight wrapper around ash to get an Instance and PhysicalDevices. This helper is kept intentionally lightweight to prevent essentially replicating a crate like vulkano. Creation of a logical `Device` is intentionally not covered since extensions to `DeviceCreateInfo` and queue creation are hard to model in a public API. The Vulkan allocator and a future renderer are expected to initialize their own logical device(s) and queues.
The Vulkan allocator is modeled around the `Allocator` trait. Implementing memory import/export and dmabuf import could be done, but it involves much more complex lifetimes (since memory import/export requires copy commands, which means command execution and needing to delay destruction of images until command execution finishes). In the future …
> The Vulkan allocator

- src/desktop/space/mod.rs
I made a mistake on #658 swapping the compare order, because I though the order had to be inverse, but `Space::windows` is already returning a reverse iterator. The nearest elements are the last ones, not the first ones...
> fix: Don't invert z_index order on insert

- src/desktop/layer.rs
- src/desktop/space/mod.rs
- src/desktop/space/output.rs
- src/desktop/utils.rs
The idea of this commit is to make the `Space::outputs_for_window` function substantially cheaper. This solution has some trade-offs.
1. This uses the existing surface-list inside the `OutputState`, that gets updated on every `Space::refresh` anyway to track `output_enter` and `output_leave` events. This means the result of this function would now not be accurate any more, if no refresh happened between changes to the shell-state and this call. I would argue this is insignificant for most compositors as refreshes should happen frequently anyway.
2. Sorting the outputs was never guaranteed in the methods docs and was wrong to begin with, because it sorted by the smallest overlapping area first than the intended largest.
anvil makes use of this behaviour to select the output with the most …
> space: Use cached output surface list for outputs_for_window

- src/desktop/layer.rs
Compositors might try to avoid calling `LayerMap::arrange` to frequently as the re-calculation of zones is unnecessarily expensive, if the layer-surfaces themselves are not changing.
`LayerMap::cleanup` (which is far less expensive) will correctly get rid of old surfaces in that case, but because there is no `surface_unmapped` event, compositors can't easily figure out, if any surfaces got removed to trigger a re-arrange.
Lets fix this by doing it automatically for the compositor in cases where a layer_surface disconnected.
> desktop/layer: Automatically re-arrange on dead surfaces

- src/backend/libinput/mod.rs
libinput is currently spamming logs for every axis even, because smithay's libinput backend queries every axis. I am not sure, why libinput would call out this as a bug (0.0 as a return value is semantically equivalent to no scrolling, is it?), but we can mitigate this annoying log message by don't doing that...
> libinput: Don't query unset axis

- CHANGELOG.md
- src/backend/egl/context.rs
- src/backend/egl/display.rs
- src/backend/egl/surface.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/multigpu/egl.rs
- src/backend/winit/mod.rs
This makes some aspects of the EGL backend accessible from outside Smithay that may useful. Some small changes are also made like renaming `get_extensions` to `extensions`
> egl: expose pub(crate) fields as public functions

- src/wayland/data_device/seat_data.rs
Previously, copy-paste into Firefox was broken if text had previously been copied within Firefox, since it seemed to assume its source was still current given it had not been cancelled. This fixes that.
There are still other issues with copy and paste in Firefox.
> data_device: Send `cancelled()` to old source in `set_selection`

- anvil/src/shell.rs
- smallvil/src/grabs/move_grab.rs
- smallvil/src/grabs/resize_grab.rs
- smallvil/src/input.rs
- smallvil/src/state.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/server_dnd_grab.rs
This is basically https://github.com/Smithay/smithay/pull/490/ for 0.30...
It reintroduces `pointer.motion` calls previously missing from the grabs and also makes sure to take focus away, where appropriate.
The second commit removes `state.pointer_location` from smallvil so we catch this problem more easily in the future.
I would have given anvil the same treatment, but the cursor state and location is here much more intertwined with the rendering code and tablet code. The latter probably requires some more changes to tablet_tool at first to make it internally track its location as well.
> Fix grab motion events

- anvil/src/x11.rs
Anvil will segfault in the X11 backend on shutdown, probably a regression during the 0.30 migration. This is a workaround for #447 until further work is done to fix it.
> anvil: fix x11 drop order issues

- src/backend/allocator/vulkan/mod.rs
Per the Vulkan specification, if an image has the COLOR_ATTACHMENT usage, the width and height of the image must be less than or equal to maxFramebufferWidth and maxFramebufferHeight respectively.
See VUID-VkImageCreateInfo-usage-00964 and VUID-VkImageCreateInfo-usage-00965 for more information.
> vulkan-alloc: ensure images with COLOR_ATTACHMENT usage are valid

- src/backend/drm/device/atomic.rs
- src/backend/drm/surface/atomic.rs
Apparently the drm-interface is allowed to dynamically add connectors during runtime, for example to represent daisy-chained display port connections and a few other special cases.
smithay currently does not handle this correctly in the atomic backend, as it assumes a static set of resources to cache their properties.
The first commit fixes the enumeration of properties for framebuffers. They are created by processes and inherently dynamic in nature. It was luckily never used in the code, but that piece of code makes no sense and shouldn't exist. Properties of framebuffers need to be queried from the drm-interface, when they are needed and should not be cached (at least not globally).
The second commit mostly shifts methods around to make them more accessible, the big change is that …
> drm/atomic: Re-evaluate properties for newly added connectors

- anvil/src/shell.rs
It's possible that a surface wants to be maximized before the window has actually been mapped yet, and therefore `outputs_for_window` returns an empty `Vec`. In that case, it's fine to use the first output available, instead.
I've been able to actually produce the crash in Anvil using Firefox with `MOZ_ENABLE_WAYLAND=1` set in the environment, using a fresh Firefox profile.
For reference, here is what Weston does in the same case:
https://gitlab.freedesktop.org/wayland/weston/-/blob/d615abdffdb0b3f69c937c577cbd3855ed382a74/desktop-shell/shell.c#L2302
> anvil: Fix crash in `maximize_request`

- src/backend/vulkan/mod.rs
- src/backend/vulkan/phd.rs
The Vulkan1X types are not ideal for our level of abstraction nor too idomatic. Smithay intends to support higher versions of Vulkan like a superset of existing functionality. However the Vulkan1X types cannot be chained with their individual parts without validation errors. There is also the fact that these types are not available until Vulkan 1.2, and the Vulkan11 structures are actually provided in Vulkan 1.2, not Vulkan 1.1. Therefore for the sake of cleaning up the codebase, the Vulkan1X types now need to be obtained some other way if desired.
> vulkan: remove Vulkan1X features/properties from PhysicalDevice

- examples/vulkan.rs
- src/backend/allocator/vulkan/mod.rs
Empty image usage flags are not allowed in Vulkan. This pull request changes VulkanAllocator to panic if it's default usage flags are empty.
VulkanAllocator::is_format_supported and VulkanAllocator::create_buffer_with_usage now return false and fail respectively if the usage flags are empty.
> vulkan-alloc: fix validation error related to empty usage flags

- src/backend/renderer/multigpu/mod.rs
Firefox strikes at it again...
First three commits fix code in the multigpu renderer, mostly related to usage of early_import.
- 38f3cf5480df7fc367d691642c4e0735f9bf6ca9 Adds a new check to make sure early_import does nothing if there was no new buffer. Otherwise it might clear the *internal* textures and we have nothing to render, because the `on_commit_buffer_handler` still has the empty `MultiTexture` and won't call `import_surface_tree`.
- 7e6473f1ca892586974ed1a522b95f00888fd37b Makes the MultiTexture reset it's internal textures, when the size changes. Otherwise the multigpu renderer could end up trying to update a texture with different dimensions, resulting in rendering errors
- 26454a0cccdd21bae9c52f5e356fd111b9cbdaf9 Clears the mappings on consequent imports (before they are …
> MultiGPU fixes round three

- .github/workflows/ci.yml
Gets rid of our manual libseat install
> CI: Use ubuntu 22.04 jammy

- Cargo.toml
This resolves issues when running smithay with winit
backend on Wayland.
> Bump winit to 0.27.1

- src/backend/egl/context.rs
- src/backend/egl/display.rs
- src/backend/egl/error.rs
Confirmed working using this example:
```rs
struct EGLRawHandles {
display: *const c_void,
config: *const c_void,
context: *const c_void,
}
```
```rs
let mut renderer = unsafe {
Gles2Renderer::new(
EGLContext::from_raw(
egl_raw_handles.display,
egl_raw_handles.config,
egl_raw_handles.context,
log.clone(),
)?,
log.clone(),
)?
};
let smithay_tex_image =
image::io::Reader::with_format(std::io::Cursor::new(STARDUST_PNG), image::ImageFormat::Png)
.decode()
.unwrap();
let smithay_tex = renderer
.import_memory(
&smithay_tex_image.to_rgba8(),
(
smithay_tex_image.width() as i32,
smithay_tex_image.height() as i32,
)
.into(),
false,
)
.unwrap();
```
https://github.com/StardustXR/stardust-assets/blob/main/icon.png
(The gamma issue is due to the renderer I am using, …
> egl: Add EGLDisplay::from_raw and EGLContext::from_raw

- src/backend/renderer/utils.rs
This method improves efficiency for compositors that do not use smithay's window rendering at all and simply want a texture, for example AR/VR compositors where every surface must be displayed via a texture on a 3D model.
@cmeissl made the code for this commit so they know more about it than I do.
> renderer: add RendererSurfaceStates texture function

- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
When the output is rotated by 90°/270° using a transform in the
`Gles2Renderer::render` function, the resulting matrix would cause the
buffer to be stretched along one and compressed along the other axis.
Since width and height are swapped when rotating by 90 degrees
(counter-)clockwise, the resulting output matrix needs to adjust for
this difference.
> Update render matrix for rotated outputs

- src/backend/drm/surface/atomic.rs
`clear_plane` always uses the primary plane instead of the passed plane
> drm: clear the correct plane

- src/backend/drm/surface/atomic.rs
`DrmSurface` would deadlock on drop if additional planes have been used
> drm: prevent deadlock on drop

- src/wayland/shell/kde/decoration.rs
- src/wayland/shell/kde/handlers.rs
- src/wayland/shell/kde/mod.rs
- src/wayland/shell/mod.rs
This should add a very rough implementation of the server decoration protocol. I've tested it and it seems to work as far as I can tell. My priority was mostly to implement this for myself to force server-side decorations for GTK, this PR is more of an accident.
It's probably somewhat rough around the edges, especially since I'm not particularly familiar with all the wrappers like `Global`/`Main`/`Resource` etc, so please let me know if you have any suggestions for improvements.
> Add KDE server-decoration support

- anvil/src/drawing.rs
- anvil/src/shell.rs
- smallvil/src/handlers/xdg_shell.rs
- src/desktop/popup/manager.rs
- src/desktop/popup/mod.rs
- src/input/pointer/cursor_image.rs
- src/input/pointer/mod.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/handlers/surface/toplevel.rs
- src/wayland/shell/xdg/mod.rs
Replaces cases of `data_map.get::<Mutex<Type>>()` with type alias `.get::<NameSurfaceData>()`
So it should be a lot easier to figure out what can be extracted from surface states
> Remove magic type signatures in favor of public type aliases 

- anvil/src/input_handler.rs
- examples/minimal.rs
- examples/seat.rs
- smallvil/src/input.rs
- src/input/keyboard/mod.rs
- src/input/mod.rs
The recent seat handling changes made in 78ebaa6 have added some
friction to the way input and specifically the keyboard is handled. This
patch aims at making it easier to migrate to the new design.
To allow for easy access to the compositor state, the state is now
passed to the closure in the keyboard's `input` function. While this
makes sense as the simplest solution to this problem, a possible
alternative would be to move this function to the seat handler in the
future.
> Fix new seat module ergonomics

- src/backend/allocator/vulkan/mod.rs
- src/backend/vulkan/mod.rs
This function is used in the vulkan allocator and the WIP vulkan renderer, so it should be exposed on PhysicalDevice.
> vulkan: add PhysicalDevice::get_format_properties

- src/desktop/space/element.rs
- src/desktop/space/mod.rs
By mistake the RenderElements of the custom elements had to be borrowed, which in reality didn't work out (see e.g. https://github.com/Smithay/smithay/pull/726).
So now we *wrap* it and get rid of the lifetime instead.
@cmeissl Please review
> space: Fix custom elements

- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/handlers/surface/popup.rs
- src/wayland/shell/xdg/handlers/surface/toplevel.rs
- src/wayland/shell/xdg/mod.rs
This adds `destroyed` methods for handling the death of XDG
toplevel, XDG popup and layer shell surfaces.
Providing these methods for the handlers directly allows for easy state
access and should simplify the likely different handling for the
individual shell surface types.
> Add destroy hooks to XDG/Layer shell handlers

- anvil/src/input_handler.rs
- anvil/src/render.rs
- anvil/src/shell.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- smallvil/src/winit.rs
- src/desktop/layer.rs
- src/desktop/space/element.rs
- src/desktop/space/layer.rs
- src/desktop/space/mod.rs
- src/desktop/space/output.rs
- src/desktop/space/popup.rs
- src/desktop/space/window.rs
- src/desktop/utils.rs
- src/desktop/window.rs
- src/lib.rs
- src/output.rs
- src/wayland/output/mod.rs
- wlcs_anvil/src/main_loop.rs
Splits the wayland::output module into wayland specific parts and a new toplevel output-module, that can be used without any wayland functionality.
After my recent changes to the input system, I don't expect this change to be very controversial, but here are some motivations for it anyway.
The `Output` struct has got a second use-case apart from advertising to wayland_clients with our inclusion of the desktop-abstractions as a rendering helper. It represents a view into the compositors grid, that shall be rendered.
With the upcoming generic-space rework, there is no reason for the `Space` and it's rendering helpers for damage-tracking to depend on the `wayland_frontend` feature anymore. But because the rendering depends on the `Output` as a helper , there needs to be a way to use the …
> output: Split wayland::output

- anvil/src/udev.rs
- anvil/src/x11.rs
- src/backend/egl/display.rs
- src/backend/renderer/multigpu/egl.rs
- src/backend/winit/mod.rs
- src/backend/x11/mod.rs
`EGLDisplay::new` raised some safety concerns, it happened a few times that the provided `EGLNativeDisplay` has been dropped before the created `EGLDisplay`. Dropping the `EGLNativeDisplay` before the  `EGLDisplay` most likely ends in a segfault at some point. To better express that this PR makes `EGLDisplay::new` unsafe and documents the safety requirements.
> egl: make EGLDisplay::new unsafe

- src/wayland/primary_selection/mod.rs
I noticed when using cosmic-comp that this unreachable!() arm would be triggered sometimes when closing a window. I assume that handling Destroy will help prevent that from happening.
> fix: add arm for primary_device_manager::Request::Destroy

- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/desktop/space/element/mod.rs
- src/desktop/space/element/wayland.rs
- src/desktop/space/mod.rs
- src/desktop/space/wayland/layer.rs
- src/desktop/space/wayland/window.rs
- src/desktop/wayland/window.rs
- wlcs_anvil/src/main_loop.rs
@cmeissl This is an attempt to handle all edge-cases around output_enter/leave events with the new generic space.
- `SurfaceTree` is not really mapped by anything, remove `SpaceElement`-impl and just provide `AsRenderElements` (TODO: Implement it directly for `WlSurface`?)
- `LayerSurface` is not mapped, but belongs to an `Output`, so also remove its `SpaceElement`-implementation
- `Window`s consist of multiple surfaces and can be on multiple outputs simultaniously. This means some surfaces might not be inside one outputs bounds, we thus need to provide `output_enter` and `refresh` with positioning information to allow for multiplexing this call correctly
- Additionally surfaces can be destroyed and created at any point, so `refresh` needs to recalculate outputs.
Note: The code for …
> desktop: Fix handling for output_enter/leave events

- src/input/keyboard/mod.rs
- src/wayland/seat/keyboard.rs
In the previous implementation, pressed keys were stored in a list. This meant that each element in the list was not guaranteed to be unique, and if you received several key press events, the list would quickly expand in size. If the list became longer than 1024 elements (4096 bytes), sending the key map to any client would result in an error and the connection to the client being severed.
Switching to a set has the advantage of solving this issue as well as potentially speeding up the processing of any key release events, since the whole vec no longer has to be traversed.
> Replace Vec for tracking of pressed keys with HashSet

- src/backend/allocator/dmabuf.rs
- src/backend/allocator/gbm.rs
- src/backend/allocator/vulkan/mod.rs
- src/backend/egl/display.rs
- src/wayland/dmabuf/mod.rs
Converting an arbitrary `RawFd` to an `OwnedFd` in a safe function is unsound. This provides a more correct API.
> Make `DmabufBuilder::add_plane()` take an `OwnedFd`

- src/desktop/layer.rs
When calculating `layer_geometry` the user expects to get geometry relative to the origin of the layer_surface.
Popups extending negatively from the surface might shift that, if the calculation happens based on `bbox_with_popups()` (e.g. for Bottom anchored layer_shell surfaces).
This can e.g. break input in interesting ways as it is not easily possible to calculate surface-relative coordinates this way.
Additionally change layer_under to still use the bbox_with_popups to catch cursors over layer_surface popups correctly.
We have not previously observed this issue with anvil, because anvil does not constrain xdg_popups correctly.
This PR fixes the buggy behaviour in cosmic-comp without breaking any existing functionality in anvil, but it does not make the bug reproducable or testable in …
> desktop/layer: Don't calculate geometry including popups

- Cargo.toml
- build.rs
- src/backend/allocator/gbm.rs
- test_gbm_bo_get_fd_for_plane.c
When available or forced with feature backend_gbm_has_fd_for_plane use fd_for_plane which allows the use of multi planar formats which expose multiple planes with different fds.
> detect gbm_bo_get_fd_for_plane

- src/desktop/layer.rs
- src/desktop/space/element.rs
- src/output.rs
- src/wayland/output/handlers.rs
- src/wayland/output/mod.rs
We have a couple of hack surrounding the internal use of `Output` inside smithay to make sure resources are getting cleaned up properly.
One of those is creating *weak output references*, as seen in the [`LayerMap`] and additionally (with a very hack hash-implementation) in #727.
Additionally I have found a bunch of use-cases for using `HashMap<Output, _>` in cosmic-comp, which would also be better served by a `WeakOutput` type.
So lets add that.
> output: Add WeakOutput type

- src/desktop/space/element/mod.rs
- src/desktop/space/mod.rs
- src/wayland/shell/wlr_layer/types.rs
@cmeissl Ping.
Also added some more comments explaining the order of elements rendered for each of the different functions.
> space: Fixup multiple rendered layer_surfaces when using multiple spaces

- .github/workflows/ci.yml
- Cargo.toml
- anvil/src/udev.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/glow.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/egl.rs
Adds a new `GlowRenderer` that wraps a `Gles2Renderer` and additionally exposes a `glow::Context` on top of the same GL context as the underlying renderer.
Can also be used in conjunction with the `MultiRenderer` and is purely optional.
> renderer: Add glow integration

- src/desktop/space/mod.rs
`swap_remove` does not only remove the element but also moves the last element to that position
> desktop: fix stacking order on raise

- src/desktop/space/mod.rs
the bbox does not include the location of the layer surface, we have to use `layer_geometry` to find the location just like in the input handler
> desktop: fix layer render location

- anvil/src/shell.rs
- src/desktop/wayland/layer.rs
the initial configure has to be sent in response to the initial commit. sending an implicit configure when mapping/arranging a layer leads to wrong sizes.
> desktop: fix layer shell initial configure

- .github/workflows/ci.yml
- Cargo.toml
- src/desktop/wayland/layer.rs
- wlcs_anvil/Cargo.toml
~~Draft because this requires a new wayland-server release to behave correctly. (`Weak::upgrade` may succeed for dead objects on 0.30-beta.10)~~
Also updates to ~~beta.11~~ beta.12
> desktop/layer: Don't require dh for cleanup

- src/input/keyboard/mod.rs
- src/input/pointer/mod.rs
Now that the `Seat` is generic over focused elements, we have lost the option to easily receive the currently focused element.
We cannot return a reference, as both fields are behind `Mutex`. When this was still just a `WlSurface`, we could just clone it.
So lets re-introduce this option with a little trait bound.
> input: Add a way to retrieve current focus

- anvil/src/focus.rs
- anvil/src/input_handler.rs
- src/desktop/wayland/popup/grab.rs
- src/desktop/wayland/popup/manager.rs
- src/desktop/wayland/window.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/mod.rs
Drop the reference from `WaylandFocus::wl_surface`.
Forcing a reference here, makes it impossible to wrap the underlying object in a `Rc<RefCell<_>>` or `Arc<Mutex<_>>` internally, as you cannot return references of the elements contained.
This is particularly desirable, when storing multiple `Window`s in a collection, e.g. to implement a stacked window layout. Anything resembling a window is usually clonable and internally refcounted. If you wanted to ref-count such a collection type, you would end up in the situation laid out above.
`WlSurface`s are cheap handles, so lets get around that, by just cloning them.
> input/wayland: Return owned surface from WaylandFocus

- anvil/src/winit.rs
- build.rs
- src/backend/egl/display.rs
- src/backend/egl/native.rs
- src/backend/egl/surface.rs
- src/backend/winit/mod.rs
The old implementation was arguably buggy (checking for either extension, but always calling EXT).
This might be a little too safe, but should work with every stupid driver out there.
Additionally this moves the buffer age query after `backend.bind()`. Otherwise the surface might not be current, resulting in another error and wrong age value.
(Fixes damage tracking issues with the winit-backend on nvidia's proprietary driver.)
> Allow usage of KHR or EXT variants for eglSwapBuffersWithDamage

- .github/workflows/ci.yml
At the moment the feature labels are only generated when publishing to crates.io
> enable doc_auto_cfg when generating docs for master branch

- src/input/keyboard/keymap_file.rs
- src/input/keyboard/mod.rs
- src/input/keyboard/modifiers_state.rs
- src/utils/mod.rs
- src/utils/sealed_file.rs
- src/wayland/input_method/input_method_handle.rs
- src/wayland/seat/keyboard.rs
This is needed so Stardust can accept in keymaps, and I figured cleaning up the APIs would be nicer too since this is partially public.
> keyboard: refactor to improve keymapfile api and sealedfile api

- Cargo.toml
- src/backend/renderer/glow.rs
Little oversight writing the glow renderer. (Why was use_system_lib not added to test_all_features? :thinking: )
> Fix compiling glow renderer with use_system_lib

- src/input/keyboard/modifiers_state.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/seat/keyboard.rs
From xkb's docs, this should normally be used. So unless there's a specific reason for Smithay to do otherwise, this is how it should get the layout.
> input: Use xkb `STATE_LAYOUT_EFFECTIVE` instead of `STATE_LAYOUT_LOCKED`

- src/input/pointer/mod.rs
- src/wayland/seat/pointer.rs
Currently all values of `AxisFrame` are private, making it completely useless if passed for [`PointerTarget::axis`](https://smithay.github.io/smithay/smithay/input/pointer/trait.PointerTarget.html#tymethod.axis), when implementing a new target out of tree.
This PR fixes that. (And also includes a small bugfix to properly accumulate multiple value calls, as the docs say.)
> input: Expose `AxisFrame` values

- src/backend/winit/mod.rs
This problem only becomes apparent, if you bind different render-targets in between (e.g. to render to a texture), which anvil never does...
> winit: Fix re-binding on nvidia

- src/backend/renderer/damage.rs
- src/backend/renderer/element/memory.rs
- src/backend/renderer/element/texture.rs
cc @cmeissl 
Allows errors to propage from inside the `RenderContext::draw` call.
> element: Allow errors to escape from  `RenderContext::draw`

- Cargo.toml
- anvil/src/state.rs
- examples/minimal.rs
- smallvil/src/state.rs
- src/backend/allocator/dmabuf.rs
- src/backend/allocator/gbm.rs
- src/backend/allocator/vulkan/mod.rs
- src/backend/drm/node/mod.rs
- src/backend/egl/display.rs
- src/backend/x11/buffer.rs
- src/input/keyboard/keymap_file.rs
- src/reexports.rs
- src/utils/sealed_file.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/mod.rs
- src/wayland/data_device/seat_data.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/primary_selection/mod.rs
- src/wayland/primary_selection/seat_data.rs
- src/wayland/shm/handlers.rs
- src/wayland/shm/pool.rs
- src/wayland/virtual_keyboard/virtual_keyboard_handle.rs
Since Smithay now requires Rust 1.65.0, and io-lifetimes reexports these types from std on recent Rust versions, this dependency is redundant.
> Remove `io-lifetimes` dependency

- src/backend/renderer/gles2/mod.rs
eglCreateImage expects the attributes to be of type EGLAttrib which is platform dependent using EGLEnum types will 
populate an array with the wrong type which causes a segfault when calculating the attrib list len in the mesa egl code
> renderer: fix export_texture

- src/utils/clock.rs
this aligns the tv_nsec type with the impl in libc
fixes an issue with cross compiling to armv7
> utils: clock tv_nsec uses a platform dependant type

- Cargo.toml
A new version of ash was released with the stuff we need now.
> update ash to 0.37.1

- src/wayland/shell/xdg/handlers/surface/toplevel.rs
This fixes an issue with the `XdgShellHandler::toplevel_destroyed` method where it wouldn't get fired when a toplevel surface is destroyed.
This was caused by the destroyed toplevel surface getting removed from the tracked toplevel surfaces before looking it up to dispatch the handler.
> Fix toplevel death not calling XDG handler

- .github/workflows/ci.yml
- src/backend/renderer/element/surface.rs
the scaling for opaque regions has to follow the same rules as the geometry or otherwise we end up with
a mismatch which could result in rendering artifacts
> renderer: fix wayland surface opaque region scale

- Cargo.toml
This sets the minimum supported Rust version to 1.65.0 in Smithay's manifest, which helps with troubleshooting downstream when attempting to build Smithay with an outdated compiler.
Especially since the MSRV is far above the introduction of the `rust-version` field anyway, it should not come with any significant drawbacks besides the potential maintenance overhead.
> Set MSRV in Cargo manifest

- src/backend/egl/context.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/glow.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/winit/mod.rs
Adds a new trait `Blit` that can be used to do copies between framebuffers.
These are usually more performant, than exporting the source framebuffer and rendering the resulting texture to the target framebuffer, if supported.
> renderer: Add `Blit`-trait and implementations

- smallvil/src/input.rs
In Smallvil windows only get deactivated when pressing on the background and not when pressing on a different window. This PR fixes this by first removing the redundant `window.set_activated(true);` and looping through every window to run `.configure` so the necessary windows get deactivated/activated.
> smallvil: fix bad handling of the active window state

- src/wayland/text_input/text_input_handle.rs
This fixes an issue with the text_input/input_method protocols where the application requesting IME wouldn't notify the IME client about its death, keeping the IME client open after the application was closed.
With this patch whenever the `text_input` object is destroyed, the `deactivate` event is automatically emitted and committed ensuring the IME client is properly updated.
Closes #835.
> Fix IME not closing on application exit

- anvil/src/input_handler.rs
- src/backend/renderer/damage.rs
This fixes the damage intersection in the dtr for rotated outputs and introduces a new keyboard shortcut in anvil
to rotate the current output. Pressing `MOD + SHIFT + R` will rotate the output clockwise.
> fix dtr output transform

- .github/workflows/ci.yml
- Cargo.toml
- anvil/src/shell.rs
- anvil/src/state.rs
- src/desktop/wayland/utils.rs
- src/wayland/fractional_scale/mod.rs
- src/wayland/mod.rs
This PR add support for `wp_fractional_scale`, rounding should be good for toplevel surfaces.
The rounding for subsurface position and size is explicitely undefined in the spec, so it should be
fine for now as is I guess.
Testing done with `single-surface` from [updated test-clients](https://gitlab.freedesktop.org/cmeissl/fractional-scaling/-/tree/fix/update_to_released_protocol)
~~depends on [wayland-rs#590](https://github.com/Smithay/wayland-rs/pull/590)~~ merged
> Support fractional scale

- src/backend/allocator/dumb.rs
- src/backend/allocator/gbm.rs
- src/backend/allocator/mod.rs
- src/backend/allocator/swapchain.rs
- src/backend/allocator/vulkan/mod.rs
- src/backend/drm/surface/gbm.rs
- src/backend/renderer/multigpu/egl.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/x11/mod.rs
- src/backend/x11/surface.rs
Latest nvidia driver can somehow import the `Gles2Renderbuffer` on my system, which has an `Invalid`-modifier and is therefore garbage for the nvidia gpu as it is tiled.
So lets explicitly check for supported formats.
- Also includes commits from #841.
- Contains commit to move the generic buffer type of the `Allocator` trait into an associated generic type. Simplifies code all over the place.
Additionally prepares for more sensible gpu-copies in the future:
- Fixes missing cleanup of `GpuManager::dma_source`
- Caches offscreen-buffer
- Attempts to import the offscreen-buffer on the target gpu **on creation** (instead of after rendering, which is expected to fail in most cases)
- Caches resulting texture with the offscreen buffer
In the future we can hopefully do what #842 sets out to do …
> multigpu: Fix broken gpu-copy

- anvil/src/udev.rs
- anvil/src/x11.rs
- src/backend/allocator/dumb.rs
- src/backend/drm/device/atomic.rs
- src/backend/drm/device/fd.rs
- src/backend/drm/device/legacy.rs
- src/backend/drm/device/mod.rs
- src/backend/drm/mod.rs
- src/backend/drm/session.rs
- src/backend/drm/surface/atomic.rs
- src/backend/drm/surface/gbm.rs
- src/backend/drm/surface/legacy.rs
- src/backend/drm/surface/mod.rs
- src/backend/egl/device.rs
- src/backend/egl/display.rs
- src/backend/egl/native.rs
- src/backend/renderer/multigpu/egl.rs
- src/backend/winit/mod.rs
- src/backend/x11/mod.rs
- src/utils/fd.rs
- src/utils/mod.rs
This PR consists of two commits, that should be reviewed independently:
- 1a2c6b2 - Adds a new utility type `DeviceFd`, which is essentially a ref-counted `OwnedFd`. It also adds a `DrmDeviceFd` based on that and gets rid of most the generics in the `backend/drm`-module in the process.
- 5ae9412 - Tries to address the unsafety of the lifetime of `EGLDisplay`-objects, which are bound to their underlying object. The big issue here was the `GbmDevice`, which is only clonable, if they underlying file-type was clonable. And we didn't want to clone a raw file descriptor, but we can easily clone a ref-counted one. So now we can simply make the `EGLDisplay` take ownership of the native type.
> Ref counted FD

- src/backend/allocator/gbm.rs
the recent IO safety work revealed a bug
in GbmBuffer::export when the system does
not support gbm_bo_get_fd_for_plane.
Before the IO safety work the same fd was
used for multiple planes (this is problematic
because each plane takes ownership of the fd).
Practically this should not have happened as
the legacy version only supports bo with a single
plane.
The latests gbm release made this kind of
error impossible by directly returning an OwnedFd, but we missed it in smithay because of conditional compilation.
fixes #854
> gbm: export fd per plane

- CHANGELOG.md
- src/wayland/output/mod.rs
- src/wayland/output/xdg.rs
This fixes an issue where the reported logical size of the xdg_output implementation would incorrectly report the untransformed logical size.
Closes #857.
> Fix xdg_output's logical size with transforms

- src/backend/drm/device/fd.rs
when a privileged `DrmDeviceFd` is cloned and dropped it also releases the master lock potential leaving the still exiting fds in a bad state
> drm: fix early master lock release

- build.rs
- src/backend/egl/native.rs
ChromeOS uses [minigbm](https://chromium.googlesource.com/chromiumos/platform/minigbm/) instead of GBM. As part of this, the EGL_MESA_platform_gbm is unavailable. To allow Smithay to work on ChromeOS, enable a minigbm flag.
> egl: Add support for surfaceless

- anvil/src/shell/mod.rs
- src/utils/x11rb.rs
- src/xwayland/xwm/mod.rs
The current mechanism by which x11 window ids and their corresponding wl_surfaces are matched, may inject a `LATE_SURFACE_ID` client message similar to the original `WL_SURFACE_ID` message.
The problem with injecting this message is, that to do that it utilizes the same `SyncSender`, that is internally used by the `X11Source`. Given that this sender is *sync* and limited to 5 in-flight messages, queuing up additional messages from the same thread, that runs the calloop event loop and receives these messages may cause a deadlock. This can often be encountered when multiple windows are spawned by a client at the same time.
Instead of making the channel unbound this PR avoids the problem by changing the mechanism all together. Instead of injecting a message, the xwm state is accessed by an …
> xwm: replace LATE_SURFACE_ID

- .github/workflows/ci.yml
- anvil/src/focus.rs
- anvil/src/input_handler.rs
- anvil/src/shell/element.rs
- anvil/src/shell/grabs.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- smallvil/src/grabs/move_grab.rs
- smallvil/src/grabs/resize_grab.rs
- smallvil/src/input.rs
- src/backend/input/mod.rs
- src/backend/libinput/mod.rs
- src/backend/libinput/tablet.rs
- src/backend/winit/input.rs
- src/backend/winit/mod.rs
- src/backend/x11/input.rs
- src/desktop/wayland/layer.rs
- src/desktop/wayland/popup/grab.rs
- src/desktop/wayland/window.rs
- src/input/mod.rs
- src/input/pointer/grab.rs
- src/input/pointer/mod.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/mod.rs
- src/wayland/relative_pointer.rs
- src/wayland/seat/pointer.rs
- src/xwayland/xwm/surface.rs
- wlcs_anvil/src/main_loop.rs
I wonder if any of this could be simpler and less redundant...
Needs testing and probably some corrections.
> Relative pointer protocol

- src/wayland/compositor/mod.rs
- src/wayland/compositor/tree.rs
Every other shell does this, it just happens that subsurfaces were forgotten
> expose subsurface role

- src/xwayland/xwm/mod.rs
- Make sure new geometry of an override redirect window is represented in its internal state.
- Don't spam clients with new stacking lists, if nothing actually changed
> xwm: More fixes

- anvil/src/input_handler.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/xwayland/x11_sockets.rs
- src/xwayland/xserver.rs
Modifies the `XWayland::start` function in various ways, best reviewed commit-by-commit.
- [xserver: Allow user provided env vars](https://github.com/Smithay/smithay/commit/4ea4e0277f361ea8bd78bab4e5a96484322b4111) - Self-explanatory
- [xserver: Allow initialization of user_data for XWaylandClient](https://github.com/Smithay/smithay/commit/a100db722c7e073fc966dba78b2b9b62b907a450)  - This is necessary to base any global filters for Xwayland on a specific Xwayland instance.
- [xserver: Don't mutate environment](https://github.com/Smithay/smithay/commit/15a3598e0e497a4bfbd3a354963738c092937970) - Mutating the environment in multi-threaded programs is unsafe in some unix systems. Additionally this doesn't work, if downstream is spawning multiple Xwayland instances. So let downstream set the …
> xwayland: More versatile xwayland launching

- src/wayland/presentation/mod.rs
The `wp_presentation` documentation still contained some documentation mentioning viewporter, however the two are unrelated. This was likely a copy-paste mistake.
> Fix wp_presentation documentation

- src/input/keyboard/mod.rs
- src/input/mod.rs
Supersedes #798 and adds some more functions to inspect the current state of a seat and the keyboard handle.
Changes `with_pressed_keysyms` to take an `FnOnce`, which will take a `Vec<KeysymHandle>` and passes on it's return value.
> input: More introspection

- CHANGELOG.md
- Cargo.toml
- src/backend/input/mod.rs
- src/backend/libinput/mod.rs
- src/backend/winit/input.rs
- src/backend/x11/input.rs
This just defines the traits and associated types. It still needs an implementation for libinput (which is straightforward). And then to be useful an implementation of the `zwp_pointer_gestures_v1` protocol is also needed.
This seems to be consistent with how other event types are handled, but seems a little verbose. Would it be better to not have 10 new traits and 8 new associated types?
The `begin` events are all the same, as are the `end` events. `update` exists only for swipe and pinch, and has additional fields for pinch. Would it be sensible to reduce the 6 begin/end associated types to 2?
> backend: Gesture events

- anvil/src/shell/x11.rs
this disables ssd for fullscreen X11 windows which is important for supporting direct scan-out on the primary plane
> anvil: disable ssd for X11 fullscreen windows

- src/input/mod.rs
- src/wayland/seat/mod.rs
This fixes a reference cycle that prevented the resources associated with `Seat` to not be dropped (notably the memfd of the keymap).
Also needs https://github.com/Smithay/wayland-rs/pull/602 for a complete fix the of leak.
> input: store known seats as Weak<WlSeat>

- Cargo.toml
This won't pull wayland when there's no wayland feature enabled.
> chore: fix wayland-protocols-* being not optional

- src/desktop/space/mod.rs
`Iterator::partition()` returns a pair, all of the elements for which it returned true, and all of the elements for which it returned false.
> Fix partitions in space::space_render_elements.

- src/backend/drm/compositor/mod.rs
- src/backend/renderer/damage.rs
The transform of an output is specified in the rotation that needs to be applied to a surface for rendering. This is the exact inverse of the transform that needs to be applied to the renderer itself.
This patch inverts the transform stored on the output's mode to ensure the rendering transform correctly specifies the inverse of the surface transform.
---
If there's any other renderer/compositors, please let me know and I'll add this line there too. This was tested on my phone and not a desktop monitor.
> Fix render output transforms

- src/backend/drm/node/constants.rs
- src/backend/drm/node/mod.rs
- src/utils/clock.rs
With this I'm able to start Anvil, if I disable `xwayland`. (`UnixAddr::new_abstract` is Linux-specific.)
Handling drm device nodes is really a mess regardless of OS... and is also a mess in `libdrm`.
> Fixes for building on FreeBSD

- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/wayland/shm/mod.rs
- src/wayland/shm/pool.rs
- wlcs_anvil/src/renderer.rs
Creating a slice into shared memory is problematic, since this is considered undefined behavior if the client mutates the memory. This is especially a problem since it was creating a slice for the whole pool, as even a correctly behaving client may mutate another buffer in the same pool.
We don't want to trust clients not to mutate buffers for soundness, even if it's not obvious what bugs or exploits this could result in. It's also quite unnecessary if all we do is convert the slice back to a pointer and pass it to OpenGL.
Memory access that could result in `SIGBUS` is probably also problematic in access from safe Rust code that expects all memory accesses to succeed.
This simply replaces the slice with a pointer and length, which for the most part (with the current renderer …
> Use pointer and length to refer to shm memory, instead of slice

- src/backend/drm/compositor/mod.rs
This fixes an issue where Overlay planes were assumed to be below the primary plane when they both had a zpos of 0. However some devices do not report a zpos for the overlay plane which should still put it above the primary one.
To fix this, overlay planes are now assumed to be above the primary plane when their zpos is equal to that of the primary plane. This is consistent with the other `is_underlay` check in
`try_assign_overlay_plane`.
> Fix overlay zpos check during rendering

- anvil/Cargo.toml
- src/backend/drm/compositor/mod.rs
- src/backend/drm/device/mod.rs
- src/backend/drm/surface/atomic.rs
- src/backend/drm/surface/legacy.rs
- src/backend/libinput/mod.rs
- src/backend/renderer/damage.rs
- src/backend/renderer/element/memory.rs
- src/backend/renderer/element/surface.rs
- src/backend/renderer/element/texture.rs
- src/backend/renderer/gles2/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/utils/wayland.rs
- src/backend/udev.rs
- src/backend/vulkan/mod.rs
- src/backend/winit/mod.rs
- src/backend/x11/mod.rs
- src/backend/x11/surface.rs
- src/desktop/space/mod.rs
- src/desktop/space/wayland/mod.rs
- src/desktop/wayland/layer.rs
- src/input/keyboard/mod.rs
- src/input/pointer/mod.rs
- src/wayland/output/handlers.rs
- src/wayland/shm/pool.rs
- src/xwayland/xwm/mod.rs
This downgrades the log-level of a bunch of spans, which annotate hot paths, many of which aren't even used for actual log messages.
Because entering and leaving spans generates internal events - even though we don't log them - this caused severe performance implications, observable using cargo-flamegraph before and after this commit.
> logging: Be less expensive with tracing

- anvil/src/udev.rs
It seems the EGLDevice doesn't advertise a DRM path when I test in a VM with QXL. This seems to work as expected.
> anvil: Fix support for LLVMpipe on udev

- src/backend/renderer/element/mod.rs
This change makes it easier for consumers to just `mem::take` the states from the frame result, which is useful since it has a lifetime attached to the original input data.
This patch now derives all important common traits that are directly derivable, following Rust's official API guidelines: https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits
> Implement `Default` for `RenderElementStates`

- src/backend/drm/mod.rs
drm-rs interprets a range with [0,1] as Boolean, but in case of zpos we want to know the actual value. Until sorted out in rm-rs we just reverse the transform back to receive the zpos value.
> drm: workaround zpos range type boolean

- src/backend/drm/compositor/mod.rs
- src/backend/drm/surface/atomic.rs
There were multiple issues regarding rotation with drm planes:
- The output `Transform` was not used for direct scan-out on the primary plane (fixed by 1e9726dea3c0cbc73746913fe6e5ea0839a20059)
- The surface did not report an issue when a plane does not expose a rotation property but a `Transform` was requested (fixed by 1cdfe14305d84ae8c06d37614aa3724fc1f79c53)
cc @chrisduerr
> Fix drm rotation

- src/desktop/space/element/mod.rs
- src/desktop/space/mod.rs
It seems since e8c977c9 `Space::map_element` doesn't take a `z_index` argument, and `SpaceElement::z_index` doesn't take a space. So these mentions are outdated.
> desktop: Remove outdated doc comments about `z_index`

- rust-toolchain.toml
In my opinion it wouldn't be bad, if smithay would include the
rust-toolchain.toml file because then it's likely guaranteed that all devs are
using the same rust-tools.
> Adding rust toolchain file

- src/xwayland/xwm/mod.rs
- src/xwayland/xwm/surface.rs
EWMH says a client MUST use a client message to change this, so this should be managed by the compositor and it is not necessary to read the value from X. Assuming the `X11Surface` exists for the lifetime of the X window, and the compositor only sets this via `change_net_state`.
Fixes https://github.com/pop-os/cosmic-comp/issues/90. This should also generally perform better since it removes a `get_property` call which has to wait on the X server, and it doesn't allocate a `HashSet`. For what difference that makes.
This also fixes what appears to be a mistake in `update_net_window_type`.
> xwm: Only set _NET_WM_STATE if it has changed 

- anvil/src/state.rs
- src/wayland/fractional_scale/mod.rs
Both the protocol and the existing `FractionalScaleManagerState` name this feature "fracitonal scale". During implementation I just quickly typed out the code and had to fix it after realizing that Smithay's handler has inconsistent naming.
While this is a somewhat unnecessary breakage, I think in the long run it's going to be beneficial to have consistent naming that doesn't get in the way and this feature is still relatively new.
> Rename FractionScaleHandler to FractionalScaleHandler

- src/wayland/virtual_keyboard/virtual_keyboard_handle.rs
I wanted to immediately create this PR as a follow-up since otherwise chances are nobody would have gotten to it (arguably it's relatively insignificant). See https://github.com/Smithay/smithay/pull/943#issuecomment-1474854032 for context.
---
This patch further improves upon 7f8618c, by parsing the keymap as a string instead of letting xkbcommon memory map the provided file descriptor.
The keymap is additionally also limited to 1MiB in size, to ensure clients cannot DoS the compositor by passing a huge `size` value to the `Keymap` request.
> Improve virtual keyboard keymap handling

- src/backend/renderer/element/utils/elements.rs
Previously the `CropRenderElement` would not take the existing element's cropping into account. This can create problems when nesting cropped render elements which can easily happen with viewporter for example.
The approach taken by this patch is to calculate the new cropped source rectangle and then only return the intersection to the original source rectangle. This allows `CropRenderElement` to crop stuff off without ever increasing the source rectangle and reverting existing cropping.
---
Just wanted to point out that this fix almost seems to simple to work just like this. So if someone can think of other potential edgecases that might break this, please let me know. This was only very briefly tested with viewporter (though it did work).
> Fix CropRenderElement nesting

- src/utils/geometry.rs
a touching only rect will produce an empty intersection, this is not useful and should check for an actual overlap instead.
fixes #898
> utils: fix intersection returning empty rects

- src/backend/renderer/gles2/mod.rs
External images on nvidia gpus seem to suffer from synchronization issues without this change. OES_EGL_image_external also seems to suggest, that this is a good idea.
> gles2: Always rebinding egl_images

- anvil/src/render.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- smallvil/src/winit.rs
- src/backend/drm/compositor/mod.rs
- src/backend/renderer/damage.rs
- src/backend/renderer/element/memory.rs
- src/backend/renderer/element/surface.rs
- src/backend/renderer/element/texture.rs
- src/backend/renderer/utils/mod.rs
- src/backend/renderer/utils/wayland.rs
- src/desktop/space/mod.rs
- wlcs_anvil/src/main_loop.rs
The naming of `DamageTrackedRenderer` implies that it is a renderer, which it is not. Fix this inaccuracy by renaming:
- `DamageTrackedRenderer` -> `OutputDamageTracker`
- `DamageTracker` -> `DamageBag`
- `DamageTrackerSnapshot` -> `DamageSnapshot`
This also documents the expected z-order of elements.
fixes #895
> Fix inaccurate renderer nameing

- src/desktop/wayland/layer.rs
A shell surface shouldn't receive `configure` with a larger size than the space available to it. Also, the positioning logic here behaves in an unexpected way if `(source.size.h / 2) - (size.h / 2)` is negative.
> layer: Limit `size` to `source.size`

- src/backend/mod.rs
Without the PR:
With the PR:
Makes it easier to read in my opinion.
> doc: restructure doc in `backend/mod.rs`

- src/lib.rs
How it looks at the moment:
How it looks like with this PR:
Makes it easier to see which two modules you mean in my opinion.
> Restructure "Structure of the crate" doc section

- src/backend/drm/compositor/elements.rs
- src/backend/drm/compositor/mod.rs
When en element switches between direct scan-out and composition we will dynamically add or remove fake elements to communicate the opaque regions of overlay planes and realize hole punching in case of underlays. Re-using the id of the elements will miss with the damage state of the internal output damage tracker. Instead we now use an artifical Id per plane for the fake elements.
cc @chrisduerr
> drm: fix element switching direct scan-out <> composition

- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/handlers/wm_base.rs
check if there are still known surfaces when destroying the xdg_wm_base object.
fixes #589
> wayland: xdg_wm_base destroy protocol check

- src/wayland/compositor/handlers.rs
Wayland defines subsurfaces in terms of a surface with a role. Smithay also treats it as such and this is problematic for protocol that is designed to work with wl_subsurface objects directly. Without a mechanism to obtain the underlying protocol implementations external to Smithay are unable to perform any operations.
Here is an example of usage using Chrome specific protocol (whose actually usefulness is out of scope).
```
augmented_sub_surface::Request::SetPosition { x, y } => {
if x.trunc() != x || y.trunc() != y {
info!("Unsupported float offset x:{x} y:{y}");
}
with_states(
data.wl_subsurface
.upgrade()
.unwrap()
.data::<SubsurfaceUserData>()
.unwrap()
.surface(),
|states| {
states
.cached_state
.pending::<SubsurfaceCachedState>()
.location = (x as i32, y as i32).into()
},
);
}
```
> SubsurfaceUserData: Add an accessor for the parent surface

- src/backend/renderer/gles/format.rs
- src/backend/renderer/gles/shaders/implicit/mod.rs
The nvidia-driver isn't very happy about us using `RGBA8` as an internal representation while reading the texture as `BGRA_EXT`. Mesa accepts that happily (probably converting internally), but nothing in the extension-spec says, that this is supposed to work.
Luckily storing the texture internally as BGRA, doesn't seem to have an effect on rendering. The colors are not inverted when accessing them in the shader, it just has an effect on reading back the texture with `ExportMem::copy_texture`, which shouldn't be a problem.
> gles: Fix BGRA usage out of spec

- anvil/src/udev.rs
With #991 being merged, we are now calling glRenderbufferStorage with GL_BGRA_EXT, if a renderbuffer is initialized with A/Xrgb8888 formats.
While this is technically correct, the docs of the EXT_texture_format_BGRA8888 [1] only mention:
> This extension provides an additional format and type combination
for use when specifying **texture data**.
This is problematic, because we are currently using a Renderbuffer for offscreen cursor plane rendering in anvil for the `DrmCompositor`.
Furthermore glReadPixels is not guaranteed to support any read format besides `GL_RGBA` [2]. Fortunately it is pretty likely, that the driver will let us read the contents with GL_BGRA_EXT, if the internal storage is also GL_BGRA_EXT (though we should really check that with `GL_IMPLEMENTATION_COLOR_READ_FORMAT` …
> anvil: Don't use Renderbuffer for offscreen cursor

- smithay-drm-extras/src/edid.rs
WlOutput can't use manufacturer name that contains \u{0} char
> drm-extras: Don't put null bytes in manufacturer string

- src/backend/renderer/gles/mod.rs
we always map Argb8888 to BGRA_EXT, so we also have to handle that in the gles 2.0 code path
fixes broken shm clients when run with opengl es 2.0 (either on real hardware or forcing with `MESA_GLES_VERSION_OVERRIDE="2.0"`)
> renderer: allow BGRA_EXT in gles 2.0

- src/backend/allocator/swapchain.rs
- src/backend/drm/compositor/mod.rs
- src/input/pointer/mod.rs
New rust nightly detects this and causes CI to fail.
> ci: Fix unnecessary mut for &mut references

- src/backend/renderer/gles/element.rs
- src/backend/renderer/gles/mod.rs
- src/backend/renderer/gles/texture.rs
- src/backend/renderer/gles/uniform.rs
This fixes a bunch of documentation comments still pointing to the old `Gles2*` names for the `Gles*` structs.
> Remove doc references to Gles2 structs

- examples/minimal.rs
- src/wayland/shell/xdg/handlers.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/handlers/surface/popup.rs
- src/wayland/shell/xdg/handlers/surface/toplevel.rs
- src/wayland/shell/xdg/mod.rs
This used to be needed because `destroyed` handler did not have access to compositor state, but that limitation is long gone.
> wayland: Remove Arc<Mutex<Inner>> from xdg shell state

- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/mod.rs
Downstream might want to track configures send and check if they have already been acked. This is quite difficult with the current api, because downstream has to compare the changes it made to the configure struct passed to `LayerShellHandler::ack_configure` and `XdgShellHandler::ack_configure` respectively.
This PR changes `send_configure` calls to return the serial used for the configure, so downstream can simply compare the serial in `ack_configure` to be sure state was acknoledged.
> wayland: Return serial on configure

- src/input/keyboard/mod.rs
- src/input/keyboard/xkb_config.rs
This allows changing the keymap used the keyboard without removing and re-adding the `wl_keyboard`. This seems to be the best way to do dynamic xkb configuration, so settings can be changed without restarting the compositor.
Like `wlr_keyboard_set_keymap`, this creates a new `xkb_state`, updates it with pressed keys, and sends modifiers to clients.
I think this should be correct but it needs testing, so leaving as a draft for now.
> input: Add `KeyboardHandle::set_xkb_config` method

- anvil/src/shell/mod.rs
- anvil/src/state.rs
- examples/compositor.rs
- examples/minimal.rs
- smallvil/src/handlers/compositor.rs
- smallvil/src/state.rs
- src/backend/allocator/dmabuf.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/transaction.rs
- src/wayland/compositor/tree.rs
- src/wayland/content_type/mod.rs
- src/xwayland/xserver.rs
Best reviewed commit-by-commit:
**[compositor: Use the TransactionQueue](https://github.com/Smithay/smithay/commit/71f145b59fbc71598cd8c18375eb2c5da7b0e5ee)**
Changes the internal handling of the compositor module to use the TransactionQueue. Should result in identical behavior, doesn't expose anything new to downstream.
**[compositor: Make it possible to add Blockers](https://github.com/Smithay/smithay/commit/6946f4b5e29f5e181eab73a80b215d673877b23c)**
Adds new public api to the compositor module to allow downstream to add Blockers to a surface, which will be considered on the next commit.
Couple of open questions for this commit:
**[buffer: Add buffer_attached callback](https://github.com/Smithay/smithay/commit/91ffd61aa41ac69b2764b38ef4e381e1ead3c77e)**
Adds a new …
> wayland: Surface Transactions

- src/utils/clock.rs
- src/utils/sealed_file.rs
`memfd_create` and sealing only exist on Linux and on recent versions of FreeBSD. For NetBSD, OpenBSD, Illumos, Darwin, etc. it is necessary to fallback to something like `shm_open`.
Using `shm_open` twice to get a writable and read-only fd seems to match what wlroots does (in `allocate_shm_file_pair`). They don't seem to use `memfd_create` and sealing at all.
`CLOCK_BOOTTIME` and `CLOCK_UPTIME` don't seem to exist on platforms like NetBSD. Getting system uptime is possible, but involves `sysctl` and not a `clockid_t`. OpenBSD seems to have both `CLOCK_BOOTTIME` and `CLOCK_UPTIME`. But they are different (`CLOCK_UPTIME` excludes time spent suspended.) This isn't used anywhere. So unless it's expected to be important for something, may be simplest to remove it?
> portability: Fallback for `SealedFile`, and remove `Boottime`

- Cargo.toml
- benches/benchmark.rs
- src/utils/user_data.rs
Profiling suggests the compositor was spending a surprising amount of time getting the thread ID. It seems `thread::current().id()` is a bit slow. Calling this once and storing the result in a thread-local seems to make the performance roughly match the thread-safe variant, if the benchmark added here is accurate.
> Use a thread-local for thread ID in `UserDataMap::get`

- rust-toolchain.toml
- src/backend/allocator/swapchain.rs
The PPP's driver seems to run into non-recoverable framebuffer errors when the `reset_buffers` function is called and the `InternalSlot` is reset while the `InternalSlot::buffer` is kept.
This patch adds a new function which only resets each slot's buffer age rather than resetting the entire slot, allowing a force-redraw on the PPP without triggering the framebuffer error.
---
This was the only solution me and @cmeissl could come up with, but he suggested to either go for something like this or to just always reset the entire slot in `reset_buffers` without keeping the buffer around. Both of those fix the issue on the PPP based on my testing.
Leaving the decision on which solution to go with to @Drakulix (unless you have an even better suggestion).
> Add buffer age reset function

- src/backend/renderer/gles/mod.rs
If the user wants to copy contents from a texture, don't copy from it's shadow buffer instead...
> gles: Don't copy from shadowbuffer instead of texture

- src/desktop/wayland/layer.rs
This fixes the positions of layer shell surfaces with rotated displays on cosmic-comp, and fixes the position of tiled windows (which are based on the exclusive zone).
> layer: Fix `LayerMap` `zone` to account for output transform

- anvil/src/input_handler.rs
- anvil/src/shell/mod.rs
- anvil/src/shell/x11.rs
- anvil/src/shell/xdg.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
Behavior with only one output should be unchanged. This seems fairly important for usability with multiple outputs. Especially with dialog windows.
A full-featured compositor may have much fancier logic, but for Anvil this seems better at least.
> anvil: Show new window on output with cursor, not first output

- src/wayland/input_method/input_method_handle.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/seat/keyboard.rs
- src/wayland/text_input/mod.rs
- src/wayland/text_input/text_input_handle.rs
Presumably text input on a seat should always go to the surface that has keyboard focus on the seat. So that should be done automatically, and a way to set the text input focus isn't needed in the public API.
I'm still looking into other issues with fcitx5. But it works better with this (shows up at all), so it's an improvement as long as this doesn't negatively impact any other IME client.
Supersedes https://github.com/Smithay/smithay/pull/1038.
CC @rano-oss
> text-input: Set focus on keyboard `enter`/`leave`

- src/utils/user_data.rs
This adds two new public methods to the `UserDataMap` stored for surfaces, aimed at making developers' lives a little easier.
The `get_or_insert` and `get_or_insert_threadsafe` methods allow getting guaranteed access to the user data without any `unwrap` in the user's code.
The `insert` and `insert_threadsafe` methods have been added as an internal abstraction to ensure the code stays consistent. I've kept them private assuming that the `if_missing` checks are necessary because the underlying storage has no deduplication mechanisms.
> Add get_or_insert abstractions for surface data

- src/backend/allocator/swapchain.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/surface/gbm.rs
- src/backend/x11/surface.rs
In a1e4cf3, the new `reset_buffer_age` function was added to the swapchain for resetting damage without having to reset the buffers themselves.
This function is not used anywhere in Smithay but could be a simpler and more clear API for users to "force" redraws. However the swapchain itself is not directly accessible to users.
This patch adds a public `reset_buffer_ages` function to all structs providing a `reset_buffers` method as an alternative for Smithay's consumers.
The original `reset_buffer_age` function has also been renamed to `reset_buffer_ages` to be more in line with `reset_buffers` and signify that there's multiple buffers being involved here.
> Expose swapchain's reset_buffer_age function

- src/backend/renderer/gles/mod.rs
GlesTexture::from_raw takes an `opaque` parameter. When creating an offscreen texture this parameter was set to `has_alpha` which would imply transparency, I.E. the opposite of opaque.
> fix: offscreen texture has_alpha determination

- src/backend/drm/compositor/elements.rs
- src/backend/drm/compositor/mod.rs
- src/backend/renderer/damage.rs
This PR tries to reduce damage on the primary plane.
The `OutputDamageTracker` now automatically damages areas no longer covered by opaque regions.
This enables us to return to only report opaque regions from overlay plane elements in the `DrmCompositor`
and no longer forward damage of the original element.
~~The last commit changes the `Element` trait to return an `Option` for opaque regions.  This can save us from some allocations for non opaque elements. They were already tracked as on Option in most elements anyway.
The commit is fully optional, so I can easily drop it if we do not want to change the api.~~
> Fix unnecessary damage

- src/backend/egl/context.rs
- src/backend/egl/device.rs
- src/backend/egl/display.rs
- src/backend/egl/error.rs
- src/backend/egl/fence.rs
- src/backend/egl/ffi.rs
- src/backend/egl/native.rs
Most EGL calls return a value which indicates whether the call succeeded or not, so avoid checking for errors when none happened.
I went for specialisation since checking for `!= EGL_FALSE` gets redundant pretty quickly, same for `!.is_null()`.  There are a few functions returning unexpected errors though, in our case `eglClientWaitSync()` and `eglDupNativeFenceFDANDROID()`, returning respectively `EGL_FALSE` even though it is a `EGLint`, and `-1`.
This has been tested with the [Catacomb](https://github.com/catacombing/catacomb) compositor, it indeed reduces the amount of `eglGetError()` calls to exactly zero according to [apitrace](https://apitrace.github.io/).
> egl: Only query eglGetError() when an error happened

- anvil/src/drawing.rs
- anvil/src/render.rs
- anvil/src/shell/element.rs
- src/backend/renderer/damage.rs
- src/backend/renderer/element/memory.rs
- src/backend/renderer/element/mod.rs
- src/backend/renderer/element/solid.rs
- src/backend/renderer/element/surface.rs
- src/backend/renderer/element/texture.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/desktop/wayland/popup/grab.rs
- src/input/keyboard/mod.rs
- src/input/mod.rs
- src/input/pointer/mod.rs
- src/wayland/input_method/input_method_handle.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/relative_pointer.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/virtual_keyboard/virtual_keyboard_handle.rs
- wlcs_anvil/src/renderer.rs
In general, I don't think there's any reason to use types that don't implement `Debug` here? And a crate can always implement `Debug` in some way for its own types, even if it isn't derivable.
With this, a lot of `Debug` implementations can just be derived, and code can assume these types are printable without additional bounds. The latter should  generally be an API improvement. (The reason I looked at this was that I tried to add a print and got a complaint that a debug bound would be needed somewhere.)
> Move some `Debug` bounds to traits, simplifying a lot of things

- src/backend/drm/surface/atomic.rs
When using the `DrmSurface::use_mode` function, we are currently testing the plane config with the old mode previously set, which will fail on most (if not all) drivers.
> drm/atomic: Use new mode when testing

- src/desktop/wayland/popup/grab.rs
- src/input/mod.rs
- src/wayland/input_method/input_method_handle.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/virtual_keyboard/virtual_keyboard_handle.rs
These are still needed to implemented `Debug` without a `D: Debug` bound.
If there were *one* manual debug impl like this I'd add a comment noting that it is the same as the derived implementation but with a different bound, and link to https://github.com/rust-lang/rust/issues/26925. But adding that comment everywhere would be verbose...
This still slightly simplifies many of these implementations, since they used to require `Debug` bounds for `::KeyboardFocus`, `::PointerFocus` etc. When removing those I switched to deriving `Debug` since that *seemed* to work.
> Add back manual `Debug` impls removed in f628336b

- .github/workflows/ci.yml
wayland-protocols 0.30.1 exists now, so CI is unhappy about the hardcoded 0.30.0, which is not pulled anymore.
> Update wayland-protocols for docs action

- src/desktop/wayland/layer.rs
This check makes it impossible to figure out which `LayerSurface` belonged to a `WlrLayerSurface` passed to `WlrLayerShellHandler::layer_destroyed`.
This is completely unnecessary, as all the state should still be available, when this handler is triggered. This is especially useful to figure out what output a now dead layer-surface was previously shown on to re-render said output.
> layer_map: Don't ignore dead surfaces

- src/backend/drm/compositor/mod.rs
- src/backend/renderer/damage.rs
- src/desktop/space/mod.rs
- src/output.rs
This patch adds new functions to the `DrmCompositor` to allow users to control when its output mode should be updated, rather than using the Output to update the mode automatically.
---
This *seems* to work with my compositor and fixes my issues. Though no guarantees it doesn't mess with damage tracking somehow.
> Add static output mode support for DrmCompositor

- src/utils/clock.rs
In order to avoid colliding with the logical definition of function std::time::duration_since, rename utils' opposite implementation to be more fitting.
For more details:
https://doc.rust-lang.org/std/time/struct.SystemTime.html#method.duration_since
> utils/clock: Rename duration_since

- src/backend/renderer/gles/mod.rs
Currently the only texture format that can be sampled from as an offscreen texture is RGBA8 persuant to the GLES2 spec. Since BGRA is already required, and since buffers that are allocated for textures end up being BGRA, allow this format as well.
> gles: Support more formats for GlesTexture

- src/wayland/compositor/tree.rs
Fixes: https://github.com/Smithay/smithay/issues/774
---
The errors are incorrect (~~`wl_subcompositor.bad_surface` and `wl_subcompositor.bad_parent` must be sent instead~~ `wl_subcompositor.bad_surface` *is* used, but with a misleading message), but at least Anvil doesn't crash or freeze anymore.
> compositor: fix subsurface parent checks

- src/backend/egl/ffi.rs
- src/backend/egl/native.rs
For this to work I also had to modify `LIB` to point to the `libEGL.so` from ANGLE. And set `VK_ICD_FILENAMES`, because naturally it wasn't working with Nvidia drivers, but was with Intel.
This uses Vulkan. It seems ANGLE only provides the Wayland platform with Vulkan.
This then runs, but errors with "Depth/stencil buffer format combination not allowed for blit." It seems it needs to use `DEPTH24_STENCIL8`. Presumably that's what the default framebuffer is using?
> egl: Support ANGLE EGL platform on winit Wayland

- anvil/src/input_handler.rs
- anvil/src/shell/x11.rs
- anvil/src/shell/xdg.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- wlcs_anvil/src/main_loop.rs
If the pointer location is tracked within Smithay, it seems bad for to have a separate copy of it. Assuming we never want them to get out of sync.
Defining a method for `pointer_location()` is awkward since we can't split borrows in method calls, so the call has to be moved earlier, in some uses. But the code is slightly verbose to duplicate everywhere it's used. Maybe just store a copy of `PointerHandle` in the state, to avoid having to get it from the seat and unwrap?
More importantly, there are a few cases marked `XXX` where pointer events were not generated.
(https://github.com/Smithay/smithay/issues/1087 is one of them). Do we want to just generate pointer motion (but not relative motion) events in all of these cases?
> anvil: Don't store `pointer_location`, use from `PointerHandle`

- src/xwayland/xwm/mod.rs
This seems to match Mutter and i3. As defined in EWMH these contain "all X Windows managed by the Window Manager". I think override-redirect windows are not considered to be "managed by" the WM. A non-compositing X WM can simply ignore override-redirect windows entirely and leave them to the application and X server to deal with.
More importantly, this prevents `configure_window` from being called on override-redirect windows when updating stacking order. (Presumably an X WM should never send configure for override-redirect windows.) This fixes submenus in Gimp on cosmic-comp.
> xwm: Don't include override-redirect windows in `_NET_CLIENT_LIST*`

- smallvil/src/input.rs
- smallvil/src/state.rs
- smallvil/src/winit.rs
Trying to make a compositor and these are some things I bumped into.
> Minor smallvil fixes

- src/backend/allocator/dumb.rs
Without this I get `[EGL] 0x3002 (BAD_ACCESS) eglCreateImageKHR: invalid pitch`
Though using `buffer_test` with `--dump` with this still doesn't produce quite the right output.
> allocator/dumb: Pass correct pitch in `AsDmabuf::export`

- smallvil/src/handlers/compositor.rs
- smallvil/src/handlers/mod.rs
- smallvil/src/handlers/xdg_shell.rs
- smallvil/src/state.rs
- smallvil/src/winit.rs
This time: fix clipboard and add basic popup support.
> Smallvil fixes 2

- .github/workflows/ci.yml
- src/backend/drm/mod.rs
- src/backend/drm/surface/mod.rs
- src/backend/egl/display.rs
- src/backend/renderer/element/memory.rs
- src/backend/vulkan/inner.rs
- src/backend/vulkan/mod.rs
- src/utils/clock.rs
Should fix CI build.
I'm not sure about the use of `Arc` in `MemoryRenderBuffer`. It seems `MemoryRenderBufferInner` isn't `Send` because `Box<dyn Any>>` isn't. `Send` can be added there if a `Send` bound is added on `TextureId`. But then `GlesTexture` isn't `Send` so that presumably isn't desired in general.
> Fix clippy lints on Rust 1.72

- .github/workflows/ci.yml
- Cargo.toml
- anvil/src/state.rs
- src/backend/drm/mod.rs
- src/backend/drm/surface/mod.rs
- src/backend/egl/display.rs
- src/backend/renderer/element/memory.rs
- src/backend/vulkan/inner.rs
- src/backend/vulkan/mod.rs
- src/utils/clock.rs
- src/wayland/mod.rs
- src/wayland/security_context/listener_source.rs
- src/wayland/security_context/mod.rs
The compositor should not expose the `wp_security_context_manager_v1` global to clients connected to a security context. Otherwise, I guess this would be up to the compositor to set its own restrictions.
This implementation is currently incomplete.
> Security Context protocol

- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/desktop/wayland/utils.rs
- src/wayland/presentation/mod.rs
The refresh represents the time till the next vblank relative to the timestamp and not the mode refresh
> wayland: fix presentation time refresh

- anvil/src/focus.rs
- anvil/src/input_handler.rs
- anvil/src/shell/element.rs
- anvil/src/shell/grabs.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- smallvil/src/grabs/move_grab.rs
- smallvil/src/grabs/resize_grab.rs
- src/backend/input/mod.rs
- src/desktop/wayland/layer.rs
- src/desktop/wayland/popup/grab.rs
- src/desktop/wayland/window.rs
- src/input/mod.rs
- src/input/pointer/grab.rs
- src/input/pointer/mod.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/mod.rs
- src/wayland/pointer_gestures.rs
- src/wayland/relative_pointer.rs
- src/wayland/seat/pointer.rs
- src/xwayland/xwm/surface.rs
Implements zwp_pointer_gestures_v1 and the entire Smithay support for it.
The Wayland gesture objects store whether they are currently active (i.e. between begin() and end()) on a given `WlSurface`. When receiving gesture update or end event, this field is checked, and if it doesn't match, then the gesture is cancelled. This way, gesture objects bound mid-gesture, or something equally weird happening, won't receive update() with no begin().
You could do something smarter, e.g. mutter will synthesize a gesture begin event if you move the pointer onto a surface mid-gesture, but doing this sounds quite more complex (need to track ongoing gestures on the pointer), and I don't think this usecase is very realistic (for this to happen you have to do something along move the pointer with a mouse …
> Touchpad gestures

- src/input/keyboard/mod.rs
> input: Only forward modifiers in KeyboardInnerHandle::set_focus

- anvil/src/input_handler.rs
- smallvil/src/input.rs
It's only supposed to be sent when there actually is a zero in the event, not when the value is missing.
This notably fixes non-diagonal scrolling in winit and alacritty.
> ‘vils: Fix axis_stop event delivery

- src/wayland/seat/pointer.rs
The protocol states "each axis_discrete event is always followed by exactly one axis event with the same axis number within the same wl_pointer.frame", while "The order of wl_pointer.axis_discrete and wl_pointer.axis_source is not guaranteed."
Which suggests `axis_discrete` should occur before `axis`.
This should correctly match the protocol spec, and other compositors.
> Fix order of pointer axis events within frame

- anvil/src/drawing.rs
- anvil/src/shell/ssd.rs
- examples/minimal.rs
- src/backend/drm/compositor/mod.rs
- src/backend/renderer/damage.rs
- src/backend/renderer/element/memory.rs
- src/backend/renderer/element/mod.rs
- src/backend/renderer/element/solid.rs
- src/backend/renderer/element/surface.rs
- src/backend/renderer/element/texture.rs
- src/backend/renderer/element/utils/elements.rs
- src/backend/renderer/gles/element.rs
- src/desktop/space/element/wayland.rs
- src/desktop/space/wayland/layer.rs
- src/desktop/space/wayland/window.rs
- src/desktop/space/wayland/x11.rs
this can give the backend a hint about how to handle the element.
for now the only supported use-case is to not accidentally assign non cursor content to the cursor plane
In the future this could be extended to reflect `wp_content_type`.
Only a Draft to discuss alternatives.
One alternative would be to introduce some kind of `ScanoutPriority` which could be used to limit the planes
an element can or should be placed on. But this is way more complex, not only for implementation, but also from
the design perspective. Maybe the two things could be considered orthogonal? The `ScanoutPriority` could look roughly like this:
```rs
pub enum ScanoutPriority {
Undesired,
Undefined,
Priorize(usize)
}
```
Another alternative I considered is to explicitly pass the cursor element(s) to …
> allow to specify a kind for an element

- anvil/src/focus.rs
- anvil/src/input_handler.rs
- anvil/src/shell/element.rs
- anvil/src/shell/grabs.rs
- smallvil/src/grabs/move_grab.rs
- smallvil/src/grabs/resize_grab.rs
- smallvil/src/input.rs
- src/desktop/wayland/layer.rs
- src/desktop/wayland/popup/grab.rs
- src/desktop/wayland/window.rs
- src/input/mod.rs
- src/input/pointer/grab.rs
- src/input/pointer/mod.rs
- src/wayland/data_device/dnd_grab.rs
- src/wayland/data_device/server_dnd_grab.rs
- src/wayland/pointer_gestures.rs
- src/wayland/relative_pointer.rs
- src/wayland/seat/pointer.rs
- src/xwayland/xwm/surface.rs
- wlcs_anvil/src/main_loop.rs
Input handling in compositors will have to emit this appropriatly. But then other methods don't have to map perfectly to frames.
Meant to address https://github.com/Smithay/smithay/issues/1126.
> Make `frame` a seperate method of `PointerTarget`/`PointerGrab`

- Cargo.toml
- anvil/src/udev.rs
- src/wayland/drm_lease/mod.rs
- src/wayland/mod.rs
> drm leasing

- Cargo.toml
- anvil/Cargo.toml
- anvil/src/input_handler.rs
- anvil/src/state.rs
- examples/buffer_test.rs
- smallvil/src/state.rs
- src/backend/drm/device/mod.rs
- src/backend/libinput/mod.rs
- src/backend/session/libseat.rs
- src/backend/udev.rs
- src/input/keyboard/mod.rs
- src/wayland/seat/keyboard.rs
- src/wayland/socket.rs
- src/xwayland/xserver.rs
- wlcs_anvil/Cargo.toml
- wlcs_anvil/src/renderer.rs
PR composed of 4 commits:
- Update of calloop to 0.12.1, which required adding a few unsafe block with associated safety comments
- Trivial update of several dependencies
- Update of xkbcommon to 0.6.0, which now uses concrete types to represent `Keycode` and `Keysym`, this found a small bug in the input/keyboard logic, where the `+ 8` offset was forgotten
- Minor clippy fixes
> Dependencies updates

- src/backend/drm/device/mod.rs
> Make DrmEventMetadata Copy

- src/utils/geometry.rs
Allows downstream to implement their own coordinate spaces without sacrificing `fmt::Debug` for it.
> geometry: Generic Debug implementation

- src/backend/drm/node/mod.rs
- src/backend/x11/mod.rs
- src/wayland/shm/pool.rs
This still leaves `XWaylandEvent::Ready` using a `RawFd`, which is awkward. Not sure exactly what the logic is there, and that field isn't used in anvil or cosmic-comp, but maybe ref-counting could be used? And `RawFd`s are used in `Session`/`LibSeatSession`, but it's not clear how to update that either.
> Use safe IO types in a couple more places

- anvil/src/input_handler.rs
- anvil/src/shell/mod.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/desktop/wayland/popup/manager.rs
- src/desktop/wayland/popup/mod.rs
- src/wayland/input_method/input_method_handle.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/input_method/input_method_popup_surface.rs
- src/wayland/input_method/mod.rs
- src/wayland/text_input/text_input_handle.rs
Fix for https://github.com/Smithay/smithay/issues/1045. This eliminates the need for `set_point`, and for the compositor to have separate code for rendering IME popups.
This seems to work at least as well as the previous version with fcitx5 in anvil? The use of `set_point` previously wasn't correct. But some work is still needed.
The current version of the protocol also has some fundamental issues that may be problematic here. We can bring anything like that up in discussion of the v3 protocol.
> WIP Use `PopupKind`/`PopupManager` for input method surface

- src/desktop/space/mod.rs
- src/desktop/space/wayland/mod.rs
- src/desktop/space/wayland/window.rs
- src/desktop/space/wayland/x11.rs
- src/desktop/wayland/utils.rs
It's useful for compositors to manage output overlap for non-Window surfaces, e.g. pointer and DnD surfaces.
I put it in `desktop/wayland/utils` as there's nothing Space-specific about it.
Example use scenario: https://github.com/YaLTeR/niri/commit/01906b190318a5e12feeb0dfa20a602a8561809f
> Make output_update() public

- Cargo.toml
- anvil/src/drawing.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/input/pointer/cursor_image.rs
- src/input/pointer/mod.rs
- src/wayland/cursor_shape.rs
- src/wayland/mod.rs
- src/wayland/tablet_manager/mod.rs
- src/wayland/tablet_manager/tablet_tool.rs
- wlcs_anvil/src/main_loop.rs
--
The protocol is dead simple and requiring a full rendering impl sounds overkill for it, given
that compositors can opt-in into this protocol, when they can handle the cursor themes.
Tested that it only reaches the compositor with https://github.com/YaLTeR/niri/pull/32 , but the actual rendering is not done, and only default cursor is properly rendered.
Testing client https://github.com/Smithay/client-toolkit/blob/master/examples/themed_window.rs (press `Shift + n` to cycle icons).
> wayland: add cursor_shape_v1 support

- .github/workflows/ci.yml
A few changes to hopefully simplify the CI and reduce its running time:
- Use `cargo check` instead of `cargo test` when there is no test to run anyway
- Use `cargo hack` to check features individually instead of creating a huge matrix of jobs
- Should save on runtime overall for no longer having a huge list of containers to run and being rate-limited by github
- Makes the CI result less clogged to read
- This will automatically pick up new features if / when they are added
- Stop downgrading `log`, this was done to workaround an issue with slog but we don't use it anymore so that should no longer be needed.
> Simplify the CI a bit

- Cargo.toml
- src/xwayland/xwm/surface.rs
encoding is unmaintained: https://rustsec.org/advisories/RUSTSEC-2021-0153
> Replace encoding dep with encoding_rs.

- src/backend/x11/mod.rs
- src/wayland/virtual_keyboard/virtual_keyboard_handle.rs
The use in `virtual_keyboard_handle.rs` additionally was incorrectly using `as_raw_fd` where it should use `into_raw_fd`. Which is unsound but does the right thing unless another thread happens to open an fd at the same time.
> Avoid unnecessary uses of `into_raw_fd` and `borrow_raw`

- src/backend/drm/gbm.rs
`BufferObjectInternal::modifier` does exactly this already. So an invalid/implicit modifier can actually cause this `unwrap` to panic.
> gbm: Don't unnecessarily unwrap

- anvil/src/shell/grabs.rs
- smallvil/src/grabs/move_grab.rs
- smallvil/src/grabs/resize_grab.rs
- src/desktop/wayland/popup/grab.rs
- src/input/keyboard/mod.rs
- src/input/pointer/grab.rs
- src/input/pointer/mod.rs
- src/wayland/selection/data_device/dnd_grab.rs
- src/wayland/selection/data_device/server_dnd_grab.rs
Used in `ClickGrab` to prevent `motion` events from occurring with every `button` event. Otherwise, behavior should be unchanged. This matches the argument taken by `KeyboardInnerHandle::unset_grab`.
This seems like the simplest solution. It would also be possible to add a method to the `PointerGrab` trait indicating if focus should be restored, but that's complicated since `unset_grab` can't access the
grab when it's `Borrowed`, so it would have to add a bool to `GrabStatus::Borrowed`, etc.
This still doesn't send a `frame`, but since this takes a serial and a time, it probably will be sent along with other pointer events, and hopefully part of a `frame`. The Wayland spec isn't all that specific
about when things can/should be part of a `frame`...
Calling `motion` is also incorrect with …
> Add `restore_focus` argument to `PointerInnerHandle::unset_grab`

- Cargo.toml
- src/utils/sealed_file.rs
I didn't notice this use of `nix` earlier since it isn't used on either Linux or FreeBSD.
> Use `rustix` for `shm_open`/`shm_close` fallback

- src/backend/drm/compositor/mod.rs
- src/backend/drm/surface/gbm.rs
Fixes the nvidia 545-beta driver, which can now apparently export/import fences, but not on the drm-side.
> drm: Query syncobj for supports_fencing

- anvil/src/state.rs
- src/wayland/input_method/mod.rs
I still wonder if there's a cleaner way to deal with global visibility, but don't have any suggestions at the moment.
KDE exposes the input method protocol only to the process it starts as an IME. This is definitely a protocol that one may want to restrict.
> Take a global filter function in `InputMethodManagerState::new`

- anvil/src/state.rs
- src/desktop/wayland/popup/manager.rs
- src/desktop/wayland/popup/mod.rs
- src/input/keyboard/mod.rs
- src/wayland/input_method/input_method_handle.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/input_method/input_method_popup_surface.rs
- src/wayland/input_method/mod.rs
- src/wayland/seat/keyboard.rs
- src/wayland/text_input/mod.rs
- src/wayland/text_input/text_input_handle.rs
- src/wayland/virtual_keyboard/mod.rs
- src/wayland/virtual_keyboard/virtual_keyboard_handle.rs
The series is split into 2 commits, the first one addresses the virtual keyboard issues I've faced and the second tries to solve IM issues, which were left on the table. Each commit has a description on what it tried to fix.
--
This is by far the ugliest thing I ever wrote, but to make it nice I'd need to delete all the input handling in smithay, which I don't have time to do.
> Fix IM and virtual keyboard handling

- .github/workflows/ci.yml
- Cargo.toml
- anvil/src/winit.rs
- examples/minimal.rs
- smallvil/src/winit.rs
- src/backend/egl/native.rs
- src/backend/winit/input.rs
- src/backend/winit/mod.rs
Make better winit integration by providing a calloop's WaylandSource
for it. The winit backend now doesn't use vsync and utilizes frame
callbacks, when the user cooperates and asks for `redraw_requested`.
Fixes #146.
> Update winit to 0.29.2 version

- Cargo.toml
- anvil/src/state.rs
- src/desktop/wayland/utils.rs
- src/utils/clock.rs
Rustix's `lock_gettime` does not return an error, and notes it is infallible, while `clock_gettime_dynamic` can handle some additional clocks that may result in an error.
I don't think the clock helper in Smithay needs to handle any of those, so returning a `Result` in `new` is unneeded.
This also uses an associated const for `ClockSource::ID`, so the clock id doesn't need to be stored a runtime when it's already expressed in the type. Const generics would be suitable, but don't work with enums yet.
> utils/clock: Use `rustix`, without `unsafe`; infallible

- src/backend/drm/node/constants.rs
- src/backend/drm/node/mod.rs
- src/wayland/shm/pool.rs
This also uses Rustix for `major`/`minor`, and makes functions accept `dev_t` consistently instead of major/minor arguments, which ends up being a bit simpler.
I'm able to run Anvil in a tty, and get it to show its default background color. For some reason I see no cursor and can't switch tty again. But that's a start...
On OpenBSD, `rust`, `git`, `llvm` can be added with `pkg_add`. There are ports for `wayland/libinput-openbsd`, `sysutils/seatd`, and `sysutils/libudev-openbsd`. `LIBCLANG_PATH=/usr/local/llvm16/lib` is needed for bindgen to find libclang. I also needed to make it use `/usr/X11R6/lib/libEGL.so.2.0` for libegl... not sure how best to handle that. That's not included here. It's also currently necessary to add `use_bindgen` feature flags.
FreeBSD seems to be working fine here …
> Support building on OpenBSD

- anvil/src/shell/element.rs
- src/desktop/wayland/layer.rs
- src/desktop/wayland/utils.rs
- src/desktop/wayland/window.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/tree.rs
`wl_compositor@v6` requires special handling in downstream compositors, so smithay can't provide it unconditionally, thus allow setting a version for `wl_compositor` when creating a global.
--
This is probably not really a good solution, Alternative could be to have a separate constructor which builds _at least_ v6.
> wayland/compositor: add wl_compositor@v6 constructor

- src/desktop/wayland/utils.rs
https://github.com/Smithay/smithay/pull/1177 changed this. But it isn't actually needed for the other changes there, since there's a blanket implementation of `FnMut` for `&mut` references to types implementing `FnMut`.
So this is more general, and helpful for simply passing a closure to the function, etc.
> Accept `F` instead of `&mut F` in `with_surfaces_surface_tree` again

- src/wayland/session_lock/mod.rs
The compositor can store this, and test if the object is still valid with `DisplayHandle::get_client`. This way the compositor can allow another session lock to be created if the previous client crashed and failed to unlock.
Maybe there could be a better API to help with this, but I'm not sure how.
https://github.com/pop-os/cosmic-comp/pull/205 demonstrates how this can be handled.
> session_lock: Add accessor for `ExtSessionLockV1` to `SessionLocker`

- anvil/src/state.rs
- src/input/keyboard/mod.rs
- src/input/pointer/mod.rs
- src/utils/serial.rs
- src/wayland/seat/keyboard.rs
- src/wayland/xdg_activation/dispatch.rs
- src/wayland/xdg_activation/mod.rs
- src/xwayland/xwm/mod.rs
- src/xwayland/xwm/surface.rs
- d116691 - drops tracking pending vs requested tokens. The whole destruction logic was flawed, as the clients don't have to cooperate. The first client generating the token may destroy the wayland object as soon as it has received the token string. The wayland request explicitly states, that the token stays valid.
- 4931081- notifies downstream when a new token is created. In this commit this is only used to immediately discard tokens downstream may consider invalid.
- 568dda9 - Adds user-data to the token data. This could also be done by downstream manually, given that the token implements `Hash`. But we already have a `HashMap` inside the `ActivationState` anyway. (optional)
- 6359bc5 - Updates module docs
- 52d7d94 - Adds a helper to check if a serial …
> xdg-activation: Rework

- src/wayland/security_context/mod.rs
Expose the client_id, that created the security context. This can be used to inherit properties like e.g. privileged protocols to new sockets created by this protocol.
> security-context: Expose client_id

- examples/minimal.rs
- src/wayland/shell/xdg/decoration.rs
- src/wayland/shell/xdg/mod.rs
When running a GTK4 application which tries to reposition a popup surface, it will wait for a commit to confirm the repositioning and halt all rendering.
To avoid compositors accidentally skipping the implementation of this function, it should be clearly indicated that this is mandatory. The documentation was also expanded to reinforce this point.
> Make XdgShellHandler::reposition_request mandatory

- src/xwayland/xwm/mod.rs
This was unfortunately reversed in https://github.com/Smithay/smithay/pull/1024, which wasn't obvious due to the refactoring that PR was doing.
> xwm: Fix reordering

- src/xwayland/xwm/mod.rs
- src/xwayland/xwm/surface.rs
Apparently clients don't like getting positions relative to their parent, if we reparent them? Anyway this works.
> xwm: Send synthetic configure event for reparented windows

- anvil/src/shell/element.rs
GIMP is tested, which works fine.
This is necessary in previous versions but not now, as API has changed.
> Remove unnecessary rebind of `processor`

- src/utils/serial.rs
Qt apps don't acknowledge the xdg_surface configure event when the serial number is 0, therefore, no toplevel appears.
This bug never happens on most compositors because the serial number 0 is used for other things, and by the time a configure event comes, the number is already incremented.
The minimal example suffers from this bug because it's so minimal, and unfortunately serial number 0 is used for the first configure event.
> Start global serial counter at 1

- src/wayland/shell/xdg/mod.rs
Expose what is needed to allow killing a unresponsive client
> add ShellClient::unresponsive

- src/backend/x11/mod.rs
The documentation claims that X11Backend::new returns both X11Backend and X11Surface, but there is not X11Surface returned
> Improve backend/x11/mod docs

- src/backend/renderer/damage/mod.rs
- src/backend/renderer/damage/shaper.rs
The previous logic was blindly merging and doing only a forward pass, however this won't work when after merging 2 rectangles already processed one could end up in overlap.
This is an example of old renderer doing so:
```
[ 697101.942] wl_surface@26.damage_buffer(66, 350, 36, 48)
[ 697101.956] wl_surface@26.damage_buffer(126, 446, 828, 168)
[ 697101.965] wl_surface@26.damage_buffer(90, 638, 744, 528)
[ 697101.974] wl_surface@26.damage_buffer(162, 1262, 420, 72)
[ 697101.984] wl_surface@26.damage_buffer(114, 1358, 312, 48)
[ 697101.994] wl_surface@26.commit()
damage to be rendered: [
Rectangle<smithay::utils::geometry::Physical> {
x: 158,
y: 478,
width: 828,
height: 168,
},
Rectangle<smithay::utils::geometry::Physical> {
x: 194,
y: 1294,
width: 420,
height: 72,
}, …
```
> Ensure that damage is non-overlapping

- src/input/keyboard/mod.rs
While this is not ideal it does the job to implement basic layouts
functionality like switching layout on compositor and propagating the
change to client, resolving latin character for Keysym handles and
set/restore layouts.
--
Showcase could be found here https://github.com/YaLTeR/niri/pull/65
>  Add API to manipulate XKB layouts

- anvil/src/main.rs
- build.rs
- clippy.toml
> Use clippy to disallow e/print/ln macros

- src/wayland/xdg_activation/dispatch.rs
- src/wayland/xdg_activation/mod.rs
This is useful for compositor that spawn processes on their own, e.g. from key-bindings.
> xdg-activation: Allow the compositor to create tokens

- src/input/keyboard/mod.rs
Also make the Layout.0 public to allow constructing Layouts from u32s.
> keyboard: allow setting keymap directly

- src/input/keyboard/mod.rs
This method takes a function that allows for a generic return value, however the function body itself never allows that return value to escape the function.
> Fix return type of `with_pressed_keysyms`

- src/wayland/selection/data_device/mod.rs
This appears to have been a copy/paste error, the primary selection accessor is in selection/primary selection,
> data_device: get clipboard selection instead of primary selection

- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/wayland/dmabuf/dispatch.rs
- src/wayland/dmabuf/mod.rs
This pull request adds the ImportNotifier type, which allows dmabuf import results to be delayed until processed at a later time. In my case this would be after being handled through a channel but can be extended to allow creating an importing thread.
Resolves #699
A quick test by smalling alacritty in smallvil shows this appears to work correctly.
> wayland(dmabuf): ImportNotifier for asynchronous buffer import

- anvil/src/udev.rs
- src/input/keyboard/keymap_file.rs
- src/input/keyboard/mod.rs
- src/wayland/virtual_keyboard/mod.rs
- src/wayland/virtual_keyboard/virtual_keyboard_handle.rs
Smithay's virtual keyboard implementation previously stored a single keymap on the seat, updating it whenever either the real or virtual keyboard's keymap was changed. As a result the two keyboards could break each other by setting an incorrect keymap.
To allow both the seat's real keyboard and the virtual keyboard to function simultaneously, a separate keymap is stored for each and whenever an input event related to a keymap is handled, the keymap is updated.
Closes #1222.
---
I'm not actually sure if this is a valid approach or not and it's definitely possible that I've missed updating the keymap in some places, but this minimal fix has been confirmed to fix the issue for me.
> Add separate keymap for virtual keyboard

- src/backend/renderer/gles/mod.rs
gles 2.0 doesn't support 10-bit, but `fourcc_to_gl_formats` might still return `BGRA_EXT` for `Abgr8888`.
> gles2: Fix bgra on 2.0 context

- Cargo.toml
- anvil/src/input_handler.rs
- smallvil/src/input.rs
- src/backend/input/mod.rs
- src/backend/libinput/mod.rs
- src/backend/winit/input.rs
- src/backend/x11/input.rs
- src/input/pointer/mod.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
I've been thinking about how to handle high res scroll. Might as well hack together an initial implementation. Very WIP, but shows what is still needed here.
Testing things, it seems `PointerScrollWheelEvent` is emitted whenever a scroll is sent from the device, while `PointerAxisEvent` is only sent after accumulating change. So this impacts even clients not using the new protocol version, so they can get more precise scrolling from `wl_pointer::axis`.
In particular, this works in Firefox.
Issues:
* For clients not using the new protocol version, we need to accumulate `axis_value120` events into a `axis_discrete` event
- Where can this be handed? Probably somewhere in Smithay and not the compositor?
* Not obviously something libinput backend can deal with. Handle in `PointerTarget<D> for …
> High res scrolling support

- anvil/src/input_handler.rs
Fixes that toggling decorations may reach `unreachable!()` and thus panic `anvil`.
> Fix: toggle decorations in anvil

- anvil/src/shell/xdg.rs
- smallvil/src/handlers/xdg_shell.rs
- src/desktop/wayland/popup/manager.rs
- src/wayland/shell/xdg/mod.rs
(includes #1255 for easier testing)
Popup unconstraining, now in Smithay proper. Good enough to be used in Smallvil even!
See Smallvil and Anvil impl, also [here's](https://github.com/YaLTeR/niri/compare/main...popups) a niri impl. No reactive updates in Smallvil and Anvil, but they are straightforward to add (niri has one on commit).
Loosely based on cosmic-comp's impl, used with @Drakulix's permission.
All you need to do is pass the target rect in the positioner's coordinate system. It handles the rest. If you don't want resizes, simply unset the resize bits on the positioner.
> Popup unconstraining

- src/desktop/wayland/popup/manager.rs
The popup positioner coordinate system is relative to the parent's geometry, so we should not subtract it.
> Do not offset popup coordinates by the parent's geometry

- src/backend/allocator/dmabuf.rs
- src/backend/allocator/dumb.rs
- src/backend/allocator/gbm.rs
- src/backend/allocator/vulkan/mod.rs
- src/backend/egl/display.rs
- src/wayland/dmabuf/dispatch.rs
- src/wayland/dmabuf/mod.rs
Version 5 of the protocol requires an error if planes do not all have the same modifier: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/224.
Separate modifiers per-plane is apparently a historical artifact that isn't actually supported in drm in the kernel. So it makes sense to remove it from the `Dmabuf` abstraction in Smithay. The `Buffer` implementation already used just the modifier for the first plane.
This has the logic to produce an error when version 5 of the protocol is exposed, but still creates the global with version 4 until wayland-protocols is updated.
> dmabuf: Store single modifier, instead of storing per-plane

- src/backend/allocator/gbm.rs
#1266 removed the modifier argument of `add_plane`, but missed one usage in the legacy gbm path
> gbm: fix legacy dmabuf export

- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/shell/xdg/handlers/surface/popup.rs
This reverts commit f1cd2dc813c85f96c08d9c2b1630901aa9789f07.
After that commit, dismissing any right click menu or tooltip in GTK 4 causes the app to ignore pointer events until it's refocused, in both Anvil and niri. Not sure who is wrong. Reverting for now.
cc @bwidawsk
> Revert "popups: Emit a wl_pointer.leave when destroyed"

- src/backend/drm/compositor/mod.rs
This should fix #1275 by recognizing `gbm_bo_write` failed, but only fixes number 3 as mentioned in  https://github.com/Smithay/smithay/issues/1275#issuecomment-1890473451
> drm: fix cursor buffer write error check

- src/input/keyboard/mod.rs
The internals of `KeyboardHandle::input` have been exposed as 2 separate functions `KeyboardHandle::input_intercept` and `KeyboardHandle::input_forward` to allow for asynchronously deciding if a key event should be forwarded to the client or not.
It was not possible to do this using `KeyboardHandle::input` because this decision must be done in the `filter` closure before returning the result of the decision.
I'm using an external toolkit that handles keyboard shortcuts and I cannot synchronously decide what key events should be forwarded or not. I have to send a message to another thread and wait for the response to come on the event loop. Blocking in the `filter` closure and waiting for an answer is not an option because I'm also blocking the event loop and I will end up in a deadlock. …
> Asynchronous input filtering

- src/wayland/security_context/listener_source.rs
Without this patch, only a single connection is ever accepted on the security context listen fd.
cc @ids1024
> security-context: Poll the right fd

- Cargo.toml
With `drm`, `gbm`, and `input` updated to use the same bindings across platforms, building Smithay on RISC-V or OpenBSD should be a bit easier.
> Update `input` to 0.9

- src/backend/renderer/multigpu/gbm.rs
- src/backend/renderer/multigpu/mod.rs
Right now the `GpuManager` only re-enumerates devices, if the user requests a node it doesn't know already.
This means it will lock resources, even if e.g. the node is removed from the `GbmGlesBackend`.
While this is fine for the `EglGlesBackend`, as there really is no notification of a removed rendering device (except for egl errors trying to use it) and enumeration being expensive, this is bad for the Gbm-backend, as for example the nvidia driver will keep the gpu active as long as EGL resources do exist.
As such introduce a way for the api to trigger re-enumeration on the next render step.
> multigpu: Allow api to trigger re-enumeration

- src/desktop/wayland/popup/manager.rs
Turns out popup grabs with IMEs are kinda not working in Smithay, but they don't have to crash the compositor.
This particular thing happens if an IME with a popup is spawned while a popup with a grab is open, and you try to call this function. For whatever reason. Not completely sure. Let's not crash anyway.
> Don't panic if parent is missing in find_popup_root_surface()

- anvil/src/input_handler.rs
- anvil/src/x11.rs
- src/backend/x11/mod.rs
- src/backend/x11/window_inner.rs
- src/input/keyboard/mod.rs
Expose FocusIn and FocusOut events through the X11 backend. Focus was already exposed on the Winit backend, so why not have the same on the X11 one. Also, a helper function has been added that returns the key codes of currently pressed keys.
My use case:
When I run the compositor in a window under X11 and I Alt+Tab, the Alt key is permanently stuck in the pressed state because the host compositor never sends me a release event. When I lose focus, I want to iterate over all the keys that are being pressed and artificially release them, so that next time I focus the window no keys are stuck down.
> Expose focus events through the X11 backend

- anvil/src/udev.rs
- anvil/src/x11.rs
- examples/buffer_test.rs
- src/backend/egl/display.rs
- src/backend/renderer/multigpu/egl.rs
- src/backend/renderer/multigpu/gbm.rs
- src/backend/winit/mod.rs
- src/backend/x11/mod.rs
Attempt at "fixing" (at least in the context of smithay) #1263 as reported by @YaLTeR.
Essentially this works around this part of the [`eglGetPlatformDisplay`-docs](https://registry.khronos.org/EGL/sdk/docs/man/html/eglGetPlatformDisplay.xhtml) as well as we can:
> Multiple calls made to eglGetPlatformDisplay with the same parameters will return the same EGLDisplay handle. 
There is no way to disallow other code to call `eglGetPlatformDisplay` behind our back, so I felt like this method warrents an `unsafe`. However this is debatable.
1. We do have places where `EGLDisplay::new` is called inside safe code, which is difficult to propagate (e.g. `EglGlesBackend::enumerate`).
2. Calling `eglGetPlatformDisplay` requires unsafe code in other code or libraries anyway.
3. `EGLDisplay`s broken …
> egl: Fix multiple references to same EGLDisplay

- src/backend/egl/display.rs
Somehow I removed this during refactoring, so now the `unwrap` in 231/232 can panic without this line.
> egl: Fix dead weak handles

- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/backend/libinput/mod.rs
- src/input/keyboard/mod.rs
- src/input/mod.rs
- wlcs_anvil/src/main_loop.rs
An attempt to make the leds on the keyboard to show up.
~~As I am normally not working on the input side this might be complete bogus, but at least it seems to work for me.
What I am especially uncertain at is the `update_led` function on the keyboard input event, but it also did not
feel correct to add it to the generic device trait.~~
Ok, so this should now represent a much saner implementation. The `SeatHandler` now has a notify function which
is automatically called on changes to the led state. The only remaining thing downstream has to do is to track all
keyboards, listen to the led state updates and update all keyboard led states.
> input: add support for keyboard led state

- anvil/src/udev.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/surface/atomic.rs
- src/backend/drm/surface/legacy.rs
This should hopefully provide a fix for all kind of plane artifact issues after suspend/resume and dpms.
The comments on the single commits should be enough to describe the motivation behind the changes.
Just some warning, this breaks some existing behavior by fixing an issue I found in the `reset_state` function of the atomic surface. Before that change every call to `reset_state` would make the surface require a commit.
With this fixed `DrmCompositor` will no longer always submit a complete state after calling `reset_state`
which might result in artifacts.
The correct way to resolve this is to call `DrmCompositor::reset_state` instead directly on the surface.
This will make sure the next call to `render_frame`/`queue_frame` will produce a full update, updating
all planes.
> Fix plane artifacts

- .github/workflows/ci.yml
- Cargo.toml
- src/backend/drm/compositor/mod.rs
- src/backend/renderer/gles/version.rs
- src/wayland/shell/xdg/handlers/surface.rs
Looks like the IndexMap is used in all these places for a stable iterator order, possibly even z-order in the compositor, so shift_remove is likely the expected behavior here.
> chore: Fix deprecated indexmap remove method

- anvil/src/state.rs
- smallvil/src/handlers/mod.rs
- src/wayland/output/handlers.rs
- src/wayland/output/mod.rs
Lets compositors know when a new `wl_output` is bound. Useful for implementing protocols with similar semantics to `wl_surface.enter` where newly bound `wl_output`s must participate in some events immediately.
> Add OutputHandler trait

- src/desktop/wayland/popup/manager.rs
when searching for a popup of a surface we have to test if the popup we found is still alive or otherwise we might return a destroyed popup.
normally this wouldn't be an issue and the popup should get cleaned up eventually, but it can race against cleanup when a surface is re-used. re-using the surface requires that the surface has no buffer attached on the first commit, so it can happen that directly after the popup is destroyed a NULL buffer is committed. In this case we could end in a situation where we try to send the initial configure to the dead popup and afterwards skip sending the configure to the re-used popup.
fixes deadlock in epiphany (Gnome Web) when selecting an history entry in the title bar.
> desktop: check if popup is still alive

- anvil/src/input_handler.rs
- src/backend/renderer/gles/mod.rs
- src/backend/renderer/mod.rs
This inverts flipped 90 and 270 to match the expected result.
I also refactored the texture matrix in general and added some tests.
The main reason was that weston-transformed seems to be broken on 90 and 270 degrees, making
me believe that I regressed that...sigh
On the plus side we now have some unit tests for the matrix.
> gles: fix texture rotations

- src/utils/clock.rs
rustix uses the same type(alias) for all platforms, so we can get rid of our target arch compilation
checks.
fixes the build on armv7
> fix build on armv7

- src/utils/clock.rs
sec/nsec types vary between platforms, luckily rustix already exports platform dependant type aliases.
fixes #1315
> utils: use sec/nsec types from rustix

- .github/workflows/ci.yml
- src/backend/renderer/utils/wayland.rs
Makes `with_renderer_surface_state` not panic, should there have never been an import. (Which can be particularly easy to trigger with unmapped Xwayland windows.)
> fix: Don't unwrap RendererSurfaceState

- src/backend/renderer/gles/mod.rs
When calling copy_framebuffer with a winit backend and GlesRenderer the following error occurs:
```
2024-02-08T18:20:53.020809Z ERROR backend_winit{window=94319884276496}:egl{platform="PLATFORM_WAYLAND_KHR" version=(1, 5)}:egl_context{ptr=94319886251776}:renderer_gles2: smithay::backend::renderer::gles: [GL] GL_INVALID_OPERATION in glReadBuffer(invalid buffer GL_COLOR_ATTACHMENT0)
thread 'main' panicked at smallvil/src/winit.rs:30:10:
Failed to map framebuffer: UnsupportedPixelFormat(DrmFourcc(AR24))
```
Full Backtrace: https://gist.github.com/Meptl/084c4d5c78408df6600a4619466c912a
To test, you can use this patch which modifies smallvil slightly to create a screenshot at `foo.png` when you press '3' on the keyboard:
<details>
<summary>Click to expand</summary>
```
diff --git …
```
> Fix copy_framebuffer for GlesRenderer

- src/wayland/idle_notify/mod.rs
- src/wayland/mod.rs
Taking over from #1021, cc @PolyMeilex @chrisduerr.
Changes:
1. Added `notify_activity(&Seat)`, kept the `WlSeat` method under a different name.
2. Fixed a bug where uninhibiting didn't reset idle state resulting in two subsequent `resumed` events (forbidden by the protocol).
3. Added dead `WlSeat` data cleanup.
4. Some other minor things.
Impl in niri: https://github.com/YaLTeR/niri/compare/main...idle-notify
> Implement ext-idle-notify

- src/wayland/selection/seat_data.rs
Primary selection is available only since v2, so don't send the events for v1 devices.
> seat/data_control: ensure version for primary selection

- src/wayland/content_type/mod.rs
I have no idea why I added it there in the first place, it's never used, the value is always Some()
> Replace Option with Weak in content type protocol

- Cargo.toml
- src/wayland/dmabuf/mod.rs
The code to raise a protocol error if planes had different modifiers is already present, this just needed `wayland-protocols` to support version 5.
> Advertise dmabuf v5

- src/desktop/wayland/window.rs
This fixes a bug with the latest version of Epiphany not rendering/working, when run in XWayland, on anvil or cosmic-comp, as reported on https://github.com/Smithay/smithay/pull/1319. Presumably it fixes similar issues reported with other clients; not sure why this doesn't break XWayland more consistently...
`xtrace` shows `ConfigureNotify` was being sent with a size of `(0, 0)` because of this. If `Window::bbox` calls `X11Surface::bbox`, the behavior should be the same as it was before the `Window` change.
This probably isn't the best way to do things, with a `bbox` field that's only used for Wayland toplevels. Not sure what would be better.
> desktop/window: Fix `bbox()` for XWayland Windows

- src/input/pointer/mod.rs
when nothing is focused we need to reset the cursor image. this has been accidentally removed during touch re-factor.
before the touch re-factor the cursor would have been reset whenever the focus changes, but it should be fine to
only reset it when there is no focus at all.
From the spec:
> When a seat's focus enters a surface, the pointer image is undefined and a client should respond to this event by setting an appropriate pointer image with the set_cursor request.
> input: reset pointer image on leave

- anvil/src/shell/mod.rs
- src/backend/renderer/utils/wayland.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/hook.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/tree.rs
[[wayland.compositor] Removable hooks](https://github.com/Smithay/smithay/commit/2f1833259db1737c3613bf4b3344221570e60fee) - Adds `HookId`, and a way to use it to unregister the hooks. Also brings destruction hook inline with other hooks by unlocking the mutex during a hook call.
[[wayland.compositor] Use lock_user_data for all methods](https://github.com/Smithay/smithay/commit/a7e52006726aceb3070b8e0e5140d990dfc64a7e) - While at it, use user data getter added in previous commit in other unrelated functions to clean up the code a bit.
> [wayland.compositor] Removable hooks

- anvil/src/state.rs
- src/wayland/mod.rs
- src/wayland/xdg_foreign/handlers.rs
- src/wayland/xdg_foreign/mod.rs
This also includes a SCTK test client, not sure if we want that in the codebase, but I committed it for now, we can just drop the commit as needed.
> [wayland] Implement XdgForeign

- src/xwayland/xwm/surface.rs
I guess this is a typical copy-paste bug as someone forgot to change the body of this function to return the right thing.
> Fix the X11 window instance getter returning the class instead of the instance

- src/desktop/wayland/layer.rs
- src/desktop/wayland/utils.rs
- src/desktop/wayland/window.rs
Stumbled upon these looking into https://github.com/Smithay/smithay/issues/1352.
Some clear mistakes (like only using the `filter` closure in `under_for_surface_tree`), but mostly just some inconsistencies handling `WindowSurfaceType`.
Draft, because this needs more testing.
> Fix various slight tree-iteration issues

- src/desktop/wayland/utils.rs
TraversalAction::Break will stop the traversal early, which can result in us missing some sibling surfaces. Skipping the children is fine as they are also unmapped.
fixes #1360
> desktop: test sibling surfaces for input

- src/wayland/dmabuf/dispatch.rs
- src/wayland/shm/handlers.rs
Currently, the callback is called when the client makes a destroy request, but not when the client disconnects and everything is destroyed implicitly.
> trigger `BufferHandler::buffer_destroyed` on client death

- src/input/keyboard/modifiers_state.rs
I guess its absence was an oversight / nobody needed it so far and not a deliberate choice.
> input: Add "ISO level 3 shift" modifier

- src/input/pointer/mod.rs
Smithay doesn't reset the cursor image, when we replace focus. This can be the default thing that happens with e.g. swaybg or cosmic-bg running, causing the last cursor image to be stuck, if any newly entered surface doesn't care to set a new image.
Lets reset on swapping focus as well, not just when nothing is focused.
> pointer: Reset image on focus change

- anvil/src/input_handler.rs
- smallvil/src/input.rs
The usual value for one wheel tick is 15, not 3. This can be verified with Firefox by scrolling on a TTY backend vs. on the winit backend (since this particular fallback is used on the winit backend).
> {an,small}vil: Fix winit scroll values

- src/backend/renderer/gles/mod.rs
- src/backend/renderer/gles/shaders/mod.rs
- src/backend/renderer/gles/uniform.rs
Useful/required for implementing custom shaders. The safety comments are a bit non-specific but I'm not sure what the specific conditions are.
> Make a few rendering things public

- anvil/src/shell/grabs.rs
- smallvil/src/grabs/move_grab.rs
- smallvil/src/grabs/resize_grab.rs
- src/desktop/wayland/popup/grab.rs
- src/input/keyboard/mod.rs
- src/input/pointer/grab.rs
- src/input/pointer/mod.rs
- src/input/touch/grab.rs
- src/input/touch/mod.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/selection/data_device/dnd_grab.rs
- src/wayland/selection/data_device/server_dnd_grab.rs
- src/wayland/xwayland_keyboard_grab.rs
`PointerGrab::unset` is called when a grab is removed or replaced with another grab.
This fixes https://github.com/pop-os/cosmic-comp/issues/403. I've seen issues with one or two of cosmic-comp's grabs if something isn't cleaned up correctly when `unset` is called, so this should help with them, as well as some other Smithay grabs.
I still need to add this for keyboard and touch grabs, but it seems workable.
> Add `unset` method to input grab traits

- src/wayland/cursor_shape.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
This fixes calls to `set_cursor` during drag-and-drop. Nautilus is a good client to test this with, though most drag-and-drop clients should work.
The Wayland spec doesn't seem that specific about how `set_cursor`, pointer focus, and drag-and-drop interact. But this seems to mostly match Sway: the surface loses pointer focus at the start of drag-and-drop, but can still set the cursor.
I'm not sure if this is likely to be desirable or undesirable when there is a grab other than a drag-and-drop grab. It could be restricted to drag-and-drop, but there is not currently any way in Smithay to check what the drag is, or if there is a drag-and-drop operation. But it should be possible to downcast the `dyn PointerGrab<D>`, I guess.
> Allow `set_cursor` when there is a pointer grab for client

- src/input/keyboard/mod.rs
- src/input/pointer/mod.rs
- src/input/touch/mod.rs
It seems I missed one place where a grab could be removed.
This fixes an issue on cosmic-comp where a surface being destroyed during a DnD drag from that surface would result in the DnD surface still displaying. (For instance, closing cosmic-workspaces with a keybinding while dragging).
(I guess the `&mut D` argument to `with_grab` is needed after all... I'll probably not create another dozen PRs adding and removing it again. It's an internal API anyway.)
> Call `*Grab::unset` when grab is removed due to surface not being alive

- anvil/src/drawing.rs
- anvil/src/shell/element.rs
- src/backend/renderer/element/surface.rs
- src/backend/renderer/utils/wayland.rs
- src/desktop/space/element/mod.rs
- src/desktop/space/element/wayland.rs
- src/desktop/space/mod.rs
- src/desktop/space/wayland/layer.rs
- src/desktop/space/wayland/window.rs
- src/desktop/space/wayland/x11.rs
Attempt at solving parts of the discussion in https://github.com/Smithay/smithay/pull/1393 and observed profiling hot-paths, by copying from the `RendererSurfaceState` once on render element creation instead of accessing the surface's user-data all the time for the `WaylandSurfaceRenderElement`.
> elements/surface: Snapshot render state

- .github/workflows/ci.yml
- Cargo.toml
- anvil/Cargo.toml
- smithay-drm-extras/Cargo.toml
There's also a new `ash` release, but that seems to require some changes to use. So I left that for now.
> Update `drm`, `gbm`, `image`; `xkbcommon`/`x11rb` deps of Anvil

- anvil/src/state.rs
- src/wayland/input_method/input_method_handle.rs
- src/wayland/input_method/input_method_popup_surface.rs
- src/wayland/input_method/mod.rs
- src/wayland/text_input/text_input_handle.rs
Each call to `set_text_input_rectangle` changes the position of the popup and also will result in popup repositioning, thus notify users when such request occurs.
The location and text cursor area where separated, since one is used for the rendering, and the other one is original location.
--
Use case: https://github.com/YaLTeR/niri/pull/295
> Notify when InputMethod::PopupSurface changes location

- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/xwayland/mod.rs
- src/xwayland/x11_sockets.rs
- src/xwayland/xserver.rs
- src/xwayland/xwm/mod.rs
This method, while undocumented, is a lot more robust than an intermediate shell. It works by passing a pipe to the Xwayland cmdline invocation. When Xwayland is ready, it writes the display number and a newline to the pipe.
While we're at it, we can remove the hard dependency on Calloop, so that the Xwayland instance can be used with other event loops (my compositor uses `mio`). This isn't enough to achieve that completely, since `X11Wm::new` takes a `LoopHandle` as an argument. I will address that in a separate PR.
c.f. weston's implementation: https://gitlab.freedesktop.org/wayland/weston/-/blob/main/frontend/xwayland.c
> Run Xwayland using `-displayfd` and a pipe

- src/backend/renderer/element/solid.rs
I need this to be able to programmatically replace a solid color element with another element in my rendering code.
> Add getters for SolidColorBuffer/Element color

- src/wayland/virtual_keyboard/mod.rs
- src/wayland/virtual_keyboard/virtual_keyboard_handle.rs
Remnants of this commit: https://github.com/Smithay/smithay/commit/5a0b08c804d5f7ea045b1beddf7fe8a4870fb2a7
It removed the code that decremented or even just accessed the counter, leaving it to overflow, which causes panics with overflow checks.
Intended to fix https://github.com/YaLTeR/niri/issues/316.
cc @chrisduerr
> virtual_keyboard: Remove unused instance tracking

- src/utils/geometry.rs
This fixes the method clamping down using the size, not with the positions of the right/bottom edges.
> Fix `Point::constrain` clamping at wrong values

- src/backend/renderer/gles/shaders/implicit/texture.frag
- src/backend/renderer/pixman/mod.rs
Not sure if this was intentional, but this color is supposed to be premultiplied, so the color components cannot be above the alpha.
> Correct debug tint color

- src/backend/renderer/element/surface.rs
- src/backend/renderer/gles/texture.rs
These seem to be sufficient for me in niri to build a matrix that transforms the shader coordinate space to the geometry coordinate space, taking viewporter src and buffer transform into account.
> Add getters for some `WaylandSurfaceRenderElement` properties

- anvil/src/shell/mod.rs
- anvil/src/shell/xdg.rs
- src/wayland/compositor/tree.rs
Even when handling request for a surface, `surface.client()` may return `None`. This occurs, for example, if a protocol error is signaled; the surface remains alive for some time, but `client()` returns `None` immediately after `post_error` was called.
I just added early returns in the three places I found in the codebase, where a client for a surface was previously being unwrapped.
I didn't add the check, if a surface `is_alive()` before calling the `commit`, discussed in #1407, as I didn't see value in doing the extra check anymore. Let me know if I should still add the check anyways.
Fixes #1407
> Avoid unwraping clients from surfaces

- src/input/pointer/mod.rs
it's very easy to accidentally forget the `frame =` reassignment when working with an `AxisFrame`, especially because it doesn't actually "consume" it, since it is `Copy`.
```rs
let mut frame = AxisFrame::new(evt.time_msec()).source(evt.source());
if horizontal_amount != 0.0 {
// this line does nothing but it doesn't warn me
frame.relative_direction(Axis::Horizontal, evt.relative_direction(Axis::Horizontal));
frame = frame.value(Axis::Horizontal, horizontal_amount);
}
```
> add #[must_use] to AxisFrame

- anvil/src/shell/mod.rs
- anvil/src/shell/x11.rs
- anvil/src/state.rs
- src/wayland/mod.rs
- src/wayland/xwayland_shell.rs
- src/xwayland/xwm/mod.rs
- src/xwayland/xwm/surface.rs
Depends on #1350 (but only trivially).
The xwayland shell protocol moves the responsibility of setting the "xwayland_surface" role on the wl_surface from the x11 side of the connection to the wayland side. Among other things, this avoids the xwm racing the lifecycle of the surface.
Since we can check the serial with a commit hook, this also removes the need for a ugly idle callback in the `Xwm`, and may allow for better separation of concerns in the future, for example moving the association state tracking out of Xwm.
Without the idle callback, we may be able to remove the hard dependency on calloop in the xwayland stack (which is my ulterior motive). It's still required for `send_selection` - I'll attempt to figure those issues out in another PR.
> Implement the xwayland shell protocol

- src/backend/renderer/utils/wayland.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/tree.rs
The protocol says a buffer that is attached but then replaced without being committed should not get `release`. So there shouldn't be any reason to call `release` in `merge_into` or `cleanup`.
Once the surface is comitted, `RenderSurfaceState::update_buffer` will create a `Buffer`. So it seems everything should be correct to ensure a buffer is released once and only once, when there are no references.
> Call `wl_buffer::release` only in drop impl of `renderer::utils::Buffer`

- anvil/src/shell/grabs.rs
- src/input/touch/grab.rs
- src/input/touch/mod.rs
- src/wayland/selection/data_device/dnd_grab.rs
- src/wayland/selection/data_device/server_dnd_grab.rs
The event structs were already defined and used in `TouchTarget`, but there was no way to actually send them.
I would also add backend support for getting these events from libinput, but apparently that still doesn't exist:
https://gitlab.freedesktop.org/libinput/libinput/-/issues/746.
> Add `shape`/`orientation` to `TouchHandle` and `TouchGrab`

- src/backend/allocator/gbm.rs
- src/backend/drm/gbm.rs
Buffers created via `gbm_bo_create` might return (errornous or actual) modifiers, which can then lead to errors trying to attach them to drm or exporting in dmabuf, which will then suddenly have modifiers.
So lets track if the creation method allows for modifiers or not.
This fixes a current bug with virgl, that zero-initializes the modifier field and thus returns `LINEAR`. This has been previously been bugs in multiple drivers and some drivers are intentionally returning the internally used modifier.
This proposed solution is equivalent to what other compositors are doing, e.g.: https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/bf86110fc5615bfd1af46e95cf81ac720ecac307
> gbm: Force implicit modifiers for old api

- src/backend/renderer/utils/wayland.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/tree.rs
Revert "Call `wl_buffer::release` only in drop impl of `renderer::utils::Buffer`"
`SurfaceAttributes::merge_into` is called during `WlSurface::commit`.
So if no one (like `on_buffer_commit_handler`) processed an existing buffer in the mean time we have to
send a release or no one will do that for a committed buffer.
This reverts commit f25bcd892e6785ec9ce6b57e55843545722921f6.
> Release overriden buffers (again)

- src/xwayland/xwm/mod.rs
https://github.com/Smithay/smithay/pull/1351 accidentally dropped the `XwmHandler::map_window_notify` (which admittedly was at a very unintuitive place, this is now much cleaner), breaking compositors making use of it. Lets reintroduce it.
> xwm: Fix missing map_window_notify callback

- src/wayland/selection/data_device/mod.rs
- src/wayland/selection/primary_selection/mod.rs
- src/wayland/selection/seat_data.rs
I wanted to change where these are called in `cosmic-comp` to workaround an issue. But by not just calling it when keyboard focus changes, it created a flood of `offer` events.
It would be possible to add a getter for the focus, but it seems reasonable just to add a test here to check if it has changed. I assume there's no problem doing noting if the focus is the same as the current one.
> Check if focus is unchanged in `set_data_device_focus`/`set_primary_focus`

- anvil/src/input_handler.rs
- anvil/src/shell/element.rs
- anvil/src/shell/grabs.rs
- anvil/src/shell/ssd.rs
Before this patch, `AnvilState<BackendData>`,
`AnvilState<Backend: crate::state::Backend>`, and `AnvilState<B>` are mixed up. This patch uses `AnvilState<BackendData>` for consistency.
> style: Use `AnvilState<BackendData>` everywhere

- anvil/src/shell/mod.rs
- src/wayland/xwayland_shell.rs
- src/xwayland/xwm/mod.rs
Since the `map_window_notify` doesn't ensure that a valid association is made between a X11Surface and a WlSurface we need to have a new way to associate them. But currently the `surface_associated` doesn't provide arguments that allow this association in the implementation side.]
This PR aim to fix thoses issues.
Note: It's currently doesn't work as expected since the execution order seems to be odd
> Fix the xwayland shell - X11Window to WlSurface association

- src/backend/renderer/element/surface.rs
- src/wayland/alpha_modifier/mod.rs
Previously the alpha modifier was not used anywhere within Smithay. The compositor possibly could handle the alpha value itself, but it's not clear how to do that when using `render_elements_from_surface_tree`. Nor is there an obvious reason not to handle this in Smithay.
The protocol leaves the exact blending space undefined. But multiplying here seems like a correct implementation.
> Multiply alpha modifier with alpha in `WaylandSurfaceRenderElement`

- anvil/src/shell/mod.rs
- src/wayland/xwayland_shell.rs
- src/xwayland/xwm/mod.rs
Also fixes, that the commit hook is added on every SetSerial call (xwayland re-uses surfaces).
cc @PapyElGringo, @colinmarc
> xwayland: Make hook implementation-detail

- src/input/pointer/mod.rs
- src/wayland/pointer_gestures.rs
- src/wayland/relative_pointer.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
Maybe it's just a personal preference, but every time I open seat logic code, and see some new protocol extension added in there it starts to overwhelm me a bit.
So spliting it up per protocol seems resonable.
Also this adresses my other main problem with reading seat code, the fact that data of the protocol is defined in `input::` module rather than next to the protocol implementation, which leads to constant jumping around. With this change state type definition is stored next to the logic.
> Move pointer protocol extensions logic to their corresponding modules

- anvil/src/input_handler.rs
- anvil/src/shell/grabs.rs
- smallvil/src/grabs/move_grab.rs
- smallvil/src/grabs/resize_grab.rs
- smallvil/src/state.rs
- src/desktop/wayland/popup/grab.rs
- src/input/pointer/grab.rs
- src/input/pointer/mod.rs
- src/input/touch/grab.rs
- src/input/touch/mod.rs
- src/wayland/selection/data_device/dnd_grab.rs
- src/wayland/selection/data_device/server_dnd_grab.rs
- src/wayland/tablet_manager/tablet_tool.rs
Surface position in global compositor space is not required to be rounded to logical integers. The compositor is free to put surfaces wherever. So, do not require an integer-logical position.
Not to be confused with:
* A subsurface can only be at an integer-logical offset from its parent surface (for now, at least). However, this is unrelated to the subsurface position in the global compositor space.
* A surface buffer is (generally expected to be) at an integer *physical* pixel position. However, this is unrelated to, and frequently isn't, an integer *logical* pixel position.
> Make input focus store f64 Logical global coords

- src/backend/renderer/gles/mod.rs
our assumption on implicit opaque rendering might
not hold for external shaders. in this case disable the short-cut and just use the default opaque region
logic to decide of blending should be enabled or not.
fixes #1455 
@YaLTeR please test
> gles: disable opaque short-cut for custom shaders

- src/backend/renderer/gles/mod.rs
this prevents resources from being kept alive unnecessarily
@ids1024 @Drakulix please test if this fixes the multi-gpu leak
> gles: clean-up on unbind

- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- examples/buffer_test.rs
- src/backend/allocator/format.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/mod.rs
- src/backend/drm/surface/gbm.rs
- src/backend/egl/context.rs
- src/backend/egl/display.rs
- src/backend/renderer/gles/mod.rs
- src/backend/renderer/glow.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/pixman/mod.rs
- src/wayland/dmabuf/mod.rs
This PR changes the dmabuf format handling so that the list populated over zwp_dmabuf stays in the same order as returned from the driver. Yes, this should in theory not make a difference, but it does on some drivers.
I noticed this because on a particular binary driver egl clients, using dmabuf v3, misbehaved. Further debugging
has shown that it semi-randomly selected formats, sometimes even YUV formats. This caused everything from wrong
color to performance issues.
Before this PR formats were only stable for a single run of the process as we used a HashSet which internally uses `RandomState`, resulting in different order each time we built the formats.
(Some of the changes are probably not needed, like the change to the plane format ordering, and just me being paranoid after debugging …
> Keep dmabuf formats in order

- src/backend/drm/compositor/mod.rs
- src/wayland/output/mod.rs
this has been introduced in the latest wayland-rs release and can safe a few cycles, especially for lists holding a lot of weak resources.
> perf: use WlWeak::is_alive instead of upgrading

- src/xwayland/xwm/surface.rs
Fix the `read_window_property_u32` because it's currently panic if `value32` is `None`
> Fix read_window_property_u32

- anvil/src/udev.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/device/mod.rs
- src/backend/drm/mod.rs
- src/backend/drm/surface/gbm.rs
- src/backend/drm/surface/mod.rs
- src/wayland/drm_lease/mod.rs
some drivers might offer multiple candidates as the primary plane for a CRTC. pick one and claim it so that we do not accidentially select the same plane multiple times.
fixes #1462
> drm: pick one primary plane if we have multiple

- src/backend/renderer/multigpu/mod.rs
This can error due to the buffer type being something other than an shm buffer, but it can also error for other reasons, like `BufferAccessError::BadMap`.
This fixes a panic when a client tries to use a buffer wit a file that isn't large enough. With this, there's no longer a panic and the client gets a protocol error as it is supposed to.
Fixes https://github.com/Smithay/smithay/issues/834.
> renderer/multigpu: Don't unwrap renderer error in `import_shm_buffer`

- src/wayland/shm/pool.rs
The actual mapping is mutable, so the placeholder should also be. Or writes will trigger a `SEGV` due to the page being unmapped when execution is resumed after the `BUS` handler.
This fixes uses of `with_buffer_contents_mut` if the file provided by the client isn't large enough. In particular the segfault reported in https://github.com/pop-os/cosmic-comp/issues/48.
> shm/pool: Map as writable in `nullify_map`

- .github/workflows/ci.yml
- src/input/keyboard/mod.rs
Similar to `PointerTarget::replace` this allows overriding the behaviour for custom targets.
> seat/kbd: Allow overriding replace behaviour

- anvil/src/udev.rs
- smithay-drm-extras/src/drm_scanner.rs
- smithay-drm-extras/src/drm_scanner/connector_scanner.rs
this changes scan_connectors to return a result
instead of unwrapping on failing to query the
drm devices resources.
> drm-extras: do not unwrap on scan errors

- src/backend/renderer/element/solid.rs
Without this, changing just the alpha in SolidColorRenderElement::from_buffer() doesn't damage the element.
I didn't test this in Smithay, but I bumped into this problem in my in-tree copy in niri.
> Return real alpha in SolidColorRenderElement

- .github/workflows/ci.yml
- src/wayland/xwayland_shell.rs
- src/xwayland/xwm/mod.rs
- We previously didn't re-export our renamed `X11Window` for the window id. This wasn't critical, because we reexport the whole `x11rb` crate, but it is needlessly confusing and breaks links in rustdoc.
- `surface_associated` is called in two places, one locks the surface state, the other doesn't. This is just asking for deadlocks.
- `surface_associated` is the only handler not taking a `XwmId`, making it unusable running multiple Xwayland servers. Lets fix that and also pass the whole `X11Surface` instead of just the window id to not force compositors to retrieve that manually.
- CI fix
- Reparenting apparently has the side-effect of mapping a window again, causing endless loops. So let's not do that.
> Various little xwm fixes

- src/backend/drm/compositor/mod.rs
always testing if the fence has been signaled
might hurt performance. we either use the exported fence fd or wait on it on the cpu anyway
> drm: remove implicit egl fence wait

- src/utils/clock.rs
> utils: Fix debug_assert for converting `Time`

- anvil/src/udev.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/mod.rs
- src/backend/drm/surface/mod.rs
some drivers might offer multiple cursor planes per CRTC. in this case try to use the first unclaimed plane and try to keep the same for as long as possible
> drm: pick one cursor plane if we have multiple

- src/wayland/seat/keyboard.rs
- src/wayland/seat/pointer.rs
- src/wayland/seat/touch.rs
It seems most protocols take a `wl_seat` as an argument rather than a capability type, but it seems reasonable for Smithay to expose this in some way to compositors still.
> Add `from_resource` to `KeyboardHandle`/`PointerHandle`/`TouchHandle`

- Cargo.toml
- anvil/Cargo.toml
- src/input/keyboard/modifiers_state.rs
This follows https://github.com/Smithay/smithay/pull/1365 in adding support for mod3. It doesn't appear that [the upstream PR](https://github.com/rust-x-bindings/xkbcommon-rs/pull/52) will be accepted anytime soon. I'm hoping that since this is basically a string constant addition this PR can go ahead and be merged to enable support.
(Closes #1464)
> input: add iso_level5_shift modifier

- src/xwayland/xwm/surface.rs
`NET_WM_STATE_HIDDEN` represents what xdg-shell calls `suspended`, not minimized. X11 windows typically expect to be unmapped and remapped, when asking for a specific minimized state, not for `_NET_WM_STATE_HIDDEN`. So lets rename this to be less confusing and more consistent.
> xwm: Rename HIDDEN state from minimized to suspended

- src/reexports.rs
`glow::Context` is exposed in the `GlowRenderer::with_context` and `GlowFrame::with_context` functions. So it should probably be re-exported.
> Add re-export for `glow`

- src/backend/renderer/element/mod.rs
- src/backend/renderer/gles/mod.rs
- src/desktop/space/mod.rs
- src/desktop/wayland/layer.rs
- src/desktop/wayland/window.rs
- src/utils/ids.rs
- src/wayland/compositor/hook.rs
- src/wayland/dmabuf/mod.rs
- src/xwayland/xwm/mod.rs
The current id generation logic may return an ID that is already in the HashSet.
I've also simplified the usage of `id_gen!`.
> utils: `id_gen!` optimization

- src/wayland/compositor/mod.rs
- src/wayland/pointer_constraints.rs
- src/wayland/session_lock/lock.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/viewporter/mod.rs
State should be applied on the actual commit. Pre-commit is too early, because the actual commit can and will be delayed by blockers. This would lead to inconsistent state where the current surface state is still old, but the protocol surface state is already new. Post-commit hook is the right place for this, it runs right after the current surface state is updated, and before the compositor commit handler is called.
After this change, my resize transactions impl in niri seems to work. Also, haven't run into any issues yet I think. But would be good for someone else to give this a try before merging. No compositor side changes are needed.
> Apply protocol state in post-commit hooks

- src/backend/renderer/multigpu/mod.rs
The Multitexture get method, is useful for accessing the internal texture reference for a given DrmNode and a specific Renderer.
Exposing this method will allow Custom Renders to leverage the smithay automatic import of buffer while implementing their own rendering logic on the output elements
> expose multitexture get method

- anvil/src/state.rs
- examples/buffer_test.rs
- examples/minimal.rs
- src/backend/drm/compositor/elements.rs
- src/backend/drm/compositor/mod.rs
- src/backend/renderer/color.rs
- src/backend/renderer/damage/mod.rs
- src/backend/renderer/element/memory.rs
- src/backend/renderer/element/mod.rs
- src/backend/renderer/element/solid.rs
- src/backend/renderer/element/surface.rs
- src/backend/renderer/element/texture.rs
- src/backend/renderer/gles/mod.rs
- src/backend/renderer/glow.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/pixman/mod.rs
- src/backend/renderer/test.rs
- src/backend/renderer/utils/wayland.rs
- src/desktop/space/mod.rs
- src/wayland/mod.rs
- src/wayland/single_pixel_buffer/handlers.rs
- src/wayland/single_pixel_buffer/mod.rs
This PR adds support for the `wp_single_pixel_buffer` protocol, based on #719 and  #988
Main difference to #988 is that this PR leaves the `WaylandSurfaceRenderElement` in tact instead of replacing it
with an enum holding a `TextureRenderElement` and `SolidRenderElement`. Some code might already depend
on the `WaylandSurfaceRenderElement` and moving everything over to the `TextureRenderElement` in a generic
way would just complicate the code. This also allows us to keep the wayland surface specific rounding while we
could lift that for the other render elements.
> Single pixel buffer (take 2)

- anvil/src/input_handler.rs
- src/backend/winit/mod.rs
- src/input/pointer/mod.rs
- src/utils/clock.rs
This should match the timestamp on input events from libinput. As far as I'm aware, this is more correct than using `0`.
> Use `CLOCK_MONOTONIC` instead of `0` for synthetic input events

- src/input/keyboard/mod.rs
- src/input/keyboard/modifiers_state.rs
The type is used as a public member of `ModifiersState`, and was public but not nameable. It seems better to add a `pub use` for the type.
> Expose `SerializedMods` type publicly in API

- src/input/keyboard/mod.rs
- src/input/touch/mod.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/pointer.rs
- src/wayland/seat/touch.rs
Before:
```mermaid
flowchart TD
WlKeyboard ---> KeyboardUserData --> KeyboardHandle --> KbdRc --> WlKeyboard
WlPointer ---> PointerUserData --> PointerHandle --> WlPointerHandle  --> WlPointer
WlTouch ---> TouchUserData --> TouchHandle ---> WlTouch
```
After:
```mermaid
flowchart TD
WlKeyboard ---> KeyboardUserData --> KeyboardHandle --> KbdRc -.-> |Weak| WlKeyboard
WlPointer ---> PointerUserData --> PointerHandle --> WlPointerHandle  -.-> |Weak| WlPointer
WlTouch ---> TouchUserData --> TouchHandle -.-> |Weak| WlTouch
```
> Fixup Seat ref count cycles

- src/output.rs
- src/wayland/output/handlers.rs
- src/wayland/output/mod.rs
- src/wayland/output/xdg.rs
Fix for output related reference cycles:
```mermaid
flowchart TD
WlOutput ---> OutputUserData --> OutputData --> A[Inner] --> WlOutput
ZxdgOutputV1 --> XdgOutputUserData --> XdgOutput --> B[Inner] --> ZxdgOutputV1
```
> Fixup output reference cycles

- anvil/src/input_handler.rs
- anvil/src/state.rs
- examples/seat.rs
- src/backend/renderer/utils/wayland.rs
- src/utils/geometry.rs
- src/utils/mod.rs
- src/wayland/compositor/handlers.rs
- src/wayland/compositor/mod.rs
- src/wayland/input_method/mod.rs
- src/wayland/output/handlers.rs
- src/wayland/output/mod.rs
- src/wayland/output/xdg.rs
- src/wayland/pointer_gestures.rs
- src/wayland/relative_pointer.rs
- src/wayland/seat/mod.rs
- src/wayland/seat/pointer.rs
- src/wayland/seat/touch.rs
- src/wayland/tablet_manager/mod.rs
- src/wayland/tablet_manager/tablet_seat.rs
- src/wayland/tablet_manager/tablet_tool.rs
- src/wayland/text_input/mod.rs
- src/wayland/viewporter/mod.rs
- src/wayland/virtual_keyboard/mod.rs
- src/xwayland/xwm/mod.rs
- src/xwayland/xwm/settings.rs
- src/xwayland/xwm/surface.rs
Alright, so this is an attempt at allowing Xwayland to be scaled similar to what KDE does.
The approach is quite generic though (and very similar in concept to what kwin does internally: https://invent.kde.org/plasma/kwin/-/merge_requests/2288).
We basically introduce a differentiation between the client's coordinate space and our `Logical` coordinate space. On every value reaching us from wayland or x11 we undo any scaling factor (saved in the `CompositorClientState`) and reapply it when sending values back.
This way we can pretend a client has an additional e.g. 2x scaling factor, decoupling the scale each client has from what it is telling us and allowing the compositor to override that seamlessly (without doing a bunch of annoying calculations itself).
To do these calculations …
> Add a new scalable client coordinate-space

- src/xwayland/xwm/mod.rs
This reverts commit c6aab182a3c9f106d9c7a0ea34187f90403e59e7.
@ids1024 pointed out that this is likely responsible for https://github.com/pop-os/cosmic-epoch/issues/835 and similar issues.
I remember the reason for this fix being some misbehaving clients on minimize, that would immediately restore themselves again. I can't reproduce this reverting just this commit with current cosmic-comp. Even if there is 1 in 10 clients, this is clearly an improvement to killing X11 clients and further issues should probably be debugged separately.
> Revert "xwm: Don't reparent on unmap"

- src/backend/allocator/format.rs
This gives read-only access to the underlying storage of `FormatSet`, to make it simpler for consumers to combine formats without having to reallocate.
> Add accessor for FormatSet's underlying storage 

- src/backend/x11/mod.rs
- src/utils/x11rb.rs
- src/xwayland/xserver.rs
- src/xwayland/xwm/mod.rs
This logs a tracing error if the X server is disconnected with a protocol  error, and logs the return status of the `Xwayland` subprocess (which also means properly reaping the pid). Having these logged (and logged alongside any other compositor errors) will hopefully help with debugging some issues.
This also adds a `disconnected` method to `XwmHandler` so the compositor knows when we lose connection to the X server. (See https://github.com/pop-os/cosmic-comp/pull/823 for a use case.)
> xwayland: Some improvements for handling of xserver crashes

- src/backend/winit/input.rs
- src/backend/x11/input.rs
Testing with this, horizontal and vertical scroll now seems to work expected on both winit and X11.
Fixes https://github.com/Smithay/smithay/issues/1524.
> winit, x11: Fix scroll direction

- src/backend/drm/node/constants.rs
- src/backend/drm/node/mod.rs
Fairly straightforward. `DRM_MAJOR` matched libdrm... but that is wrong: https://gitlab.freedesktop.org/mesa/drm/-/issues/1.
NetBSD still lacks libinput, libudev, or a way to use Smithay (non-nested) practically without those.
> drm: Update for NetBSD

- Cargo.toml
- src/utils/hook.rs
- src/utils/mod.rs
- src/wayland/compositor/mod.rs
- src/wayland/compositor/tree.rs
- src/wayland/mod.rs
- src/wayland/shm/handlers.rs
- src/wayland/shm/mod.rs
- src/wayland/xdg_toplevel_icon.rs
Draft, as it awaits next wayland-protocols release
> wayland.xdg_toplevel_icon: Initial implementation

- anvil/src/input_handler.rs
- examples/seat.rs
- src/backend/input/mod.rs
- src/backend/libinput/mod.rs
- src/backend/winit/input.rs
- src/backend/x11/input.rs
- src/backend/x11/mod.rs
- src/desktop/wayland/popup/grab.rs
- src/input/keyboard/mod.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/seat/keyboard.rs
- src/wayland/xwayland_keyboard_grab.rs
It seems good to use a dedicated type for keycodes, particularly given there's two conventions for keycodes, offset by 8. So there's ambiguity about what the numberic value of the keycode actually represents.
We might prefer to use the Wayland value rather than the X11 version like `xkeysym::KeyCode` uses. But it would complicate things to have two different keycode types, and the code that calls `kbd.key` already is converting from `Keycode`.
> Use `Keycode` type consistently for representing keycode

- Cargo.toml
- src/backend/egl/display.rs
- src/backend/egl/ffi.rs
- src/backend/renderer/pixman/mod.rs
`once_cell::sync::Lazy` can be further replaced by `std::sync::LazyLock` once MSRV is bumped above 1.80.
> Replace `lazy_static` with `once_cell::sync::Lazy`

- anvil/src/shell/mod.rs
- anvil/src/state.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- src/backend/renderer/utils/wayland.rs
- wlcs_anvil/src/main_loop.rs
fixes the regression introduced in https://github.com/Smithay/smithay/pull/1123#issuecomment-1953661036
(not that is was working correctly before, but pointer was broken at bit less)
what I do not like is all the manual plumbing in the Dnd handling, handling this in smithay will require re-structuring a few things. From the spec of DnD start:
> The icon surface is an optional (can be NULL) surface that provides an icon to be moved around with the cursor. Initially, the top-left corner of the icon surface is placed at the cursor hotspot, but subsequent wl_surface.attach request can move the relative position.
According to this we need the cursor hotspot at the start of the grab to initialize the DnD icon offset. But as the hotspot is stored in the current pointer surface we can no access …
> fix buffer offset handling

- Cargo.toml
- src/backend/x11/extension.rs
- src/backend/x11/mod.rs
- src/backend/x11/window_inner.rs
The winit backend (and libinput backend) already don't produce key repeat events like this.
> x11: Use xinput2, and ignore key repetition

- src/wayland/foreign_toplevel_list/mod.rs
This is useful for other protocols building on top of `ext_foreign_toplevel_list` to figure out, for which `ExtForeignToplevelHandleV1`s events need to be send.
> ext_foreign_toplevel_list: Allow to retrieve resources

- src/input/keyboard/mod.rs
See commits messages for descriptions of the changes here. The last commit is potentially more controversial than the earlier ones; if it's an issue, I think the `Xkb` changes in the others are a good improvement at least.
> Don't hold lock in `input_intercept` callback and don't expose `xkb::` types in safe API

- src/backend/drm/device/atomic.rs
- src/backend/drm/surface/atomic.rs
Fixes https://github.com/Smithay/smithay/issues/1374.
> drm/atomic: Update connector prop mapping in `reset_state()`, and refactor prop mapping code a bit

- src/wayland/shell/xdg/mod.rs
It looks like `initial_decoration_configure_sent` field ended up in both `popup` and `toplevel` states, which is wrong. Decoration configure refers only to toplevels
> xdg-shell Fix definition of initial_decoration_configure_sent

- anvil/src/input_handler.rs
- anvil/src/shell/mod.rs
- anvil/src/shell/xdg.rs
- anvil/src/state.rs
- smallvil/src/handlers/xdg_shell.rs
- src/wayland/shell/xdg/mod.rs
Just a simple helper to reduce typemap magic a little bit.
Technically, this needlessly hides deadlocky `compositor::with_states`, but I doubt it matters if `send_configure`  usually called right after this check hides `with_states` already, if anything this reduces the chance of someone calling `send_configure` in `with_states` callback where needed initial configure value is available.
This also fixes Anvil sending configure to early during initial configure dance, whenever fullscreen/maximize requests are retrieved, but guarding the configure with `if is_initial_configure_sent`.
> xdg-shell: `is_initial_configure_sent` getter

- src/backend/drm/device/atomic.rs
https://github.com/Smithay/smithay/commit/88cdf9bd7d9c3550d16aa7b291486b9b4471e1c0 introduced a deadlock when creating AtomicDrmDevice, as https://github.com/Smithay/smithay/blob/88cdf9bd7d9c3550d16aa7b291486b9b4471e1c0/src/backend/drm/device/atomic.rs#L122 causes a deadlock in https://github.com/Smithay/smithay/blob/88cdf9bd7d9c3550d16aa7b291486b9b4471e1c0/src/backend/drm/device/atomic.rs#L185, since the `mapping` is dropped too late. this changes it to be dropped earlier.
> fix deadlock in AtomicDrmDevice

- src/backend/renderer/multigpu/gbm.rs
- src/backend/renderer/multigpu/mod.rs
A surface itself does not have a format, it is implicitly defined by the currently attached buffer. So whenever we cache something that depends on that format we have to clear the cache if the format changes.
~~This might explain all kind of strange issues when going between direct scan-out and composition where it is not
unlikely that the format changes.~~ Might not happen so often as mesa does not implicitly change format afaik
@YaLTeR Thanks for reporting the detailed reproduction in `#smithay`
> multigpu: reset texture on surface buffer format change

- anvil/src/shell/mod.rs
- anvil/src/udev.rs
- src/backend/allocator/dmabuf.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/device/fd.rs
- src/backend/renderer/sync/mod.rs
- src/backend/renderer/utils/wayland.rs
- src/wayland/compositor/tree.rs
- src/wayland/drm_syncobj/mod.rs
- src/wayland/drm_syncobj/sync_point.rs
- src/wayland/mod.rs
So far just exposes the protocol but doesn't do anything. https://github.com/Smithay/smithay/pull/1327 does indeed make that part mostly painless instead of having impl bounds to deal with and a delegate macro.
> Add linux-drm-syncobj-v1 protocol

- src/wayland/shm/pool.rs
Fixes warning on nightly Rust.
> shm: Use `OnceLock` instead of `static mut`

- anvil/src/state.rs
- src/input/pointer/mod.rs
- src/wayland/pointer_constraints.rs
I noticed that at the moment, there seems to be absolutely no way to utilize the value of [zwp_locked_pointer_v1::set_cursor_position_hint](https://wayland.app/protocols/pointer-constraints-unstable-v1#zwp_locked_pointer_v1:request:set_cursor_position_hint), not least because there is no good way to be notified of when its state changes, but Smithay's pointer handling seems to have no way to actually inform it about a cursor position hint.
This PR fixes that, by adding a method to `PointerConstraintsHandler` to notify the downstream compositor, and a method to `PointerHandle` to update the location field. Because it keeps track of the old focus as a separate field, i reckon this isn't going to cause any issues, and if it does cause issues, it's entirely opt-in. …
> add pointer location hint

- src/wayland/drm_syncobj/mod.rs
This check was backwards, but that wasn't apparent since not all implementations use the same timeline for both.
> drm-syncobj: Fix check for acquire/release point order

- src/backend/drm/compositor/mod.rs
- src/backend/drm/device/legacy.rs
- src/backend/drm/surface/atomic.rs
- src/backend/drm/surface/legacy.rs
- src/backend/drm/surface/mod.rs
As discussed in https://github.com/Smithay/smithay/issues/1553.
This seems to be working okay, on atomic or legacy DRM. I'm still finishing the cosmic-comp support.
Not sure if `DrmCompositor::disable` should clear any other state. Or if `AtomicDrmSurface::clear_state` does anything that is unneeded here. Other compositors appear to vary slightly in which properties their atomic backends set/unset for DPMS.
> Add a `disable` method to `DrmSurface`/`DrmCompositor` for implementing DPMS

- src/wayland/output/mod.rs
we want to make sure the output integer scale
is always >= 1 after applying the client scale.
using min will do the opposite, so change to max
which will make sure we always return at least 1
or whatever scale we calculated
fixes #1559
> output: fix scale clamping

- src/output.rs
Provides a way to construct a `WeakOutput` that doesn't point to any output. Useful when `Output::from_resource` returns `None`, but the `WeakOutput` needs to be stored in a user data.
> Derive `Default` for `WeakOutput`

- Cargo.toml
- anvil/src/shell/mod.rs
- src/wayland/shell/xdg/mod.rs
- test_clients/Cargo.toml
- test_clients/src/bin/test_xdg_map_unmap.rs
- test_clients/src/lib.rs
As far as I can tell, the xdg initial configure dance has to be done every time a xdg surface remaps itself.
So this MR:
- introduced a simple `reset_initial_configure_sent` helper method for xdg_surface, that allows to reset `initial_configure_sent`/`initial_decoration_configure_sent` to `false`.
- fixes remapping in anvil
- introduces a simple test client collection crate, for now it has a remap cycle client, that does the remapping in an endless loop.
---
Spec quote relating to this behavior:
```
For an xdg_surface to be mapped by the compositor, the following conditions must be met:
(1) the client has assigned an xdg_surface-based role to the surface
(2) the client has set and committed the xdg_surface state and the role-dependent state to the surface
(3) the client has committed a …
```
> xdg shell: Introduce `reset_initial_configure_sent()` 

- src/wayland/pointer_constraints.rs
I'm pretty sure this works fine as is, but just to be 100% sure that the reference cycle (see  #1552) gets broken properly, let's remove the constraint in the destructor rather than on event.
`remove_constraint` removes the constraint object from `wlsurface` user data, and as the constraint object contains the surface in its own user data this makes sure that the cycle is broken properly.
> wayland.pointer_constraints: Remove constraints in the destructor

- src/input/keyboard/mod.rs
- src/input/pointer/grab.rs
- src/input/pointer/mod.rs
- src/input/touch/grab.rs
- src/input/touch/mod.rs
- src/wayland/input_method/mod.rs
- src/wayland/selection/data_device/dnd_grab.rs
- src/wayland/selection/data_device/mod.rs
- src/wayland/selection/data_device/server_dnd_grab.rs
Allows the compositor to inspect which grab is currently active.
Use case 1: in niri I want to scroll the workspace left and right when hovering the mouse close to output edges with a DnD grab, but not with a regular click grab.
Use case 2: avoiding a weird case with libadwaita DnD/move conflict https://gitlab.gnome.org/GNOME/gtk/-/issues/7113 by checking if the active grab is a DnD grab specifically and denying the move request in that case.
```rust
let mut is_dnd_grab = false;
pointer.with_grab(|_, grab| {
is_dnd_grab = grab.as_any().downcast_ref::<DnDGrab<Self>>().is_some();
});
```
Debug impls are auto-generated with rust-analyzer (they want `D: 'static`).
> Add Pointer/Touch/KeyboardHandle::with_grab() and downcasting

- Cargo.toml
- src/wayland/shm/handlers.rs
- src/wayland/shm/mod.rs
Version 2 adds [release](https://wayland.app/protocols/wayland#wl_shm:request:release) request, we don't have to do anything with it in Smithay as it is marked as destructor.
Draft until next wayland-rs release
> wayland.shm: Add support for wl_shm version 2

- src/wayland/session_lock/lock.rs
- src/wayland/session_lock/surface.rs
Fix the reference cycle.
Found this with Tracy allocation profiling.
> session_lock: Change surface to Weak

- src/lib.rs
Just what it says on the tin - I noticed a few typos while reading the top-level docs.
> Fix for some typos/grammer in top-level crate docs

- src/output.rs
- src/wayland/output/handlers.rs
- src/wayland/output/mod.rs
Generally it's best not to hold strong references like this in user data, and it's definitely important if we use `WeakOutput::is_alive` for anything (https://github.com/Smithay/smithay/issues/1584). In any case, making it weak seems to be easy.
This alone didn't solve the issue I was seeing in cosmic-comp (which https://github.com/pop-os/cosmic-comp/pull/990 addresses, at least for now), so there may be more `Output` strong references to deal with somewhere...
> Use `WeakOutput` in `OutputUserData`, `Output` in `WlOutputData`

- anvil/src/udev.rs
- smallvil/src/state.rs
Storing a `LoopHandle` clone in its callback causes "Self-ownership" of `Rc`.
> Anvil: fix `LoopHandle` leak

- src/backend/drm/device/atomic.rs
Guess it got left over from refactoring.
> Remove unused format specifier

- src/utils/geometry.rs
this pr is two commits
- in [b5b9410409f2de6eb42084754451fa7fcbf37e17] i `impl Sub for Size`, that just mirrors what the `SubAssign` already does
- [ecb3f8565594bbdbd325ce54c6cd345e8072e186] might be a little controvertial: `Sub` and `SubAssign` operations on `Size` are already saturating, but they saturate to `i32::MIN`, which i don't personally think is very useful, because a `Size` can (should) not be negative, which means that i always have to check before subtracting two sizes. i changed it so they saturate to `0`.
to saturate to 0, i added an assossiated `const ZERO: Self` to the `Coordinate` trait.
if you prefer, i could move them to a `Size::saturating_sub(other: Size)` instead, but i think that this change makes `Size` more convenient to use.
> zero-saturating size sub

- anvil/src/input_handler.rs
- src/backend/input/tablet.rs
- src/backend/libinput/tablet.rs
I noticed that `TabletToolEvent` provides methods like `position_transformed`, but doesn't depend on `AbsolutePositionEvent`. This makes it slightly inconvenient to make generic code that handles both tablet and touch events.
I think this is a reasonable way to change this.
> input: Make `TabletToolEvent` depend on `AbsolutePositionEvent`, and apply output transform to tablet events in anvil

- src/backend/drm/compositor/mod.rs
- src/backend/drm/mod.rs
- src/backend/drm/surface/atomic.rs
- src/backend/drm/surface/gbm.rs
- src/backend/drm/surface/mod.rs
Draft while this is missing docs and more testing.
Adds helper methods to make it possible to set VRR per frame, which makes more dynamic VRR policies like "only enable, when we have a fullscreen application" more easily possible. Also simplifies VRR checks.
> drm: Add vrr property helpers

- Cargo.toml
- src/backend/allocator/gbm.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/gbm.rs
- src/backend/drm/surface/gbm.rs
Depends on https://github.com/Smithay/gbm.rs/pull/25.
> Update `gbm` to 0.18

- src/backend/renderer/multigpu/mod.rs
It doesn't seem `GpuManager` has a way to get a list of all backend renders; or other information about devices. (Calling `GraphicsApi::enumerate` in multiple places would not be correct.)
This seems useful in some cases, and easy to support.
(My use case is to dynamically configure a shader, and compile the shader on all GPUs when the shader is changed. Which needs a way to iterate over the `GlesRenderer`s).
> Add `GpuManager::devices` methods

- src/backend/renderer/gles/mod.rs
- src/backend/renderer/pixman/mod.rs
This fixes an error I noticed in https://github.com/Smithay/smithay/pull/1497 where it the renderer couldn't access an shm buffer that had been destroyed. I believe using a strong reference to the `WlBuffer` won't cause issues here.
For dmabuf buffers, retaining a strong `Dmabuf` would not be correct, since the caching is based on strong references to the `Dmabuf`. I've tested that the same error doesn't occur with dmabufs though. I guess as long as there is a strong reference in the `WaylandSurfaceRenderElement`, the user data of the `WlBuffer` has a strong reference to the `Dmabuf`.
So no corresponding change is needed for dmabufs, though perhaps its worth thinking if caching could be done differently. It could cache by `Weak<WlBuffer>` instead of `WeakDmabuf`  by implementing …
> Pixman (and gles) renderer fixes

- Cargo.toml
- src/backend/allocator/dmabuf.rs
- src/backend/renderer/pixman/mod.rs
Needs testing. Compiles, but I haven't checked that the `borrow_mut` calls can't panic.
Requires https://github.com/cmeissl/pixman-rs/pull/19.
> Update to `pixman` 0.2, and make `PixmanTexture` thread-safe

- src/backend/renderer/gles/mod.rs
- src/backend/renderer/gles/shaders/implicit/mod.rs
- src/backend/renderer/gles/shaders/mod.rs
- src/backend/renderer/gles/texture.rs
https://registry.khronos.org/OpenGL/specs/es/2.0/es_full_spec_2.0.pdf appendix C states that programs, like textures, can be shared between contexts. So I believe this has the same considerations for use in different renderers/contexts/threads as `GlesTexture`.
> Make `GlesPixelProgram` / `GlesTexProgram` `Send + Sync`

- src/backend/renderer/multigpu/mod.rs
Renderers require mut references for most things. Allocators also need an `&mut` to allocate. The `node` isn't mutable, though `mem::swap` could replace the whole `GbmGlesDevice` (already possible elsewhere with the just renderer).
> Add a `GpuManager::device_mut()` method

- src/backend/allocator/gbm.rs
fixes a regression introduced by https://github.com/Smithay/smithay/pull/1594
> fix compilation without fd_for_plane

- src/wayland/compositor/transaction.rs
use weak surface ref inside transaction to prevent keeping them alive longer as needed
this also resolves a deadlock when trying to send events in a drop impl stored in the surface state of a blocked transaction
see https://github.com/Smithay/wayland-rs/pull/772 for a different way to solve the same deadlock
> use weak surface ref inside transaction

- src/wayland/shell/mod.rs
- src/wayland/shell/xdg/handlers.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/handlers/surface/toplevel.rs
- src/wayland/shell/xdg/mod.rs
- src/wayland/xdg_foreign/handlers.rs
- src/wayland/xdg_foreign/mod.rs
Several things here:
1. Add a self-parent and a parent loop check when setting a parent, corresponding to the protocol:
> The parent toplevel must not be one of the child toplevel's descendants, and the parent must be different from the child toplevel, otherwise the invalid_parent protocol error is raised.
1. Fix inverted logic in xdg-foreign, tested with xdg-desktop-portal-gnome dialogs.
1. Expose an `XdgShellHandler::parent_changed()` callback so compositors can react to parent changes.
The primary use is to restack surfaces as the protocol intends:
> This surface should be stacked above the parent surface and all other ancestor surfaces.
Another use is to signal parent changes to wlr-foreign-toplevel-management.
This makes xdg-foreign depend on `XdgShellHandler`. Not sure if it's …
> Toplevel parent fixes, checks, and callback

- src/wayland/shell/xdg/mod.rs
The pending configures are useful for when you need to check the state that you sent to the client, but that it hadn't acknowledged yet, along with their serials. I only expose read access so that you can't mess with the internal commit tracking.
The serials in general (like the current state serial) are useful in case you want to synchronize something to surface commits. The case I have in niri is that I want to know if the surface had already committed the state that it had last acked, or not yet. Specifically, for the surface size, I want to differentiate between when the surface acked a new size and hasn't committed in response yet, and when the surface acked a new size but committed a different size in response.
> xdg: Add getters for pending configures and current state serial

- anvil/src/input_handler.rs
Fixes input to layer-shell surfaces that are not on the first output.
> anvil: Subtract `output.geo.loc` in calls to `layer_under`

- .github/workflows/ci.yml
- Cargo.toml
- anvil/Cargo.toml
- anvil/src/drawing.rs
- anvil/src/render.rs
- anvil/src/udev.rs
- anvil/src/winit.rs
- anvil/src/x11.rs
- clippy.toml
- examples/buffer_test.rs
- src/backend/allocator/swapchain.rs
- src/backend/drm/compositor/frame_result.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/exporter/dumb.rs
- src/backend/drm/exporter/gbm.rs
- src/backend/drm/exporter/mod.rs
- src/backend/drm/mod.rs
- src/backend/drm/output.rs
- src/backend/renderer/damage/mod.rs
- src/backend/renderer/gles/mod.rs
- src/backend/renderer/gles/shaders/mod.rs
- src/backend/renderer/test.rs
- src/backend/vulkan/mod.rs
- src/desktop/mod.rs
- src/desktop/space/mod.rs
- src/input/keyboard/keymap_file.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/pointer_constraints.rs
- src/wayland/shm/pool.rs
highly wip of the ideas described here: https://github.com/pop-os/cosmic-comp/pull/969#issuecomment-2450833400
it implements most of the stuff, except:
- the capabilities stuff
- the actual format selection
- some things are stubs and need to be implemented properly
not extensively tested, but anvil seems to still be able to launch.
returning an error from `DrmCompositor::new` also successfully triggers the format selection
logic
A lot...
If this turns out to be problematic we can disable the event for `commit_frame`, but we need to make sure
to kick off rendering in this case somehow..
> DrmOutputManager

- src/backend/input/mod.rs
These are the keycodes my own mouse produces for these actions (Logitech G102, `046d:c092`), although it might be influenced by `libratbag`.
This also matches winit and chromium.
> input: Treat Mouse `BTN_SIDE` and `BTN_EXTRA` as `MouseButton::Back` and `MouseButton::Forward` Respectively

- Cargo.toml
- src/backend/egl/display.rs
- src/backend/egl/ffi.rs
- src/backend/renderer/pixman/mod.rs
- src/backend/vulkan/mod.rs
- src/utils/ids.rs
- src/utils/user_data.rs
- src/wayland/shm/pool.rs
- src/wayland/xdg_toplevel_icon.rs
`once_cell` can now be fully replaced by `std`.
> Drop `once_cell` dependency

- anvil/src/state.rs
- anvil/src/udev.rs
This finally makes vulkan fifo mode work correctly on anvil.
Tested with `vkmark -p fifo` which now outputs steady 60fps on my laptop.
closes #1583
> anvil: fix vulkan fifo mode

- src/wayland/shell/xdg/mod.rs
These two changes are used for https://github.com/pop-os/cosmic-comp/pull/1122.
Cosmic-comp's implementation is a little unusual. It tries to fit the popup within the tile if it can do so without resizing. If this fails, it instead tries to fit it within the output, using resizes as well if still needed. I'm not sure if many compositors will need this, but this seems as good a way as any to expose a way to do this.
It also has a check to test which output the anchor point is in. It seems reasonable to expose this as a method.
> xdg: Add `get_anchor_point method` to `PositionerState`

- src/backend/drm/surface/atomic.rs
`Invalid screen configuration` issues are rare these days, but decrypting them from logs is very cumbersome whenever they occur. This is mostly due to the property handles not having any meaning, if you don't have the property mapping.
So we do log the mapping now as well.
Additionally in debug mode we construct the whole request differently to give us actually nice output. We need a bunch of collections to do so, so this is inefficient enough to only do in debug builds, long term it might be better to find a solution how to deconstruct drm-rs's `AtomicModeReq`. But for now this should be a significant improvement.
> drm/atomic: Better logging for atomic requests

- src/backend/drm/compositor/mod.rs
So because we are allocating a new buffer for cursor planes, the `config.dst` of the previous plane state might not actually represent the size of the cursor element, but simply the size of the cursor-plane (or the nearest size hint).
That might stay the same, if the cursor is simply rescaled, resulting in our tests failing to detect, that we need to redraw. This in particular happens with `MemoryRenderElements` + `RescaleRenderElements`, where neither the `Id` nor the `commit_counter` changes. So we have to remember the element size.
(Or we make `src`/`dst` actually use the cursor size, without re-allocating the buffer of course, but I am not sure, if compatibility for that is so great. Generally cursor planes don't seem very capable.)
> compositor: Fix cursor redraw on scale change

- src/wayland/selection/primary_selection/mod.rs
- src/wayland/selection/wlr_data_control/device.rs
- src/wayland/selection/wlr_data_control/mod.rs
I'm working on a PR for niri to disable the primary selection. I've had to make some changes in Smithay in order to support disabling of the primary selection at runtime (live-reloading of the config).
Niri PR: https://github.com/YaLTeR/niri/pull/1011
@kchibisov I was told you were the last person who reworked clipboard handling in Smithay, and that you might want to take a look at these changes.
> Add primary-selection filter

- src/wayland/text_input/text_input_handle.rs
This PR fixes issue https://github.com/Smithay/smithay/issues/1604
According to the text input v3 specification, the enable request should activate at most one text input on the compositor and ignore any subsequent enable requests until a disable request is received.
However, currently, Smithay does not guarantee this behavior and sends events to all text input objects created by the same client.
We will modify it to send events only to the text input object that has received the enable request and update the management of the enabled text input objects.
> Fix repeated key input issue in Chrome with multiple windows

- src/backend/renderer/gles/element.rs
- src/backend/renderer/gles/mod.rs
No idea, why I didn't do this earlier, but this makes the `PixelShaderElement` properly deal with `src` and `dest`, making it work correctly with the `RescaleRenderElement` and `CropRenderElement`.
This PR slightly changes the public api of the `GlesRenderer`, but neither breaks compatibility with existing shaders nor of the api of the `PixelShaderElement`, so most compositors will likely be fine.
> gles/element: Take `src` into account

- src/utils/clock.rs
As far as I can tell, this way of computing the returned value should match libinput, e.g.:
* https://gitlab.freedesktop.org/libinput/libinput/-/blob/1.22-branch/src/libinput.c#L546
* https://gitlab.freedesktop.org/libinput/libinput/-/blob/1.22-branch/src/util-time.h#L72-76
Fixes #1639. For v0.4.2 pls
> clock: Fix current monotonic time in millis u32 overflow panic

- src/xwayland/xwm/mod.rs
- src/xwayland/xwm/surface.rs
This PR sets the `override_redirect` field on `X11Surface` to false inside of `Event::MapRequest`. According to [these here docs](https://x.org/releases/X11R7.7/doc/man/man3/XMapWindow.3.xhtml), `MapRequest` only happens when override-redirect is false. However, if an X11 window was created with override_redirect set to true then later set it false before mapping, we reached `MapRequest` with an `X11Surface` whose `override_redirect` was still true, never updating it. This led to weird side-effects like configures and maps failing.
As it turns out, if you update the flag to false then windows actually start showing up! After testing with cosmic-comp, this should fix pop-os/cosmic-comp#1089 and pop-os/cosmic-comp#979. Haven't tested with the following but it may also fix …
> xwm: Update override-redirect flag on map request

- anvil/src/cursor.rs
This fixes an immediate crash when using [phinger-cursors-dark](https://github.com/phisch/phinger-cursors) as the cursor theme.
I'm not entirely sure if a delays of 0 are valid and if this is how they should be handled (this still skips all such frames, except if it's the first and all frames have a delay of 0), it's undocumented beyond "delay: CARD32 Delay between animation frames in milliseconds" in XCURSOR(3).
> anvil: Avoid panicing on cursor themes with a total delay of 0

- src/wayland/input_method/input_method_handle.rs
- src/wayland/input_method/input_method_keyboard_grab.rs
- src/wayland/text_input/text_input_handle.rs
Only one text-input must be enabled at a time, by checking the text-input id when issuing a request and comparing to the active one, however the regular `Enabled` events must be send for all of them, and as for the leave, we also send it for all the events to make it symmetrical with the `enter.
Fixes: 475072d410df (text-input: Ensure only one enabled...)
Fixes #1604.
--
Should be backported to patch release, otherwise text-input doesn't work at all.
> text-input: fix active instance tracking

- src/wayland/input_method/input_method_handle.rs
- src/wayland/seat/keyboard.rs
- src/wayland/text_input/text_input_handle.rs
Fixes #1614.
--
Can backport as well, since it's a bug fix.
> text-input: properly handle double buffered state

- src/utils/hook.rs
- src/wayland/compositor/tree.rs
- src/wayland/drm_syncobj/mod.rs
- src/wayland/shm/mod.rs
Currently, the `usize` ID is recycled in `Hook`’s destructor. However, since `Hook` also implements `Clone`, the `usize` ID might be recycled more than once. And `HookId` might still be used even after the `usize` ID has already been recycled.
This PR moves the ID recycling to `HookId`’s destructor. The trade-off is that `HookId` can't be `Copy`.
Actually, I’m not sure if we even need a recyclable ID implementation, it just adds extra complexity. If we’re using a `u64` for the ID, running out of values shouldn’t really be a concern.
> utils: Fix `HookId` recycle logic

- Cargo.toml
- src/wayland/selection/device.rs
- src/wayland/selection/ext_data_control/device.rs
- src/wayland/selection/ext_data_control/mod.rs
- src/wayland/selection/ext_data_control/source.rs
- src/wayland/selection/mod.rs
- src/wayland/selection/offer.rs
- src/wayland/selection/seat_data.rs
- src/wayland/selection/source.rs
- src/wayland/selection/wlr_data_control/device.rs
- src/wayland/selection/wlr_data_control/mod.rs
- `wayland.selection: ExtDataControl` Adds support for the new ext data control protocol
- `wayland.selection: Introduce DataDeviceKind` Removes `TypeId` in favor of `DataDeviceKind` enum
> wayland.selection: Introduce ext data control protocol

- src/wayland/idle_notify/mod.rs
draft as version 2 is still in MR phase: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/367
> wayland.idle_notify: Update to version 2

- src/utils/geometry.rs
fixes a typo in the function name: "extremities" is the correct name, "extemities" is just a misspelling
the function is not that common to call from outside of smithay, anvil don't use it at all, cosmic uses it exactly once and niri only three times, but it is still a breaking change, so i just deprecated it and hid it on the docs instead of removing it.
> rename Rectangle::from_extemities to Rectangle::from_extremeties

- src/wayland/xdg_activation/mod.rs
I'm not sure about the api style, alternatively this could return a `&mut XdgActivationTokenData` instead and drop the argument. This is breaking, but not for the common case of `activation_state.create_external_token(None)`.
Example usage in niri ipc (not upstreamed), creating an activation token as if it was created by the focused/requested window:
```rs
Request::DebugCreateActivationToken { id } => {
let (tx, rx) = async_channel::bounded(1);
ctx.event_loop.insert_idle(move |state| {
let window = id
.and_then(|id| {
state
.niri
.layout
.windows()
.find(|(_, m)| m.id().get() == id)
.map(|(_, w)| w)
})
.or_else(|| state.niri.layout.focus());
let toplevel = window.map(|window| window.toplevel());
let app_id = toplevel
.and_then(|toplevel| with_toplevel_role(toplevel, |role| …
```
> xdg_activation: Allow passing all data in `XdgActivationState::create_external_token`

- Cargo.toml
Just disables linking of libseat in docs-rs environment
> Fixup docs-rs build

- src/backend/renderer/gles/texture.rs
Intended for usecases like `TextureRenderBuffer` where the texture contents can change. If someone else references the same texture (for example, someone stored the texture render element for later use), the texture contents would change under the hood for them. This method lets the compositor check that nobody else has a reference to the same texture, making it safe to change its contents.
This doesn't (cannot) track extra graphics API references to the same texture object, but those are harder to make and less common; the compositor can figure out the uniqueness on its own then.
Questions for review:
1. Do I understand correctly that the TTY/winit backends don't keep other references to the textures? E.g. they don't create raw OpenGL references that go around this `Arc`.
2. Does the …
> gles/texture: Add is_unique_reference()

- src/backend/renderer/gles/mod.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/pixman/mod.rs
- src/backend/renderer/test.rs
I think it is pretty reasonable to be able to query the format and size of a bound framebuffer.
This is particularly useful in code that might now get passed in an opaque framebuffer handle, but needs to know the format/size to allocate an offscreen texture for post-processing. Sending this data out of band seems entirely unnecessary.
Bike-shedding: Should we rename the `Texture` trait at this point?
> renderer: Require `Texture` for framebuffer types

- src/utils/iter.rs
- src/utils/mod.rs
- src/wayland/output/mod.rs
- src/wayland/seat/keyboard.rs
- src/wayland/seat/pointer.rs
This allows implementing for examples Xwayland eavesdropping like KDE implements for global shortcuts: https://invent.kde.org/plasma/kwin/-/merge_requests/1950
> seat: Allow accessing `WlKeyboard`/`WlPointer` instances

- src/wayland/compositor/tree.rs
Fixes https://github.com/Smithay/smithay/issues/1693, though there may be other issues around double-buffering state, or producing protocol errors if the surface is destroy before the corresponding subsurface.
This matches Gnome. Sway doesn't seem to produce any error. So maybe wayland should clarify the correct behavior here, but a protocol error seems most reasonable.
In any case, certainly better than crashing the compositor, and it's easier to test the client when it isn't crashing the compositor.
> Protocol error instead of panic if `place_above`/`_below` has no parent

- src/xwayland/xwm/mod.rs
Apparently `XChangeWindowAttributes` can be used to change the `override-redirect` flag for a window, and some clients create a window without the flag, then set it this way. So we should handle the flag in `MapNotify` to detect this.
Perhaps some other things should be changed, but this seems to help. This fixes menus not showing up on cosmic-comp in REAPER and Intel Questa, and presumably various other clients.
> xwm: Update `override_redirect` in `MapNotify` handler

- Cargo.toml
- smallvil/src/grabs/resize_grab.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/device/mod.rs
- src/backend/drm/mod.rs
- src/backend/drm/output.rs
- src/backend/mod.rs
- src/lib.rs
- src/wayland/selection/data_device/mod.rs
- src/wayland/shell/xdg/mod.rs
- src/xwayland/xserver.rs
- src/xwayland/xwm/mod.rs
A lot of games expect to be able to query a primary output via xrandr. This adds a way for compositors to manage this state.
> xwm: Add events/method for randr primary output management

- src/backend/renderer/damage/mod.rs
- src/backend/renderer/element/memory.rs
- src/backend/renderer/element/solid.rs
- src/backend/renderer/element/surface.rs
- src/backend/renderer/element/texture.rs
- src/backend/renderer/gles/mod.rs
- src/backend/renderer/glow.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/renderer/pixman/mod.rs
- src/backend/renderer/test.rs
- src/backend/renderer/utils/wayland.rs
- wlcs_anvil/src/main_loop.rs
Introduce `ContextId` to represent a renderer context, replacing the previous use of `TypeId` + `usize` ID.
This also aligns with the best practice of using the newtype pattern for IDs.
> renderer: Introduce `ContextId`

- src/xwayland/xwm/settings.rs
Forgot the pad when implementing this and only noticed this now trying to set `Gtk/CursorThemeName`.
> xsettings: Fix string values

- anvil/README.md
4deb3d5c seems to have removed this.
> anvil: Remove documentation for `ANVIL_DISABLE_DRM_COMPOSITOR`

- src/input/keyboard/mod.rs
- src/input/keyboard/modifiers_state.rs
to enable compositor side control of modifiers such as num lock.
This PR is an implementation of a [recommendation](https://github.com/YaLTeR/niri/issues/291#issuecomment-2657328970) made by @kylewillmon in a Niri issue requesting support to enable num lock at startup: https://github.com/YaLTeR/niri/issues/291
Disclaimer: I'm new to rust so I'm extra happy for all feedback that points out code smells.
> feat: implement KeyboardHandle::set_modifier_state

- src/wayland/xwayland_keyboard_grab.rs
These changes should both be helpful for custom implementations (and the default has issues: https://github.com/Smithay/smithay/issues/1714).
The default behavior should ideally be improved, but if `XWaylandKeyboardGrabHandler::grab` is an overridable method, this makes sense to have anyway.
> xwayland_keyboard_grab: `Clone` impl and accessor for `ZwpXwaylandKeyboardGrabV1`

- src/backend/libinput/tablet.rs
Hi! I noticed that `TabletToolEvent<LibinputInputBackend>` incorrectly returns `dx` and `dy` properties of libinput event as `tilt_x` and `tilt_y` so pen tilt in drawing programs like Krita gets broken and I can't use brushes relying on it
Seems like everything is working correctly after my changes
> Fix incorrect tablet pen tilt handling in `libinput` backend

- Cargo.toml
- src/input/keyboard/keymap_file.rs
- src/input/keyboard/mod.rs
This fixes excessive keymap events with `virtual-keyboard-unstable-v1` clients like fcitx5.
This depends on `sha2`. Adding a new dependency for this is annoying, but this is a fairly widely used crate. `blake3` could also work but is less widely used. Perhaps a dependency couple be avoided if `SipHasher` is good enough, but as I understand it's not really meant to guarantee an absence of collisions (but may be good enough in practice here?).
I expect computing a hash won't impact performance much, compared to clients having to process excessive `keymap` events
> input/keyboard: Use hash for ID of `KeymapFile`

- src/input/keyboard/mod.rs
This fixes a bug where updated modifiers only become effective when the user triggers an additional (physical) modifier.
ref: https://github.com/YaLTeR/niri/issues/1501
> fix: store updated mods_state in KbdInternal in KeyboardHandle.set_modifier_state

- src/utils/geometry.rs
there already is an `impl Mul<N> for Size<N, Kind>`, so i think it just makes sense to also have a function that does the opposite. also saves me one `Size::from((size.w * 3 / 4, size.h * 3 / 4))` where i can now do a `size * 3 / 4`. you could also do this with `.downscale` (and `.upscale` respectively), but those are a little less convenient to use and (in my opinion) less clear.
> impl Div<N> for Size<N, Kind>

- Cargo.toml
- src/backend/allocator/dmabuf.rs
- src/utils/sealed_file.rs
- src/xwayland/x11_sockets.rs
i had to do 4 changes for the update:
1. i had to enable the "pipe" and "process" features. i think those were enabled by a transitive dependency on rustix, that had already enabled them, but since those were enabling them for rustix 0.38, i had to enable them explicitly for rustix 1.0.
2. similar to https://github.com/Smithay/drm-rs/pull/223, i had to change the generic for `rustix::ioctl` from a `type` to a `const`.
3. `rustix::event::poll` changed the type from a `c_int` to an `Option<&Timespec>`. since the timeout was 0, i don't have to convert anything and only construct a 0-ed `Timespec`. i opted against using `Timespec::default` as i thought that doing it this way was more clear.
4. rustix merged all of the `rustix::net::bind_*` fns into a single `rustix::net::bind` that takes an …
> update to rustix 1.0

- src/utils/geometry.rs
the main reason is that i was very annoyed at having to unnecessary double parenthesis when calling `Size::from((w, h))`, which i don't have to do with `Size::new(w, h)`.
another benefit is, that `Point::new` is const so you can create a `Point` in const (though i haven't ever needed that). since `Size::new` has a `debug_assert!` that calls a trait method, i cannot make that `const` without removing the assertion.
> implement a Point::new and a Size::new constructor

- src/backend/renderer/gles/mod.rs
The `unwrap_or_else()` call here in `import_shm_buffer()` has a call to `self.gl.GenTextures()`, but `self.egl.make_current()` was only being called in the next block.
It appears this was the cause of some issues I saw on a multi-GPU system, where `GenTextures` ended up being called on the last current context, which if it was on the other GPU, caused this `GlesTexture` to be using the same texture ID as whatever other texture was assigned the same ID.
> gles: Don't call `GenTextures` before `make_current()`

- anvil/src/udev.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/exporter/gbm.rs
See https://gitlab.freedesktop.org/drm/amd/-/issues/2075#note_2582039
> compositor/gbm: Don't scanout client buffers without explicit node matches

- src/backend/renderer/multigpu/mod.rs
I've been seeing `eglCreateImageKHR` errors here copying Nvidia buffers to AMD. And worse, this somehow lead to a crash in the Nvidia driver.
It seems this was trying to use an implicit modifier, resulting in something that won't import on the other GPU. Presumably we should just filter out `Modifier::Invalid` here.
> render/multigpu: Don't use implicit modifier in `dma_shadow_copy`

- src/input/mod.rs
The derived clone is only generated if all generic types implement Clone. In this case, that's wrong because the contained type is not meant to be Clone.
> Fix WeakSeat Clone

- src/desktop/wayland/layer.rs
- src/utils/geometry.rs
Stumbled upon this due to a use-after-free in quickshell, but it's quite easy to reproduce by just requesting i32::MAX margins over Wayland.
Sample test case in niri: https://github.com/YaLTeR/niri/commit/776c9bd2cda500bfa755a4a9149e6ab0300f95a5#diff-c9d5077797e52564389913b095b8def52b21223fe33660897c9d181354881a80R35
Initially I started converting all math to `.saturating_add()` but that got unwieldy so I decided to just wrap it in a `Saturating<>`.
> Fix integer overflows in `LayerMap::arrange()`

- anvil/src/state.rs
- examples/minimal.rs
- smallvil/src/handlers/mod.rs
- src/wayland/selection/data_device/device.rs
- src/wayland/selection/data_device/mod.rs
- src/wayland/selection/data_device/source.rs
- src/wayland/selection/ext_data_control/device.rs
- src/wayland/selection/ext_data_control/mod.rs
- src/wayland/selection/ext_data_control/source.rs
- src/wayland/selection/primary_selection/mod.rs
- src/wayland/selection/primary_selection/source.rs
- src/wayland/selection/seat_data.rs
- src/wayland/selection/source.rs
- src/wayland/selection/wlr_data_control/device.rs
- src/wayland/selection/wlr_data_control/mod.rs
- src/wayland/selection/wlr_data_control/source.rs
Smithay uses lazy notify when there's actual interaction, which is unexpected and doesn't properly reflect the state of the clipboard. Instead immediately notify clients when the source was destroyed.
Links: https://github.com/YaLTeR/niri/issues/1831
--
Need to do that for all the rest of the selections protocols and drop the `alive` check, I guess.
> selection: instantly notify clients when source dies

- CHANGELOG.md
- anvil/src/input_handler.rs
- anvil/src/main.rs
- anvil/src/udev.rs
- src/backend/drm/compositor/mod.rs
- src/backend/drm/exporter/gbm.rs
- src/backend/egl/display.rs
- src/backend/egl/mod.rs
- src/backend/renderer/gles/shaders/mod.rs
- src/backend/renderer/multigpu/mod.rs
- src/backend/vulkan/mod.rs
- src/input/keyboard/mod.rs
- src/wayland/dmabuf/dispatch.rs
- src/wayland/dmabuf/mod.rs
- src/wayland/drm_syncobj/mod.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/types.rs
- src/wayland/shm/handlers.rs
- src/wayland/shm/pool.rs
- src/xwayland/x11_sockets.rs
- src/xwayland/xserver.rs
This patch introduces a breaking change which allows restoring the pre-0.7.0 functionality of acccepting any node for direct scanout for the `GbmFramebufferExporter` constructor.
While it would be possible to do the same in a non-breaking manner by introducing a separate constructor, this should be more elegant long-term while requiring minimal breaking changes.
> Add option to accept any node for direct scanout

- src/backend/drm/compositor/mod.rs
- src/backend/drm/output.rs
Fixes framebuffer leaks with multi-threaded use of `DrmOutputManager`: https://github.com/pop-os/cosmic-comp/issues/1501
It would be good make sure non-threadsafe userdata will never leak; either handling that some way on drops on another thread, or only using non-threadsafe userdata on things that can't be sent across threads...
> drm/compositor: Use thread-safe user data for `CachedDrmFramebuffer`

- src/backend/drm/compositor/mod.rs
- src/backend/renderer/element/mod.rs
- src/backend/renderer/element/surface.rs
This adds an API to allow filtering, which elements should be considered for scanout and which shouldn't.
Example usage and motivation in cosmic: https://github.com/pop-os/cosmic-comp/pull/1542
Draft because I am not sure, if this is a particular good api for this feature. Ping @cmeissl on that.
Essentially since the `DrmCompositor` is the only piece of code using `underlying_storage` at the moment I opted for the lazy way of just returning `None`, if we don't want the target to be considered for scanout. This is a bit hacky, maybe another method would be more appropriate.
The bigger issue however is the change to `render_elements_from_surface_tree`.
I didn't want to modify `AsRenderElements` to pass through a closure barely used by any other element. This ends up still working in …
> element/surface: Allow filtering of scanout candidates

- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
If a renderer gets re-created with the same api and same node, existing cached `MultiTexture`s might be used with now outdated and invalid texture ids.
This happens e.g. in cosmic-comp, which destroys `EGLContext`s, when a particular device isn't used anymore to give the driver a chance to put the device into deeper sleep modes.
The obvious solution here is to not re-invent the wheel and only use `TypeId`s + `DrmNode`s for hashing but our new `ErasedContextId`, which will change for newly created renderers, that aren't based on the same context, essentially replacing the `DrmNode`-part of our previous hashes with what used to be the `RendererId`.
This also simplifies the `MultiTextureInternal`-struct and related code quite a bit, as we don't have a double nested `HashMap` anymore.
> multigpu: Don't re-use textures for re-created renderers

- src/utils/geometry.rs
This patch liberally sprinkles #[must_use] annotations on all geometry functions which return `Self` without modifying `self`.
---
I just wasted 3 seconds testing a patch just to realize I called `downscale` without assigning it to anything. This patch certainly takes a bit of a lazy approach just copy-pasting the annotations everywhere, but I do think that it's likely to save at least a couple minutes of developer headache in the long term.
> Add #[must_use] annotations to geometry module

- src/backend/drm/compositor/frame_result.rs
- src/backend/renderer/gles/mod.rs
- src/backend/renderer/glow.rs
- src/backend/renderer/mod.rs
- src/backend/renderer/multigpu/mod.rs
These methods are not part of a frame, so if an explicit sync point is needed, they need to return one.
I assume creating a sync point will have quite a low cost. When we're not exporting to an fd or waiting on a different renderer. Otherwise we might need a more cumbersome API; like an `&mut Option<SyncPoint>` method that is filled only if the caller needs a sync point. The `glFinish` invoked if EGL fences aren't supported would be more costly though; but that generally shouldn't be needed.
I think some of the synchronization may get more complicated with a Vulkan renderer, since Vulkan allows commands to complete out of order from when they are started and be synchronized separately, as I understand? I don't have experience with Vulkan synchronization though.
> Return `SyncPoint` from blit methods of renderer

- .gitignore
- CHANGELOG.md
- anvil/src/input_handler.rs
- anvil/src/shell/xdg.rs
- compile_wlcs.sh
- src/desktop/wayland/layer.rs
- src/desktop/wayland/popup/manager.rs
- src/desktop/wayland/popup/mod.rs
- src/wayland/session_lock/lock.rs
- src/wayland/session_lock/mod.rs
- src/wayland/session_lock/surface.rs
- src/wayland/shell/wlr_layer/handlers.rs
- src/wayland/shell/wlr_layer/mod.rs
- src/wayland/shell/xdg/handlers/surface.rs
- src/wayland/shell/xdg/handlers/surface/popup.rs
- src/wayland/shell/xdg/handlers/surface/toplevel.rs
- src/wayland/shell/xdg/mod.rs
Corresponding niri update: https://github.com/YaLTeR/niri/commit/5a4d794b17791386f4103415de95b7557cb369ad
Fixes my fullscreen anim bugs that I found with mpv and adwaita-1-demo.
----
The last-acked configure is part of the committed state, and should be tracked as such. Before this commit, it would be possible to observe a newer "current state" in a commit handler if the surface acked the next state while the compositor was waiting on a blocker set in a pre-commit handler.
As part of the change, the current_state() getter was removed, because it's confusing and likely not what you actually want. For instance, several uses in Anvil actually needed to access a different state.
The WmCapabilities checks in Anvil were removed because they are serverside and don't change; not sure what the …
> xdg-shell, layer-shell, session-lock: Track last acked configure in MultiCache

- src/xwayland/xwm/surface.rs
This PR exposes the previously private InputMode enum in xwm/surface.
I renamed the enum to WmInputModel for consistency with the ICCCM documentation.
This is needed in order for compositors to correctly handle keyboard focus for some applications.
Intellij IDEA, for example, has its root window set to GloballyActive and its dialogs set to None. It's currently impossible to correctly focus the GloballyActive root window while avoiding focusing the None dialog.
> xwm: Expose WmInputModel
